CREATE TABLE USER_ENTITY
(
    ID                  VARCHAR(2048) PRIMARY KEY,
    USERNAME            VARCHAR(512) UNIQUE NOT NULL,
    ORGANISASJONSNUMMER VARCHAR(64)         NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGGED_IN      TIMESTAMP,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);