export const Diagnoser = {
	ICPC2: [
		{ code: 'A01', text: 'Smerte generell/flere steder' },
		{ code: 'A02', text: 'Frysninger' },
		{ code: 'A03', text: 'Feber' },
		{ code: 'A04', text: 'Slapphet/tretthet' },
		{ code: 'A05', text: 'Sykdomsfølelse' },
		{ code: 'A06', text: 'Besvimelse/synkope' },
		{ code: 'A07', text: 'Bevisstløshet/koma' },
		{ code: 'A08', text: 'Hevelse/oppfylning IKA' },
		{ code: 'A09', text: 'Svetteproblemer' },
		{ code: 'A10', text: 'Blødning IKA' },
		{ code: 'A11', text: 'Brystsmerte IKA' },
		{ code: 'A13', text: 'Engstelig for behandling' },
		{ code: 'A16', text: 'Irritabelt/urolig spedbarn' },
		{ code: 'A18', text: 'Bekymret/opptatt av utseende IKA' },
		{ code: 'A20', text: 'Dødshjelp diskusjon/spørsmål om' },
		{ code: 'A21', text: 'Økt risiko for ondartet svulst' },
		{ code: 'A23', text: 'Risiko for sykdom IKA' },
		{ code: 'A25', text: 'Engstelig for døden' },
		{ code: 'A26', text: 'Engstelig for kreft IKA' },
		{ code: 'A27', text: 'Engstelig for sykdom IKA' },
		{ code: 'A28', text: 'Redusert funksjonsevne IKA' },
		{ code: 'A29', text: 'Generelle symptomer/plager IKA' },
		{ code: 'A30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'A31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'A32', text: 'Sensitivitetsprøve' },
		{ code: 'A33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'A34', text: 'Blodprøve IKA' },
		{ code: 'A35', text: 'Urinprøve IKA' },
		{ code: 'A36', text: 'Avføringsprøve IKA' },
		{ code: 'A37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'A38', text: 'Laboratorieprøve IKA' },
		{ code: 'A39', text: 'Fysisk funksjonsprøve' },
		{ code: 'A40', text: 'Endoskopi' },
		{ code: 'A41', text: 'Billeddiagnostikk' },
		{ code: 'A42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'A43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'A44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'A45', text: 'Helseopplysning/rådgivning' },
		{ code: 'A46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'A47', text: 'Kontakt med spesialist' },
		{ code: 'A48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'A49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'A50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'A51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'A52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'A53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'A54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'A55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'A56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'A57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'A58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'A59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'A60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'A61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'A62', text: 'Administrativ prosedyre' },
		{ code: 'A63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'A64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'A65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'A66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'A67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'A68', text: 'Henvisning IKA' },
		{ code: 'A69', text: 'Kontaktårsak IKA' },
		{ code: 'A70', text: 'Tuberkulose' },
		{ code: 'A71', text: 'Meslinger' },
		{ code: 'A72', text: 'Vannkopper' },
		{ code: 'A73', text: 'Malaria' },
		{ code: 'A74', text: 'Røde hunder' },
		{ code: 'A75', text: 'Mononukleose' },
		{ code: 'A76', text: 'Virussykdom med utslett IKA' },
		{ code: 'A77', text: 'Virussykdom IKA' },
		{ code: 'A78', text: 'Infeksjonssykdom IKA' },
		{ code: 'A79', text: 'Ondartet svulst IKA' },
		{ code: 'A80', text: 'Skade/traume IKA' },
		{ code: 'A81', text: 'Multiple skader/traumer' },
		{ code: 'A82', text: 'Følgetilstand skade/traume' },
		{ code: 'A84', text: 'Legemiddelforgiftning' },
		{ code: 'A85', text: 'Bivirkning legemiddel' },
		{ code: 'A86', text: 'Toksisk virkning stoff IKA' },
		{ code: 'A87', text: 'Komplikasjon etter behandling' },
		{ code: 'A88', text: 'Skadevirkning av fysisk faktor' },
		{ code: 'A89', text: 'Komplikasjoner/problemer med protese' },
		{ code: 'A90', text: 'Medfødt feil IKA/multiple feil' },
		{ code: 'A91', text: 'Unormalt funn ved undersøkelse IKA' },
		{ code: 'A92', text: 'Allergi/allergisk reaksjon IKA' },
		{ code: 'A93', text: 'Prematurt/immaturt levendefødt barn' },
		{ code: 'A94', text: 'Perinatal sykelighet IKA' },
		{ code: 'A95', text: 'Perinatal død' },
		{ code: 'A96', text: 'Død/dødsfall IKA' },
		{ code: 'A97', text: 'Administrativ kontakt/undersøkelse' },
		{ code: 'A98', text: 'Individforebyggende tiltak' },
		{ code: 'A981', text: 'Cytologi livmorhals screening' },
		{ code: 'A99', text: 'Helseproblem/sykdom IKA' },
		{ code: 'B02', text: 'Lymfeknuter forstørrede/smertefulle' },
		{ code: 'B04', text: 'Blod/blodsystemet symptomer/plager' },
		{ code: 'B25', text: 'Engstelig for HIV/AIDS' },
		{ code: 'B26', text: 'Engstelig for kreft blod/lymfesystem' },
		{ code: 'B27', text: 'Engstelig for blod/lymfe sykdom IKA' },
		{ code: 'B28', text: 'Redus funksjonsevne pga blod/lymfe' },
		{ code: 'B29', text: 'Blod/lymfesystem sympt/plager IKA' },
		{ code: 'B30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'B31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'B32', text: 'Sensitivitetsprøve' },
		{ code: 'B33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'B34', text: 'Blodprøve IKA' },
		{ code: 'B35', text: 'Urinprøve IKA' },
		{ code: 'B36', text: 'Avføringsprøve IKA' },
		{ code: 'B37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'B38', text: 'Laboratorieprøve IKA' },
		{ code: 'B39', text: 'Fysisk funksjonsprøve' },
		{ code: 'B40', text: 'Endoskopi' },
		{ code: 'B41', text: 'Billeddiagnostikk' },
		{ code: 'B42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'B43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'B44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'B45', text: 'Helseopplysning/rådgivning' },
		{ code: 'B46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'B47', text: 'Kontakt med spesialist' },
		{ code: 'B48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'B49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'B50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'B51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'B52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'B53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'B54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'B55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'B56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'B57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'B58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'B59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'B60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'B61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'B62', text: 'Administrativ prosedyre' },
		{ code: 'B63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'B64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'B65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'B66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'B67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'B68', text: 'Henvisning IKA' },
		{ code: 'B69', text: 'Kontaktårsak IKA' },
		{ code: 'B70', text: 'Lymfadenitt akutt' },
		{ code: 'B71', text: 'Lymfadenitt kronisk/uspesifikk' },
		{ code: 'B72', text: 'Hodgkins sykdom/lymfom' },
		{ code: 'B73', text: 'Leukemi' },
		{ code: 'B74', text: 'Ondartet svulst blod/lymfesystem IKA' },
		{ code: 'B75', text: 'Godartet/uspes svulst blod/lymfe' },
		{ code: 'B76', text: 'Miltruptur traumatisk' },
		{ code: 'B77', text: 'Skade blod/lymfesystem IKA' },
		{ code: 'B78', text: 'Arvelig hemolytisk anemi' },
		{ code: 'B79', text: 'Medfødt feil blod/lymfesystem IKA' },
		{ code: 'B80', text: 'Jernmangelanemi' },
		{ code: 'B81', text: 'Anemi B12/folsyremangel' },
		{ code: 'B82', text: 'Anemi IKA' },
		{ code: 'B83', text: 'Purpura/koagulasjonsdefekt' },
		{ code: 'B84', text: 'Unormale hvite blodceller' },
		{ code: 'B87', text: 'Forstørret milt' },
		{ code: 'B90', text: 'HIV-sykdom/AIDS' },
		{ code: 'B99', text: 'Blod/lymfe/milt sykdom IKA' },
		{ code: 'D01', text: 'Abdominalsmerte/krampe generell' },
		{ code: 'D02', text: 'Abdominalsmerte epigastriet' },
		{ code: 'D03', text: 'Halsbrann' },
		{ code: 'D04', text: 'Endetarmssmerte' },
		{ code: 'D05', text: 'Perianal kløe' },
		{ code: 'D06', text: 'Abdominalsmerte lokalisert IKA' },
		{ code: 'D07', text: 'Dyspepsi/fordøyelsesbesvær' },
		{ code: 'D08', text: 'Flatulens/oppblåsthet/raping' },
		{ code: 'D09', text: 'Kvalme' },
		{ code: 'D10', text: 'Oppkast/brekninger' },
		{ code: 'D11', text: 'Diaré' },
		{ code: 'D12', text: 'Forstoppelse' },
		{ code: 'D13', text: 'Gulsott' },
		{ code: 'D14', text: 'Oppkast med blod/hematemese' },
		{ code: 'D15', text: 'Melena' },
		{ code: 'D16', text: 'Rektalblødning' },
		{ code: 'D17', text: 'Inkontinens avføring' },
		{ code: 'D18', text: 'Endring i avføring/avføringsvane' },
		{ code: 'D19', text: 'Tenner/tannkjøtt symptomer/plager' },
		{ code: 'D20', text: 'Munn/tunge/lepper symptomer/plager' },
		{ code: 'D21', text: 'Svelgebesvær' },
		{ code: 'D23', text: 'Forstørret lever' },
		{ code: 'D24', text: 'Abdominal oppfylling/kul IKA' },
		{ code: 'D25', text: 'Utspilt abdomen' },
		{ code: 'D26', text: 'Engstelig for kreft fordøyelsesyst' },
		{ code: 'D27', text: 'Engstelig for fordøyelsesykdom IKA' },
		{ code: 'D28', text: 'Redusert funksjonsevne fordøy probl' },
		{ code: 'D29', text: 'Fordøyelsesyst symptomer/plager IKA' },
		{ code: 'D30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'D31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'D32', text: 'Sensitivitetsprøve' },
		{ code: 'D33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'D34', text: 'Blodprøve IKA' },
		{ code: 'D35', text: 'Urinprøve IKA' },
		{ code: 'D36', text: 'Avføringsprøve IKA' },
		{ code: 'D37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'D38', text: 'Laboratorieprøve IKA' },
		{ code: 'D39', text: 'Fysisk funksjonsprøve' },
		{ code: 'D40', text: 'Endoskopi' },
		{ code: 'D41', text: 'Billeddiagnostikk' },
		{ code: 'D42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'D43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'D44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'D45', text: 'Helseopplysning/rådgivning' },
		{ code: 'D46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'D47', text: 'Kontakt med spesialist' },
		{ code: 'D48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'D49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'D50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'D51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'D52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'D53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'D54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'D55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'D56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'D57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'D58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'D59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'D60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'D61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'D62', text: 'Administrativ prosedyre' },
		{ code: 'D63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'D64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'D65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'D66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'D67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'D68', text: 'Henvisning IKA' },
		{ code: 'D69', text: 'Kontaktårsak IKA' },
		{ code: 'D70', text: 'Tarminfeksjon' },
		{ code: 'D71', text: 'Kusma' },
		{ code: 'D72', text: 'Virushepatitt' },
		{ code: 'D73', text: 'Gastroenteritt antatt infeksiøs' },
		{ code: 'D74', text: 'Ondartet svulst magesekk' },
		{ code: 'D75', text: 'Ondartet svulst tykktarm/endetarm' },
		{ code: 'D76', text: 'Ondartet svulst bukspyttkjertel' },
		{ code: 'D77', text: 'Ondartet svulst fordøyelsesyst IKA' },
		{ code: 'D78', text: 'Godartet/uspes svulst fordøyelsessys' },
		{ code: 'D79', text: 'Fremmedlegeme fordøyelsessystemet' },
		{ code: 'D80', text: 'Skade fordøyelsesystemet IKA' },
		{ code: 'D81', text: 'Medfødt feil fordøyelsesystem' },
		{ code: 'D82', text: 'Tenner/tannkjøtt sykdom' },
		{ code: 'D83', text: 'Munn/tunge/lepper sykdom' },
		{ code: 'D84', text: 'Spiserørssykdom' },
		{ code: 'D85', text: 'Sår i tolvfingertarm' },
		{ code: 'D86', text: 'Magesår IKA' },
		{ code: 'D87', text: 'Funksjonelle plager magesekk' },
		{ code: 'D88', text: 'Appendisitt' },
		{ code: 'D89', text: 'Lyskebrokk' },
		{ code: 'D90', text: 'Mellomgulvsbrokk' },
		{ code: 'D91', text: 'Abdominalt brokk IKA' },
		{ code: 'D92', text: 'Divertikkelsykdom i tarm' },
		{ code: 'D93', text: 'Irritabel tarm-syndrom' },
		{ code: 'D94', text: 'Kronisk enteritt/ulcerøs kolitt' },
		{ code: 'D95', text: 'Analfissur/perianal abscess' },
		{ code: 'D96', text: 'Orme-/parasittsykdom' },
		{ code: 'D97', text: 'Leversykdom IKA' },
		{ code: 'D98', text: 'Galleveisbetennelse/gallesten' },
		{ code: 'D99', text: 'Sykdom i fordøyelsessystemet IKA' },
		{ code: 'D991', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'D992', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'D993', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'D994', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'D995', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'D996', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'D997', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'D998', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'D999', text: 'Utbruddssykdom definert av FHI, fordøyelsessystemet' },
		{ code: 'F01', text: 'Øyesmerte' },
		{ code: 'F02', text: 'Rødt øye' },
		{ code: 'F03', text: 'Tåreflod/sekresjon øye' },
		{ code: 'F04', text: 'Synlige flekker/tråder i synsfelt' },
		{ code: 'F05', text: 'Synsforstyrrelse IKA' },
		{ code: 'F13', text: 'Øye unormal følelse' },
		{ code: 'F14', text: 'Øye unormal bevegelse' },
		{ code: 'F15', text: 'Øye unormalt utseende' },
		{ code: 'F16', text: 'Øyelokk symptomer/plager' },
		{ code: 'F17', text: 'Briller symptomer/plager' },
		{ code: 'F18', text: 'Kontaktlinser symptomer/plager' },
		{ code: 'F27', text: 'Engstelig for øyesykdom' },
		{ code: 'F28', text: 'Redusert funksjonsevne pga øyeprobl' },
		{ code: 'F29', text: 'Øye symptomer/plager IKA' },
		{ code: 'F30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'F31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'F32', text: 'Sensitivitetsprøve' },
		{ code: 'F33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'F34', text: 'Blodprøve IKA' },
		{ code: 'F35', text: 'Urinprøve IKA' },
		{ code: 'F36', text: 'Avføringsprøve IKA' },
		{ code: 'F37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'F38', text: 'Laboratorieprøve IKA' },
		{ code: 'F39', text: 'Fysisk funksjonsprøve' },
		{ code: 'F40', text: 'Endoskopi' },
		{ code: 'F41', text: 'Billeddiagnostikk' },
		{ code: 'F42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'F43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'F44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'F45', text: 'Helseopplysning/rådgivning' },
		{ code: 'F46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'F47', text: 'Kontakt med spesialist' },
		{ code: 'F48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'F49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'F50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'F51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'F52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'F53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'F54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'F55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'F56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'F57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'F58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'F59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'F60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'F61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'F62', text: 'Administrativ prosedyre' },
		{ code: 'F63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'F64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'F65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'F66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'F67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'F68', text: 'Henvisning IKA' },
		{ code: 'F69', text: 'Kontaktårsak IKA' },
		{ code: 'F70', text: 'Infeksiøs konjunktivitt' },
		{ code: 'F71', text: 'Allergisk konjunktivitt' },
		{ code: 'F72', text: 'Øyelokkbetennelse' },
		{ code: 'F73', text: 'Øye infeksjon/betennelse IKA' },
		{ code: 'F74', text: 'Svulst i øye/øyehule' },
		{ code: 'F75', text: 'Kontusjon/blødning i øye' },
		{ code: 'F76', text: 'Fremmedlegeme øye' },
		{ code: 'F79', text: 'Skade øye IKA' },
		{ code: 'F80', text: 'Tåreveisstenose/atresi spedbarn' },
		{ code: 'F81', text: 'Medfødt feil øye IKA' },
		{ code: 'F82', text: 'Netthinneløsning/rift' },
		{ code: 'F83', text: 'Retinopati' },
		{ code: 'F84', text: 'Makuladegenerasjon' },
		{ code: 'F85', text: 'Hornhinnesår' },
		{ code: 'F86', text: 'Trakom' },
		{ code: 'F91', text: 'Brytningsforstyrrelse' },
		{ code: 'F92', text: 'Grå stær/katarakt' },
		{ code: 'F93', text: 'Glaukom' },
		{ code: 'F94', text: 'Blindhet' },
		{ code: 'F95', text: 'Skjeling/strabisme' },
		{ code: 'F99', text: 'Øyesykdom IKA' },
		{ code: 'H01', text: 'Øresmerte/øreverk' },
		{ code: 'H02', text: 'Hørsel symptomer/plager' },
		{ code: 'H03', text: 'Øresus' },
		{ code: 'H04', text: 'Øreflod/sekresjon' },
		{ code: 'H05', text: 'Blødning øre' },
		{ code: 'H13', text: 'Øreplugg/øretetthet' },
		{ code: 'H15', text: 'Bekymret/opptatt av ørenes utseende' },
		{ code: 'H27', text: 'Engstelig for øresykdom' },
		{ code: 'H28', text: 'Redusert funksjonsevne pga øreprobl' },
		{ code: 'H29', text: 'Øre symptomer/plager IKA' },
		{ code: 'H30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'H31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'H32', text: 'Sensitivitetsprøve' },
		{ code: 'H33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'H34', text: 'Blodprøve IKA' },
		{ code: 'H35', text: 'Urinprøve IKA' },
		{ code: 'H36', text: 'Avføringsprøve IKA' },
		{ code: 'H37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'H38', text: 'Laboratorieprøve IKA' },
		{ code: 'H39', text: 'Fysisk funksjonsprøve' },
		{ code: 'H40', text: 'Endoskopi' },
		{ code: 'H41', text: 'Billeddiagnostikk' },
		{ code: 'H42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'H43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'H44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'H45', text: 'Helseopplysning/rådgivning' },
		{ code: 'H46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'H47', text: 'Kontakt med spesialist' },
		{ code: 'H48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'H49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'H50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'H51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'H52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'H53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'H54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'H55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'H56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'H57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'H58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'H59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'H60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'H61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'H62', text: 'Administrativ prosedyre' },
		{ code: 'H63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'H64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'H65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'H66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'H67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'H68', text: 'Henvisning IKA' },
		{ code: 'H69', text: 'Kontaktårsak IKA' },
		{ code: 'H70', text: 'Ytre øre betennelse' },
		{ code: 'H71', text: 'Mellomørebetennelse akutt' },
		{ code: 'H72', text: 'Mellomørebetennelse serøs' },
		{ code: 'H73', text: 'Tuba auditiva betennelse' },
		{ code: 'H74', text: 'Mellomørebetennelse kronisk' },
		{ code: 'H75', text: 'Svulst øre' },
		{ code: 'H76', text: 'Fremmedlegeme øre' },
		{ code: 'H77', text: 'Perforert trommehinne IKA' },
		{ code: 'H78', text: 'Overflateskade ytre øre' },
		{ code: 'H79', text: 'Skade øre IKA' },
		{ code: 'H80', text: 'Medfødt feil øre' },
		{ code: 'H81', text: 'Ørevoks' },
		{ code: 'H82', text: 'Svimmelhetssyndrom' },
		{ code: 'H83', text: 'Otosklerose' },
		{ code: 'H84', text: 'Hørselstap aldersbetinget' },
		{ code: 'H85', text: 'Hørselstap støyskade' },
		{ code: 'H86', text: 'Døvhet/hørselstap IKA' },
		{ code: 'H99', text: 'Øresykdom IKA' },
		{ code: 'K01', text: 'Smerte relatert til hjertet' },
		{ code: 'K02', text: 'Trykk/sammensnøring hjertet' },
		{ code: 'K03', text: 'Smerte relatert til kretsløpet IKA' },
		{ code: 'K04', text: 'Hjertebank' },
		{ code: 'K05', text: 'Uregelmessige hjerteslag IKA' },
		{ code: 'K06', text: 'Utvidede vener' },
		{ code: 'K07', text: 'Hovne ankler/ødem' },
		{ code: 'K22', text: 'Økt risiko for hjerte-karsykdom' },
		{ code: 'K24', text: 'Engstelig for hjertesykdom' },
		{ code: 'K25', text: 'Engstelig for høyt blodtrykk' },
		{ code: 'K27', text: 'Engstelig for hjerte-karsykdom IKA' },
		{ code: 'K28', text: 'Redus funksjonsevne hjerte-karprobl' },
		{ code: 'K29', text: 'Hjerte-karsyst symptomer/plager IKA' },
		{ code: 'K30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'K31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'K32', text: 'Sensitivitetsprøve' },
		{ code: 'K33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'K34', text: 'Blodprøve IKA' },
		{ code: 'K35', text: 'Urinprøve IKA' },
		{ code: 'K36', text: 'Avføringsprøve IKA' },
		{ code: 'K37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'K38', text: 'Laboratorieprøve IKA' },
		{ code: 'K39', text: 'Fysisk funksjonsprøve' },
		{ code: 'K40', text: 'Endoskopi' },
		{ code: 'K41', text: 'Billeddiagnostikk' },
		{ code: 'K42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'K43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'K44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'K45', text: 'Helseopplysning/rådgivning' },
		{ code: 'K46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'K47', text: 'Kontakt med spesialist' },
		{ code: 'K48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'K49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'K50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'K51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'K52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'K53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'K54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'K55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'K56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'K57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'K58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'K59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'K60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'K61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'K62', text: 'Administrativ prosedyre' },
		{ code: 'K63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'K64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'K65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'K66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'K67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'K68', text: 'Henvisning IKA' },
		{ code: 'K69', text: 'Kontaktårsak IKA' },
		{ code: 'K70', text: 'Infeksjon hjerte-karsystemet' },
		{ code: 'K71', text: 'Reumatisk feber/hjertesykdom' },
		{ code: 'K72', text: 'Svulst i hjerte' },
		{ code: 'K73', text: 'Medfødt feil hjerte-karsystemet' },
		{ code: 'K74', text: 'Iskemisk hjertesykdom med angina' },
		{ code: 'K75', text: 'Akutt hjerteinfarkt' },
		{ code: 'K76', text: 'Iskemisk hjertesykdom kronisk IKA' },
		{ code: 'K77', text: 'Hjertesvikt' },
		{ code: 'K78', text: 'Atrieflimmer/flutter' },
		{ code: 'K79', text: 'Paroksysmal takykardi' },
		{ code: 'K80', text: 'Hjertearytmi IKA' },
		{ code: 'K81', text: 'Bilyd hjerte/arterier IKA' },
		{ code: 'K82', text: 'Pulmonal hjertesykdom' },
		{ code: 'K83', text: 'Hjerteklaffesykdom IKA' },
		{ code: 'K84', text: 'Hjertesykdom IKA' },
		{ code: 'K85', text: 'Forhøyet blodtrykk IKA' },
		{ code: 'K86', text: 'Hypertensjon ukomplisert' },
		{ code: 'K87', text: 'Hypertensjon med komplikasjoner' },
		{ code: 'K88', text: 'Postural hypotensjon' },
		{ code: 'K89', text: 'Forbigående cerebral iskemi' },
		{ code: 'K90', text: 'Hjerneslag' },
		{ code: 'K91', text: 'Cerebrovaskulær sykdom' },
		{ code: 'K92', text: 'Aterosklerose/perifer karsykdom' },
		{ code: 'K93', text: 'Lungeemboli' },
		{ code: 'K94', text: 'Årebetennelse' },
		{ code: 'K95', text: 'Åreknuter underekstremitet' },
		{ code: 'K96', text: 'Hemoroider' },
		{ code: 'K99', text: 'Hjerte-karsykdom IKA' },
		{ code: 'L01', text: 'Nakke symptomer/plager' },
		{ code: 'L02', text: 'Rygg symptomer/plager' },
		{ code: 'L03', text: 'Korsrygg symptomer/plager' },
		{ code: 'L04', text: 'Brystkasse symptomer/plager' },
		{ code: 'L05', text: 'Flanke/armhule symptomer/plager' },
		{ code: 'L07', text: 'Kjeve symptomer/plager' },
		{ code: 'L08', text: 'Skulder symptomer/plager' },
		{ code: 'L09', text: 'Arm symptomer/plager' },
		{ code: 'L10', text: 'Albue symptomer/plager' },
		{ code: 'L11', text: 'Håndledd symptomer/plager' },
		{ code: 'L12', text: 'Hånd/finger symptomer/plager' },
		{ code: 'L13', text: 'Hofte symptomer/plager' },
		{ code: 'L14', text: 'Legg/lår symptomer/plager' },
		{ code: 'L15', text: 'Kne symptomer/plager' },
		{ code: 'L16', text: 'Ankel symptomer/plager' },
		{ code: 'L17', text: 'Fot/tå symptomer/plager' },
		{ code: 'L18', text: 'Utbredte muskelsmerter/fibromyalgi' },
		{ code: 'L19', text: 'Muskel symptomer/plager IKA' },
		{ code: 'L20', text: 'Ledd symptomer/plager IKA' },
		{ code: 'L26', text: 'Engstelig for kreft muskel-skj-syst' },
		{ code: 'L27', text: 'Engstelig for sykd musk-skj-syst IKA' },
		{ code: 'L28', text: 'Redus funksjonsevne musk-skj-probl' },
		{ code: 'L29', text: 'Muskel-skj-syst sympt/plager IKA' },
		{ code: 'L30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'L31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'L32', text: 'Sensitivitetsprøve' },
		{ code: 'L33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'L34', text: 'Blodprøve IKA' },
		{ code: 'L35', text: 'Urinprøve IKA' },
		{ code: 'L36', text: 'Avføringsprøve IKA' },
		{ code: 'L37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'L38', text: 'Laboratorieprøve IKA' },
		{ code: 'L39', text: 'Fysisk funksjonsprøve' },
		{ code: 'L40', text: 'Endoskopi' },
		{ code: 'L41', text: 'Billeddiagnostikk' },
		{ code: 'L42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'L43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'L44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'L45', text: 'Helseopplysning/rådgivning' },
		{ code: 'L46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'L47', text: 'Kontakt med spesialist' },
		{ code: 'L48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'L49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'L50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'L51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'L52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'L53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'L54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'L55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'L56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'L57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'L58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'L59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'L60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'L61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'L62', text: 'Administrativ prosedyre' },
		{ code: 'L63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'L64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'L65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'L66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'L67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'L68', text: 'Henvisning IKA' },
		{ code: 'L69', text: 'Kontaktårsak IKA' },
		{ code: 'L70', text: 'Infeksjon muskel-skjelettsystemet' },
		{ code: 'L71', text: 'Ondartet svulst muskel-skj-syst' },
		{ code: 'L72', text: 'Brudd underarm' },
		{ code: 'L73', text: 'Brudd legg/ankel' },
		{ code: 'L74', text: 'Brudd hånd/fot' },
		{ code: 'L75', text: 'Brudd lårben/lårhals' },
		{ code: 'L76', text: 'Brudd IKA' },
		{ code: 'L77', text: 'Forstuving/forstrekking ankel' },
		{ code: 'L78', text: 'Forstuving/forstrekking kne' },
		{ code: 'L79', text: 'Forstuving/forstrekking ledd IKA' },
		{ code: 'L80', text: 'Dislokasjon/subluksasjon' },
		{ code: 'L81', text: 'Skade muskel-skj-syst IKA' },
		{ code: 'L82', text: 'Medfødt feil muskel-skj-syst' },
		{ code: 'L83', text: 'Nakkesyndrom' },
		{ code: 'L84', text: 'Ryggsyndrom uten smerteutstråling' },
		{ code: 'L85', text: 'Ervervet deformitet ryggsøyle' },
		{ code: 'L86', text: 'Ryggsyndrom med smerteutstråling' },
		{ code: 'L87', text: 'Bursitt/tendinitt/synovitt IKA' },
		{ code: 'L88', text: 'Reumatoid artritt/reumatisk sykdom' },
		{ code: 'L89', text: 'Hofteleddsartrose' },
		{ code: 'L90', text: 'Kneleddsartrose' },
		{ code: 'L91', text: 'Artrose IKA' },
		{ code: 'L92', text: 'Skuldersyndrom' },
		{ code: 'L93', text: 'Tennisalbue/lateral epikondylitt' },
		{ code: 'L94', text: 'Osteokondrose' },
		{ code: 'L95', text: 'Osteoporose' },
		{ code: 'L96', text: 'Akutt indre kneskade' },
		{ code: 'L97', text: 'Godartet/uspes svulst musk-skj-syst' },
		{ code: 'L98', text: 'Ervervet deformitet ekstremitet' },
		{ code: 'L99', text: 'Muskel-skjelettsykdom IKA' },
		{ code: 'N01', text: 'Hodepine' },
		{ code: 'N03', text: 'Ansiktssmerte' },
		{ code: 'N04', text: 'Restless legs' },
		{ code: 'N05', text: 'Prikking/parestesi i hender/føtter' },
		{ code: 'N06', text: 'Forstyrrelser i hudens følsomhet IKA' },
		{ code: 'N07', text: 'Krampeanfall/kramper' },
		{ code: 'N08', text: 'Unormale/ufrivillige bevegelser' },
		{ code: 'N16', text: 'Forstyrrelse i lukt/smak' },
		{ code: 'N17', text: 'Svimmelhet IKA' },
		{ code: 'N18', text: 'Lammelse/svakhet' },
		{ code: 'N19', text: 'Talevansker' },
		{ code: 'N26', text: 'Engstelig for kreft nervesystemet' },
		{ code: 'N27', text: 'Engstelig for sykdom nervesyst IKA' },
		{ code: 'N28', text: 'Redus funksjonsevne probl nervesyst' },
		{ code: 'N29', text: 'Nervesystem symptomer/plager IKA' },
		{ code: 'N30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'N31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'N32', text: 'Sensitivitetsprøve' },
		{ code: 'N33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'N34', text: 'Blodprøve IKA' },
		{ code: 'N35', text: 'Urinprøve IKA' },
		{ code: 'N36', text: 'Avføringsprøve IKA' },
		{ code: 'N37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'N38', text: 'Laboratorieprøve IKA' },
		{ code: 'N39', text: 'Fysisk funksjonsprøve' },
		{ code: 'N40', text: 'Endoskopi' },
		{ code: 'N41', text: 'Billeddiagnostikk' },
		{ code: 'N42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'N43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'N44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'N45', text: 'Helseopplysning/rådgivning' },
		{ code: 'N46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'N47', text: 'Kontakt med spesialist' },
		{ code: 'N48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'N49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'N50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'N51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'N52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'N53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'N54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'N55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'N56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'N57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'N58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'N59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'N60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'N61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'N62', text: 'Administrativ prosedyre' },
		{ code: 'N63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'N64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'N65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'N66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'N67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'N68', text: 'Henvisning IKA' },
		{ code: 'N69', text: 'Kontaktårsak IKA' },
		{ code: 'N70', text: 'Poliomyelitt' },
		{ code: 'N71', text: 'Meningitt/encefalitt' },
		{ code: 'N72', text: 'Stivkrampe' },
		{ code: 'N73', text: 'Infeksjon sentralnervesyst IKA' },
		{ code: 'N74', text: 'Ondartet svulst nervesystemet' },
		{ code: 'N75', text: 'Godartet svulst nervesystemet' },
		{ code: 'N76', text: 'Uspesifisert svulst nervesystemet' },
		{ code: 'N79', text: 'Hjernerystelse' },
		{ code: 'N80', text: 'Hodeskade IKA' },
		{ code: 'N81', text: 'Skade nervesystemet IKA' },
		{ code: 'N85', text: 'Medfødt feil nervesystemet' },
		{ code: 'N86', text: 'Multippel sklerose' },
		{ code: 'N87', text: 'Parkinsonisme' },
		{ code: 'N88', text: 'Epilepsi' },
		{ code: 'N89', text: 'Migrene' },
		{ code: 'N90', text: 'Cluster-hodepine' },
		{ code: 'N91', text: 'Facialisparese' },
		{ code: 'N92', text: 'Trigeminusnevralgi' },
		{ code: 'N93', text: 'Carpal tunnel syndrom' },
		{ code: 'N94', text: 'Perifer nevropati' },
		{ code: 'N95', text: 'Tensjonshodepine' },
		{ code: 'N99', text: 'Sykdom i nervesystemet IKA' },
		{ code: 'P01', text: 'Følelse angst/nervøs/anspent' },
		{ code: 'P02', text: 'Psykisk ubalanse situasjonsbetinget' },
		{ code: 'P03', text: 'Depresjonsfølelse' },
		{ code: 'P04', text: 'Irritabel atferd/følelse' },
		{ code: 'P05', text: 'Senilitet, atferd/følelse gammel' },
		{ code: 'P06', text: 'Søvnforstyrrelse' },
		{ code: 'P07', text: 'Seksuell drift/lyst hemmet' },
		{ code: 'P08', text: 'Seksuell tilfredsstillelse hemmet' },
		{ code: 'P09', text: 'Seksuell legning bekymret for' },
		{ code: 'P10', text: 'Stamming/tics' },
		{ code: 'P11', text: 'Spiseforstyrrelse hos barn' },
		{ code: 'P12', text: 'Sengevæting/enuresis IKA' },
		{ code: 'P13', text: 'Enkoprese' },
		{ code: 'P15', text: 'Kronisk alkoholmisbruk' },
		{ code: 'P16', text: 'Akutt alkoholmisbruk' },
		{ code: 'P17', text: 'Tobakkmisbruk' },
		{ code: 'P18', text: 'Legemiddelmisbruk' },
		{ code: 'P19', text: 'Stoffmisbruk' },
		{ code: 'P20', text: 'Hukommelsesforstyrrelse' },
		{ code: 'P22', text: 'Atferdsforstyrrelse barn' },
		{ code: 'P23', text: 'Atferdsforstyrrelse ungdom' },
		{ code: 'P24', text: 'Spesifikke utviklingsforstyrrelser' },
		{ code: 'P25', text: 'Livsfaseproblem voksen' },
		{ code: 'P27', text: 'Engstelig for psykisk sykdom' },
		{ code: 'P28', text: 'Redusert funksjonsevne psyk problem' },
		{ code: 'P29', text: 'Psykiske symptomer/plager IKA' },
		{ code: 'P30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'P31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'P32', text: 'Sensitivitetsprøve' },
		{ code: 'P33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'P34', text: 'Blodprøve IKA' },
		{ code: 'P35', text: 'Urinprøve IKA' },
		{ code: 'P36', text: 'Avføringsprøve IKA' },
		{ code: 'P37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'P38', text: 'Laboratorieprøve IKA' },
		{ code: 'P39', text: 'Fysisk funksjonsprøve' },
		{ code: 'P40', text: 'Endoskopi' },
		{ code: 'P41', text: 'Billeddiagnostikk' },
		{ code: 'P42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'P43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'P44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'P45', text: 'Helseopplysning/rådgivning' },
		{ code: 'P46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'P47', text: 'Kontakt med spesialist' },
		{ code: 'P48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'P49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'P50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'P51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'P52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'P53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'P54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'P55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'P56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'P57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'P58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'P59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'P60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'P61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'P62', text: 'Administrativ prosedyre' },
		{ code: 'P63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'P64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'P65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'P66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'P67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'P68', text: 'Henvisning IKA' },
		{ code: 'P69', text: 'Kontaktårsak IKA' },
		{ code: 'P70', text: 'Demens' },
		{ code: 'P71', text: 'Organisk psykisk lidelse IKA' },
		{ code: 'P72', text: 'Schizofreni' },
		{ code: 'P73', text: 'Affektiv lidelse' },
		{ code: 'P74', text: 'Angstlidelse' },
		{ code: 'P75', text: 'Dissosiativ/somatoform lidelse' },
		{ code: 'P76', text: 'Depressiv lidelse' },
		{ code: 'P77', text: 'Selvmord/selvmordsforsøk' },
		{ code: 'P78', text: 'Nevrasteni' },
		{ code: 'P79', text: 'Fobi/obsessiv-kompulsiv lidelse' },
		{ code: 'P80', text: 'Personlighetsforstyrrelse' },
		{ code: 'P81', text: 'Hyperkinetisk forstyrrelse' },
		{ code: 'P82', text: 'Posttraumatisk stresslidelse' },
		{ code: 'P85', text: 'Psykisk utviklingshemning' },
		{ code: 'P86', text: 'Anorexia nervosa/bulimi' },
		{ code: 'P98', text: 'Psykose IKA' },
		{ code: 'P99', text: 'Psykisk lidelse IKA' },
		{ code: 'R01', text: 'Smerte luftveier' },
		{ code: 'R02', text: 'Kortpustethet/dyspné' },
		{ code: 'R03', text: 'Piping i brystet' },
		{ code: 'R04', text: 'Pusteproblem IKA' },
		{ code: 'R05', text: 'Hoste' },
		{ code: 'R06', text: 'Neseblødning' },
		{ code: 'R07', text: 'Nysing/tetthet i nese' },
		{ code: 'R08', text: 'Nese symptomer/plager IKA' },
		{ code: 'R09', text: 'Bihule symptomer/plager IKA' },
		{ code: 'R21', text: 'Hals symptomer/plager' },
		{ code: 'R23', text: 'Stemme symptomer/plager' },
		{ code: 'R24', text: 'Blodig oppspytt/hemoptyse' },
		{ code: 'R25', text: 'Unormalt oppspytt/ekspektorat' },
		{ code: 'R26', text: 'Engstelig for kreft luftveier' },
		{ code: 'R27', text: 'Engstelig for sykdom luftveier IKA' },
		{ code: 'R28', text: 'Redusert funksjonsevne luftveisprobl' },
		{ code: 'R29', text: 'Luftveier symptomer/plager IKA' },
		{ code: 'R30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'R31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'R32', text: 'Sensitivitetsprøve' },
		{ code: 'R33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'R34', text: 'Blodprøve IKA' },
		{ code: 'R35', text: 'Urinprøve IKA' },
		{ code: 'R36', text: 'Avføringsprøve IKA' },
		{ code: 'R37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'R38', text: 'Laboratorieprøve IKA' },
		{ code: 'R39', text: 'Fysisk funksjonsprøve' },
		{ code: 'R40', text: 'Endoskopi' },
		{ code: 'R41', text: 'Billeddiagnostikk' },
		{ code: 'R42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'R43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'R44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'R45', text: 'Helseopplysning/rådgivning' },
		{ code: 'R46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'R47', text: 'Kontakt med spesialist' },
		{ code: 'R48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'R49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'R50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'R51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'R52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'R53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'R54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'R55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'R56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'R57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'R58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'R59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'R60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'R61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'R62', text: 'Administrativ prosedyre' },
		{ code: 'R63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'R64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'R65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'R66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'R67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'R68', text: 'Henvisning IKA' },
		{ code: 'R69', text: 'Kontaktårsak IKA' },
		{ code: 'R71', text: 'Kikhoste' },
		{ code: 'R72', text: 'Streptokokkhals' },
		{ code: 'R73', text: 'Nesebyll' },
		{ code: 'R74', text: 'Akutt øvre luftveisinfeksjon' },
		{ code: 'R75', text: 'Bihulebetennelse' },
		{ code: 'R76', text: 'Akutt tonsillitt' },
		{ code: 'R77', text: 'Akutt laryngitt/trakeitt' },
		{ code: 'R78', text: 'Akutt bronkitt/bronkiolitt' },
		{ code: 'R79', text: 'Kronisk bronkitt' },
		{ code: 'R80', text: 'Influensa' },
		{ code: 'R81', text: 'Lungebetennelse' },
		{ code: 'R82', text: 'Pleuritt IKA' },
		{ code: 'R83', text: 'Luftveisinfeksjon IKA' },
		{ code: 'R84', text: 'Ondartet svulst bronkie/lunge' },
		{ code: 'R85', text: 'Ondartet svulst luftveier IKA' },
		{ code: 'R86', text: 'Godartet svulst luftveier' },
		{ code: 'R87', text: 'Fremmedlegeme i nese/larynks/bronkie' },
		{ code: 'R88', text: 'Skade luftveier IKA' },
		{ code: 'R89', text: 'Medfødt feil luftveier' },
		{ code: 'R90', text: 'Hypertrofi tonsiller/adenoid vev' },
		{ code: 'R92', text: 'Uspesifisert svulst luftveier' },
		{ code: 'R95', text: 'Kronisk obstruktiv lungesykdom' },
		{ code: 'R96', text: 'Astma' },
		{ code: 'R97', text: 'Allergisk rinitt' },
		{ code: 'R98', text: 'Hyperventileringssyndrom' },
		{ code: 'R99', text: 'Luftveissykdom IKA' },
		{ code: 'R991', text: 'Covid-19 (mistenkt/sannsynlig)' },
		{ code: 'R992', text: 'Covid-19 (bekreftet)' },
		{ code: 'R993', text: 'Utbruddssykdom definert av FHI, luftveier' },
		{ code: 'R994', text: 'Utbruddssykdom definert av FHI, luftveier' },
		{ code: 'R995', text: 'Utbruddssykdom definert av FHI, luftveier' },
		{ code: 'R996', text: 'Utbruddssykdom definert av FHI, luftveier' },
		{ code: 'R997', text: 'Utbruddssykdom definert av FHI, luftveier' },
		{ code: 'R998', text: 'Utbruddssykdom definert av FHI, luftveier' },
		{ code: 'R999', text: 'Utbruddssykdom definert av FHI, luftveier' },
		{ code: 'S01', text: 'Smerte/ømhet hud' },
		{ code: 'S02', text: 'Hudkløe' },
		{ code: 'S03', text: 'Vorter' },
		{ code: 'S04', text: 'Lokalisert hevelse/kul hud' },
		{ code: 'S05', text: 'Utbredte hevelser/kuler hud' },
		{ code: 'S06', text: 'Lokalisert utslett hud' },
		{ code: 'S07', text: 'Utbredt utslett hud' },
		{ code: 'S08', text: 'Forandring av hudfarge IKA' },
		{ code: 'S09', text: 'Infeksjon finger/tå' },
		{ code: 'S10', text: 'Abscess/furunkel' },
		{ code: 'S11', text: 'Hudinfeksjon posttraumatisk' },
		{ code: 'S12', text: 'Insektstikk/bitt' },
		{ code: 'S13', text: 'Bitt av dyr/menneske' },
		{ code: 'S14', text: 'Forbrenning/skålding' },
		{ code: 'S15', text: 'Fremmedlegeme hud' },
		{ code: 'S16', text: 'Kontusjon/slag hud' },
		{ code: 'S17', text: 'Skrubbsår/blemmer' },
		{ code: 'S18', text: 'Åpent sår/kutt' },
		{ code: 'S19', text: 'Skade hud/underhud IKA' },
		{ code: 'S20', text: 'Liktorn/fortykket underhud' },
		{ code: 'S21', text: 'Hudstruktur symptomer/plager' },
		{ code: 'S22', text: 'Negl symptomer/plager' },
		{ code: 'S23', text: 'Håravfall/skallethet' },
		{ code: 'S24', text: 'Hår/hodebunn symptomer/plager IKA' },
		{ code: 'S26', text: 'Engstelig for kreft hud' },
		{ code: 'S27', text: 'Engstelig for hudsykdom IKA' },
		{ code: 'S28', text: 'Redusert funksjonsevne pga hudprobl' },
		{ code: 'S29', text: 'Hud symptomer/plager IKA' },
		{ code: 'S30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'S31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'S32', text: 'Sensitivitetsprøve' },
		{ code: 'S33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'S34', text: 'Blodprøve IKA' },
		{ code: 'S35', text: 'Urinprøve IKA' },
		{ code: 'S36', text: 'Avføringsprøve IKA' },
		{ code: 'S37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'S38', text: 'Laboratorieprøve IKA' },
		{ code: 'S39', text: 'Fysisk funksjonsprøve' },
		{ code: 'S40', text: 'Endoskopi' },
		{ code: 'S41', text: 'Billeddiagnostikk' },
		{ code: 'S42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'S43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'S44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'S45', text: 'Helseopplysning/rådgivning' },
		{ code: 'S46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'S47', text: 'Kontakt med spesialist' },
		{ code: 'S48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'S49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'S50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'S51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'S52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'S53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'S54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'S55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'S56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'S57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'S58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'S59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'S60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'S61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'S62', text: 'Administrativ prosedyre' },
		{ code: 'S63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'S64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'S65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'S66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'S67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'S68', text: 'Henvisning IKA' },
		{ code: 'S69', text: 'Kontaktårsak IKA' },
		{ code: 'S70', text: 'Herpes zoster' },
		{ code: 'S71', text: 'Herpes simplex IKA' },
		{ code: 'S72', text: 'Infestasjon midd' },
		{ code: 'S73', text: 'Infestasjon parasitt IKA' },
		{ code: 'S74', text: 'Ringorm/hudsopp IKA' },
		{ code: 'S75', text: 'Candidainfeksjon hud' },
		{ code: 'S76', text: 'Hudinfeksjon IKA' },
		{ code: 'S77', text: 'Ondartet svulst hud' },
		{ code: 'S78', text: 'Lipom' },
		{ code: 'S79', text: 'Godartet/uspesifisert svulst hud IKA' },
		{ code: 'S80', text: 'Solutløst keratose/solforbrenning' },
		{ code: 'S81', text: 'Hemangiom/lymfangiom' },
		{ code: 'S82', text: 'Pigmentnevus' },
		{ code: 'S83', text: 'Medfødt feil hud/underhud IKA' },
		{ code: 'S84', text: 'Brennkopper' },
		{ code: 'S85', text: 'Pilonidalcyste/-fistel' },
		{ code: 'S86', text: 'Seboréisk dermatitt' },
		{ code: 'S87', text: 'Atopisk dermatitt/eksem' },
		{ code: 'S88', text: 'Kontakt-/allergisk dermatitt IKA' },
		{ code: 'S89', text: 'Bleiedermatitt' },
		{ code: 'S90', text: 'Pityriasis rosea' },
		{ code: 'S91', text: 'Psoriasis' },
		{ code: 'S92', text: 'Svettekjertelsykdom' },
		{ code: 'S93', text: 'Talgcyste' },
		{ code: 'S94', text: 'Inngrodd negl' },
		{ code: 'S95', text: 'Molluscum contagiosum' },
		{ code: 'S96', text: 'Akne' },
		{ code: 'S97', text: 'Kronisk hudsår' },
		{ code: 'S98', text: 'Urticaria' },
		{ code: 'S99', text: 'Hud/underhud sykdom IKA' },
		{ code: 'T01', text: 'Økt tørste' },
		{ code: 'T02', text: 'Økt matlyst' },
		{ code: 'T03', text: 'Nedsatt matlyst' },
		{ code: 'T04', text: 'Ernæringsproblem barn' },
		{ code: 'T05', text: 'Ernæringsproblem voksen' },
		{ code: 'T07', text: 'Vektøkning' },
		{ code: 'T08', text: 'Vekttap' },
		{ code: 'T10', text: 'Forsinket vekst' },
		{ code: 'T11', text: 'Uttørring' },
		{ code: 'T26', text: 'Engstelig for kreft endokrine system' },
		{ code: 'T27', text: 'Engstelig endokr/metabol/ernær sykd' },
		{ code: 'T28', text: 'Red funk evne endo/metab/ernær probl' },
		{ code: 'T29', text: 'Endok/metab/ernær sympt/plager IKA' },
		{ code: 'T30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'T31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'T32', text: 'Sensitivitetsprøve' },
		{ code: 'T33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'T34', text: 'Blodprøve IKA' },
		{ code: 'T35', text: 'Urinprøve IKA' },
		{ code: 'T36', text: 'Avføringsprøve IKA' },
		{ code: 'T37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'T38', text: 'Laboratorieprøve IKA' },
		{ code: 'T39', text: 'Fysisk funksjonsprøve' },
		{ code: 'T40', text: 'Endoskopi' },
		{ code: 'T41', text: 'Billeddiagnostikk' },
		{ code: 'T42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'T43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'T44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'T45', text: 'Helseopplysning/rådgivning' },
		{ code: 'T46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'T47', text: 'Kontakt med spesialist' },
		{ code: 'T48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'T49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'T50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'T51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'T52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'T53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'T54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'T55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'T56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'T57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'T58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'T59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'T60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'T61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'T62', text: 'Administrativ prosedyre' },
		{ code: 'T63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'T64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'T65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'T66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'T67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'T68', text: 'Henvisning IKA' },
		{ code: 'T69', text: 'Kontaktårsak IKA' },
		{ code: 'T70', text: 'Infeksjon endokrine system' },
		{ code: 'T71', text: 'Ondartet svulst tyreoidea' },
		{ code: 'T72', text: 'Godartet svulst tyreoidea' },
		{ code: 'T73', text: 'Svulst endokrine organ IKA' },
		{ code: 'T78', text: 'Ductus/cystis tyreoglossus' },
		{ code: 'T80', text: 'Medfødt feil endokr/metabol syst IKA' },
		{ code: 'T81', text: 'Struma' },
		{ code: 'T82', text: 'Fedme' },
		{ code: 'T83', text: 'Overvekt' },
		{ code: 'T85', text: 'Hypertyreose/tyreotoksikose' },
		{ code: 'T86', text: 'Hypotyreose/myksødem' },
		{ code: 'T87', text: 'Hypoglykemi' },
		{ code: 'T89', text: 'Diabetes type 1' },
		{ code: 'T90', text: 'Diabetes type 2' },
		{ code: 'T91', text: 'Vitaminmangel/ernæringsforstyrrelse' },
		{ code: 'T92', text: 'Urinsyregikt' },
		{ code: 'T93', text: 'Lipidstoffskifte forstyrrelse' },
		{ code: 'T99', text: 'Endokrin/metabol/ernær sykd IKA' },
		{ code: 'U01', text: 'Smerte vannlating' },
		{ code: 'U02', text: 'Hyppig vannlating' },
		{ code: 'U04', text: 'Urininkontinens' },
		{ code: 'U05', text: 'Vannlatingsproblemer IKA' },
		{ code: 'U06', text: 'Hematuri' },
		{ code: 'U07', text: 'Urin symptomer/plager IKA' },
		{ code: 'U08', text: 'Urinretensjon' },
		{ code: 'U13', text: 'Blære symptomer/plager IKA' },
		{ code: 'U14', text: 'Nyre symptomer/plager' },
		{ code: 'U26', text: 'Engstelig for kreft urinveier' },
		{ code: 'U27', text: 'Engstelig for sykdom urinveier IKA' },
		{ code: 'U28', text: 'Redusert funksjonsevne urinveisprobl' },
		{ code: 'U29', text: 'Urinveier symptomer/plager IKA' },
		{ code: 'U30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'U31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'U32', text: 'Sensitivitetsprøve' },
		{ code: 'U33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'U34', text: 'Blodprøve IKA' },
		{ code: 'U35', text: 'Urinprøve IKA' },
		{ code: 'U36', text: 'Avføringsprøve IKA' },
		{ code: 'U37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'U38', text: 'Laboratorieprøve IKA' },
		{ code: 'U39', text: 'Fysisk funksjonsprøve' },
		{ code: 'U40', text: 'Endoskopi' },
		{ code: 'U41', text: 'Billeddiagnostikk' },
		{ code: 'U42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'U43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'U44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'U45', text: 'Helseopplysning/rådgivning' },
		{ code: 'U46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'U47', text: 'Kontakt med spesialist' },
		{ code: 'U48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'U49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'U50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'U51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'U52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'U53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'U54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'U55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'U56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'U57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'U58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'U59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'U60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'U61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'U62', text: 'Administrativ prosedyre' },
		{ code: 'U63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'U64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'U65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'U66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'U67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'U68', text: 'Henvisning IKA' },
		{ code: 'U69', text: 'Kontaktårsak IKA' },
		{ code: 'U70', text: 'Nyrebekkenbetennelse' },
		{ code: 'U71', text: 'Cystitt/urinveisinfeksjon IKA' },
		{ code: 'U72', text: 'Uretritt' },
		{ code: 'U75', text: 'Ondartet svulst nyre' },
		{ code: 'U76', text: 'Ondartet svulst urinblære' },
		{ code: 'U77', text: 'Ondartet svulst urinveier IKA' },
		{ code: 'U78', text: 'Godartet svulst urinveier' },
		{ code: 'U79', text: 'Uspesifisert svulst urinveier' },
		{ code: 'U80', text: 'Skade urinveier' },
		{ code: 'U85', text: 'Medfødt feil urinveier' },
		{ code: 'U88', text: 'Glomerulonefritt/nefropati' },
		{ code: 'U90', text: 'Ortostatisk proteinuri' },
		{ code: 'U95', text: 'Sten i urinveier' },
		{ code: 'U98', text: 'Unormal urinprøve IKA' },
		{ code: 'U99', text: 'Urinveissykdom IKA' },
		{ code: 'W01', text: 'Spørsmål om svangerskap' },
		{ code: 'W02', text: 'Engstelig for svangerskap' },
		{ code: 'W03', text: 'Blødning svangerskap' },
		{ code: 'W05', text: 'Kvalme/brekninger svangerskap' },
		{ code: 'W10', text: 'Prevensjon postkoital antikonsepsjon' },
		{ code: 'W11', text: 'Prevensjon p-pille' },
		{ code: 'W12', text: 'Prevensjon spiral' },
		{ code: 'W13', text: 'Sterilisering (K)' },
		{ code: 'W14', text: 'Prevensjon IKA (K)' },
		{ code: 'W15', text: 'Infertilitet (K)' },
		{ code: 'W17', text: 'Blødning etter fødsel' },
		{ code: 'W18', text: 'Postpartum symptomer/plager IKA' },
		{ code: 'W19', text: 'Amming symptomer/plager' },
		{ code: 'W21', text: 'Bekymret/opptatt av utseende sv skap' },
		{ code: 'W27', text: 'Engstelig for komplik sv skap/fødsel' },
		{ code: 'W28', text: 'Red funksjonsevne svangerskapsprobl' },
		{ code: 'W29', text: 'Sv skap/fødsel sympt/plager IKA' },
		{ code: 'W30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'W31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'W32', text: 'Sensitivitetsprøve' },
		{ code: 'W33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'W34', text: 'Blodprøve IKA' },
		{ code: 'W35', text: 'Urinprøve IKA' },
		{ code: 'W36', text: 'Avføringsprøve IKA' },
		{ code: 'W37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'W38', text: 'Laboratorieprøve IKA' },
		{ code: 'W39', text: 'Fysisk funksjonsprøve' },
		{ code: 'W40', text: 'Endoskopi' },
		{ code: 'W41', text: 'Billeddiagnostikk' },
		{ code: 'W42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'W43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'W44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'W45', text: 'Helseopplysning/rådgivning' },
		{ code: 'W46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'W47', text: 'Kontakt med spesialist' },
		{ code: 'W48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'W49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'W50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'W51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'W52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'W53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'W54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'W55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'W56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'W57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'W58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'W59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'W60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'W61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'W62', text: 'Administrativ prosedyre' },
		{ code: 'W63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'W64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'W65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'W66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'W67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'W68', text: 'Henvisning IKA' },
		{ code: 'W69', text: 'Kontaktårsak IKA' },
		{ code: 'W70', text: 'Infeksjon/sepsis barseltid' },
		{ code: 'W71', text: 'Infeksjon som kompliser sv skap IKA' },
		{ code: 'W72', text: 'Ondartet svulst svangerskap' },
		{ code: 'W73', text: 'Godartet/uspes svulst sv skap' },
		{ code: 'W75', text: 'Skade som kompliserer svangerskap' },
		{ code: 'W76', text: 'Medfødt feil som kompliserer sv skap' },
		{ code: 'W78', text: 'Svangerskap bekreftet' },
		{ code: 'W781', text: 'Svangerskapskontroll' },
		{ code: 'W79', text: 'Uønsket svangerskap' },
		{ code: 'W80', text: 'Ekstrauterint svangerskap' },
		{ code: 'W81', text: 'Svangerskapsforgiftning' },
		{ code: 'W82', text: 'Abort spontan' },
		{ code: 'W83', text: 'Abort fremkalt' },
		{ code: 'W84', text: 'Svangerskap høyrisiko' },
		{ code: 'W85', text: 'Svangerskapsdiabetes' },
		{ code: 'W90', text: 'Ukomplisert fødsel levendefødt barn' },
		{ code: 'W91', text: 'Ukomplisert fødsel dødfødt barn' },
		{ code: 'W92', text: 'Komplisert fødsel levendefødt barn' },
		{ code: 'W93', text: 'Komplisert fødsel dødfødt barn' },
		{ code: 'W94', text: 'Mastitt i barseltid' },
		{ code: 'W95', text: 'Brystsykdom i sv skap/barseltid IKA' },
		{ code: 'W96', text: 'Komplikasjoner i barseltid IKA' },
		{ code: 'W99', text: 'Svangersk/føds/barsel sykd IKA' },
		{ code: 'X01', text: 'Smerte kjønnsorgan (K)' },
		{ code: 'X02', text: 'Menstruasjonssmerter' },
		{ code: 'X03', text: 'Intermenstruelle smerter' },
		{ code: 'X04', text: 'Smerte samleie (K)' },
		{ code: 'X05', text: 'Menstruasjon sparsom/sjelden' },
		{ code: 'X06', text: 'Menstruasjon kraftig' },
		{ code: 'X07', text: 'Menstruasjon uregelmessig/hyppig' },
		{ code: 'X08', text: 'Intermenstruell blødning' },
		{ code: 'X09', text: 'Premenstruelle symptomer/plager' },
		{ code: 'X10', text: 'Forskyvning menstruasjon' },
		{ code: 'X11', text: 'Klimakterium symptomer/plager' },
		{ code: 'X12', text: 'Postmenopausal blødning' },
		{ code: 'X13', text: 'Blødning etter samleie' },
		{ code: 'X14', text: 'Utflod fra skjeden' },
		{ code: 'X15', text: 'Skjede symptomer/plager IKA' },
		{ code: 'X16', text: 'Vulva symptomer/plager' },
		{ code: 'X17', text: 'Underliv symptomer/plager (K)' },
		{ code: 'X18', text: 'Smerte bryst (K)' },
		{ code: 'X19', text: 'Kul i bryst IKA (K)' },
		{ code: 'X20', text: 'Brystvorte symptomer/plager (K)' },
		{ code: 'X21', text: 'Bryst symptomer/plager IKA (K)' },
		{ code: 'X22', text: 'Bekymret/oppt av utseende bryst (K)' },
		{ code: 'X23', text: 'Engstelig for kjønnssykdom (K)' },
		{ code: 'X24', text: 'Engstelig for seksuell dysfunk (K)' },
		{ code: 'X25', text: 'Engstelig for kreft kjønnsorgan (K)' },
		{ code: 'X26', text: 'Engstelig for brystkreft (K)' },
		{ code: 'X27', text: 'Engstelig sykd kj org/bryst IKA (K)' },
		{ code: 'X28', text: 'Red funksjonevne probl kjønnsorg (K)' },
		{ code: 'X29', text: 'Kjønnsorgan sympt/plager IKA (K)' },
		{ code: 'X30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'X31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'X32', text: 'Sensitivitetsprøve' },
		{ code: 'X33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'X34', text: 'Blodprøve IKA' },
		{ code: 'X35', text: 'Urinprøve IKA' },
		{ code: 'X36', text: 'Avføringsprøve IKA' },
		{ code: 'X37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'X38', text: 'Laboratorieprøve IKA' },
		{ code: 'X39', text: 'Fysisk funksjonsprøve' },
		{ code: 'X40', text: 'Endoskopi' },
		{ code: 'X41', text: 'Billeddiagnostikk' },
		{ code: 'X42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'X43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'X44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'X45', text: 'Helseopplysning/rådgivning' },
		{ code: 'X46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'X47', text: 'Kontakt med spesialist' },
		{ code: 'X48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'X49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'X50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'X51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'X52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'X53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'X54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'X55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'X56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'X57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'X58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'X59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'X60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'X61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'X62', text: 'Administrativ prosedyre' },
		{ code: 'X63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'X64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'X65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'X66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'X67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'X68', text: 'Henvisning IKA' },
		{ code: 'X69', text: 'Kontaktårsak IKA' },
		{ code: 'X70', text: 'Syfilis (K)' },
		{ code: 'X71', text: 'Gonokokkinfeksjon (K)' },
		{ code: 'X72', text: 'Candidainfeksjon urogenitalt (K)' },
		{ code: 'X73', text: 'Trikomonasinfeksjon urogenitalt (K)' },
		{ code: 'X74', text: 'Underlivsinfeksjon IKA (K)' },
		{ code: 'X75', text: 'Ondartet svulst livmorhals' },
		{ code: 'X76', text: 'Ondartet svulst bryst (K)' },
		{ code: 'X77', text: 'Ondartet svulst kjønnsorg IKA (K)' },
		{ code: 'X78', text: 'Godartet svulst livmor' },
		{ code: 'X79', text: 'Godartet svulst bryst (K)' },
		{ code: 'X80', text: 'Godartet svulst kjønnsorg IKA (K)' },
		{ code: 'X81', text: 'Uspes svulst kjønnsorg IKA (K)' },
		{ code: 'X82', text: 'Skade kjønnsorgan (K)' },
		{ code: 'X83', text: 'Medfødt feil kjønnsorgan (K)' },
		{ code: 'X84', text: 'Vaginitt/vulvitt IKA' },
		{ code: 'X85', text: 'Sykdom i livmorhals IKA' },
		{ code: 'X86', text: 'Cytologi livmorhals unormal' },
		{ code: 'X87', text: 'Fremfall kjønnsorgan (K)' },
		{ code: 'X88', text: 'Godartet mammadysplasi' },
		{ code: 'X89', text: 'Premenstruelt tensjonssyndrom' },
		{ code: 'X90', text: 'Genital herpesvirusinfeksjon (K)' },
		{ code: 'X91', text: 'Condylomata acuminata (K)' },
		{ code: 'X92', text: 'Klamydiainfeksjon urogenitalt (K)' },
		{ code: 'X99', text: 'Kjønnsorgan sykdom IKA (K)' },
		{ code: 'Y01', text: 'Smerte penis' },
		{ code: 'Y02', text: 'Smerte testikkel/skrotum' },
		{ code: 'Y03', text: 'Utflod urinrør/penis' },
		{ code: 'Y04', text: 'Penis symptomer/plager IKA' },
		{ code: 'Y05', text: 'Skrotum/testikkel sympt/plager IKA' },
		{ code: 'Y06', text: 'Prostata symptomer/plager' },
		{ code: 'Y07', text: 'Impotens organisk betinget' },
		{ code: 'Y08', text: 'Seksuelt problem IKA (M)' },
		{ code: 'Y10', text: 'Infertilitet (M)' },
		{ code: 'Y13', text: 'Sterilisering (M)' },
		{ code: 'Y14', text: 'Prevensjon IKA (M)' },
		{ code: 'Y16', text: 'Bryst symptomer/plager (M)' },
		{ code: 'Y24', text: 'Engstelig for seksuell dysfunk (M)' },
		{ code: 'Y25', text: 'Engstelig for kjønnsykdom (M)' },
		{ code: 'Y26', text: 'Engstelig for kreft kjønnsorgan (M)' },
		{ code: 'Y27', text: 'Engstelig for sykd kjønnsorg IKA (M)' },
		{ code: 'Y28', text: 'Red funksjonsevne prob kjønnsorg (M)' },
		{ code: 'Y29', text: 'Kjønnsorgan sympt/plager IKA (M)' },
		{ code: 'Y30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'Y31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'Y32', text: 'Sensitivitetsprøve' },
		{ code: 'Y33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'Y34', text: 'Blodprøve IKA' },
		{ code: 'Y35', text: 'Urinprøve IKA' },
		{ code: 'Y36', text: 'Avføringsprøve IKA' },
		{ code: 'Y37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'Y38', text: 'Laboratorieprøve IKA' },
		{ code: 'Y39', text: 'Fysisk funksjonsprøve' },
		{ code: 'Y40', text: 'Endoskopi' },
		{ code: 'Y41', text: 'Billeddiagnostikk' },
		{ code: 'Y42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'Y43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'Y44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'Y45', text: 'Helseopplysning/rådgivning' },
		{ code: 'Y46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'Y47', text: 'Kontakt med spesialist' },
		{ code: 'Y48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'Y49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'Y50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'Y51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'Y52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'Y53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'Y54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'Y55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'Y56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'Y57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'Y58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'Y59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'Y60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'Y61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'Y62', text: 'Administrativ prosedyre' },
		{ code: 'Y63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'Y64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'Y65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'Y66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'Y67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'Y68', text: 'Henvisning IKA' },
		{ code: 'Y69', text: 'Kontaktårsak IKA' },
		{ code: 'Y70', text: 'Syfilis (M)' },
		{ code: 'Y71', text: 'Gonokokkinfeksjon (M)' },
		{ code: 'Y72', text: 'Genital herpesvirusinfeksjon (M)' },
		{ code: 'Y73', text: 'Prostatitt/vesikulitt' },
		{ code: 'Y74', text: 'Orkitt/epididymitt' },
		{ code: 'Y75', text: 'Balanopostitt' },
		{ code: 'Y76', text: 'Condylomata acuminata (M)' },
		{ code: 'Y77', text: 'Ondartet svulst prostata' },
		{ code: 'Y78', text: 'Ondartet svulst kjønnsorg IKA (M)' },
		{ code: 'Y79', text: 'Godartet/uspes svulst kjønnsorg (M)' },
		{ code: 'Y80', text: 'Skade kjønnsorgan (M)' },
		{ code: 'Y81', text: 'Fimose/overflødig forhud' },
		{ code: 'Y82', text: 'Hypospadi' },
		{ code: 'Y83', text: 'Ikke-descendert testikkel' },
		{ code: 'Y84', text: 'Medfødt feil kjønnsorgan IKA (M)' },
		{ code: 'Y85', text: 'Prostatahyperplasi' },
		{ code: 'Y86', text: 'Hydrocele' },
		{ code: 'Y99', text: 'Kjønnsorgan sykdom IKA (M)' },
		{ code: 'Z01', text: 'Problem økonomi/fattigdom' },
		{ code: 'Z02', text: 'Problem drikkevann/mat' },
		{ code: 'Z03', text: 'Problem bolig/nabolag' },
		{ code: 'Z04', text: 'Problem sosialt/kulturelt' },
		{ code: 'Z05', text: 'Problem arbeidsforhold/yrke' },
		{ code: 'Z06', text: 'Problem arbeidsledighet' },
		{ code: 'Z07', text: 'Problem utdannelse' },
		{ code: 'Z08', text: 'Problem sosial velferd/trygd' },
		{ code: 'Z09', text: 'Problem jus/politi' },
		{ code: 'Z10', text: 'Problem helsetjen/tilgjengelighet' },
		{ code: 'Z11', text: 'Problem det å være syk/compliance' },
		{ code: 'Z12', text: 'Problem mellom samlivspartnere' },
		{ code: 'Z13', text: 'Problem atferd samlivspartner' },
		{ code: 'Z14', text: 'Problem sykdom hos partner' },
		{ code: 'Z15', text: 'Problem tap/dødsfall av partner' },
		{ code: 'Z16', text: 'Problem med/i forhold til barn' },
		{ code: 'Z18', text: 'Problem sykdom hos barn' },
		{ code: 'Z19', text: 'Problem tap/dødsfall av barn' },
		{ code: 'Z20', text: 'Problem forhold til foreldre/familie' },
		{ code: 'Z21', text: 'Problem atferd foreldre/familie' },
		{ code: 'Z22', text: 'Problem med sykdom hos foreldre/fam' },
		{ code: 'Z23', text: 'Problem tap/dødsfall av foreldre/fam' },
		{ code: 'Z24', text: 'Problem med forhold til venner' },
		{ code: 'Z25', text: 'Problem vold/traumatisk hendelse' },
		{ code: 'Z27', text: 'Engstelig for sosialt problem' },
		{ code: 'Z28', text: 'Redusert funksjonsevne sosialt probl' },
		{ code: 'Z29', text: 'Sosialt problem IKA' },
		{ code: 'Z30', text: 'Medisinsk undersøkelse fullstendig' },
		{ code: 'Z31', text: 'Medisinsk undersøkelse målrettet' },
		{ code: 'Z32', text: 'Sensitivitetsprøve' },
		{ code: 'Z33', text: 'Mikrobiologisk/immunologisk prøve' },
		{ code: 'Z34', text: 'Blodprøve IKA' },
		{ code: 'Z35', text: 'Urinprøve IKA' },
		{ code: 'Z36', text: 'Avføringsprøve IKA' },
		{ code: 'Z37', text: 'Histologisk/cytologisk prøve' },
		{ code: 'Z38', text: 'Laboratorieprøve IKA' },
		{ code: 'Z39', text: 'Fysisk funksjonsprøve' },
		{ code: 'Z40', text: 'Endoskopi' },
		{ code: 'Z41', text: 'Billeddiagnostikk' },
		{ code: 'Z42', text: 'Biosignalundersøkelse IKA' },
		{ code: 'Z43', text: 'Diagnostisk prosedyre IKA' },
		{ code: 'Z44', text: 'Forebyggende vaksinering/medikasjon' },
		{ code: 'Z45', text: 'Helseopplysning/rådgivning' },
		{ code: 'Z46', text: 'Kontakt med primærhelsetjenesten' },
		{ code: 'Z47', text: 'Kontakt med spesialist' },
		{ code: 'Z48', text: 'Vurdering av kontaktårsak/behov' },
		{ code: 'Z49', text: 'Forebyggende prosedyre IKA' },
		{ code: 'Z50', text: 'Legemiddelforskrivning/-administrasj' },
		{ code: 'Z51', text: 'Incisjon/tapping/aspirasjon' },
		{ code: 'Z52', text: 'Fjerne vev/biopsi/kauterisasjon' },
		{ code: 'Z53', text: 'Kateterisering/intub/dilatasjon' },
		{ code: 'Z54', text: 'Fiksering/suturering/gips/protese' },
		{ code: 'Z55', text: 'Lokal injeksjon/infiltrasjon' },
		{ code: 'Z56', text: 'Bandasje/kompresjon/tamponade' },
		{ code: 'Z57', text: 'Fysikalsk behandling/rehabilitering' },
		{ code: 'Z58', text: 'Terapeutisk rådgivning/samtale' },
		{ code: 'Z59', text: 'Terapeutisk tiltak/småkirurgi IKA' },
		{ code: 'Z60', text: 'Resultat av prøve/prosedyre' },
		{ code: 'Z61', text: 'Resultat undersøkelse/epikrise' },
		{ code: 'Z62', text: 'Administrativ prosedyre' },
		{ code: 'Z63', text: 'Observasjon/oppfølging IKA' },
		{ code: 'Z64', text: 'Kontakt forårsaket av helsepersonell' },
		{ code: 'Z65', text: 'Kontakt forårsaket annen enn pasient' },
		{ code: 'Z66', text: 'Henvisning annet helsepersonell IKA' },
		{ code: 'Z67', text: 'Henvisning spesialist/sykehus' },
		{ code: 'Z68', text: 'Henvisning IKA' },
		{ code: 'Z69', text: 'Kontaktårsak IKA' }
	]
}
