ALTER TABLE ORGANISASJON_ORDER
    ALTER COLUMN BATCH_ID INTEGER NULL;

ALTER TABLE ORGANISASJON_ORDER
    ALTER COLUMN ENVIRONMENT VARCHAR (64) NULL;

ALTER TABLE ORGANISASJON_ORDER
    ADD UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;