CREATE TABLE ORG_ORDER
(
    ID          SERIAL PRIMARY KEY,
    UUID        VARCHAR(256) NOT NULL,
    QUEUE_ID    INTEGER      NOT NULL,
    BUILD_ID    INTEGER      NUll,
    BATCH_ID    INTEGER      NULL,
    ENVIRONMENT VARCHAR(32)  NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);