package no.nav.testnav.kodeverkservice.utility;

import lombok.experimental.UtilityClass;
import no.nav.testnav.libs.dto.kodeverkservice.v1.KodeverkAdjustedDTO;
import no.nav.testnav.libs.dto.kodeverkservice.v1.KodeverkAdjustedDTO.KodeAdjusted;
import no.nav.testnav.libs.dto.kodeverkservice.v1.KodeverkDTO;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import static no.nav.testnav.kodeverkservice.utility.CommonKeysAndUtils.GYLDIG_FRA;
import static no.nav.testnav.kodeverkservice.utility.CommonKeysAndUtils.GYLDIG_TIL;
import static no.nav.testnav.kodeverkservice.utility.CommonKeysAndUtils.YRKESKLASSIFISERING;

@UtilityClass
public class YrkesklassifiseringUtility {

    private static final List<Map<String, String>> yrkesklassifisering = new ArrayList<>();

    static {
        yrkesklassifisering.add(Map.of("0", "Militære yrker og uoppgitt"));
        yrkesklassifisering.add(Map.of("1", "Ledere"));
        yrkesklassifisering.add(Map.of("2", "Akademiske yrker"));
        yrkesklassifisering.add(Map.of("3", "Høyskoleyrker"));
        yrkesklassifisering.add(Map.of("4", "Kontoryrker"));
        yrkesklassifisering.add(Map.of("5", "Salgs- og serviceyrker"));
        yrkesklassifisering.add(Map.of("6", "Bønder, fiskere mv."));
        yrkesklassifisering.add(Map.of("7", "Håndverkere"));
        yrkesklassifisering.add(Map.of("8", "Prosess- og maskinoperatører, transportarbeidere mv."));
        yrkesklassifisering.add(Map.of("9", "Renholdere, hjelpearbeidere mv."));
        yrkesklassifisering.add(Map.of("00", "Uoppgitt / yrker som ikke kan identifiseres"));
        yrkesklassifisering.add(Map.of("01", "Offiserer fra fenrik og høyere grad"));
        yrkesklassifisering.add(Map.of("02", "Befal med sersjant grad"));
        yrkesklassifisering.add(Map.of("03", "Menige"));
        yrkesklassifisering.add(Map.of("11", "Politikere og toppledere"));
        yrkesklassifisering.add(Map.of("12", "Administrative og merkantile ledere"));
        yrkesklassifisering.add(Map.of("13", "Ledere av enheter for vareproduksjon og tjenesteyting"));
        yrkesklassifisering.add(Map.of("14", "Ledere i hotell, restaurant, varehandel mv."));
        yrkesklassifisering.add(Map.of("21", "Realister, sivilingeniører mv."));
        yrkesklassifisering.add(Map.of("22", "Medisinske yrker"));
        yrkesklassifisering.add(Map.of("23", "Undervisningsyrker"));
        yrkesklassifisering.add(Map.of("24", "Rådgivere innen økonomi, administrasjon og salg"));
        yrkesklassifisering.add(Map.of("25", "IKT-rådgivere"));
        yrkesklassifisering.add(Map.of("26", "Juridiske, samfunnsvitenskapelige og humanistiske yrker"));
        yrkesklassifisering.add(Map.of("31", "Ingeniører mv."));
        yrkesklassifisering.add(Map.of("32", "Helserelaterte yrker"));
        yrkesklassifisering.add(Map.of("33", "Medarbeidere innen økonomi, administrasjon og salg"));
        yrkesklassifisering.add(Map.of("34", "Yrker innen kultur, idrett mv."));
        yrkesklassifisering.add(Map.of("35", "IKT-teknikere"));
        yrkesklassifisering.add(Map.of("41", "Kontormedarbeidere"));
        yrkesklassifisering.add(Map.of("42", "Kundeserviceyrker"));
        yrkesklassifisering.add(Map.of("43", "ÿkonomi- og logistikkmedarbeidere"));
        yrkesklassifisering.add(Map.of("44", "Postbud, arkiv- og personalkontormedarbeidere"));
        yrkesklassifisering.add(Map.of("51", "Yrker innen personlig tjenesteyting"));
        yrkesklassifisering.add(Map.of("52", "Salgsyrker"));
        yrkesklassifisering.add(Map.of("53", "Pleie- og omsorgsarbeidere"));
        yrkesklassifisering.add(Map.of("54", "Sikkerhetsarbeidere"));
        yrkesklassifisering.add(Map.of("61", "Jordbrukere"));
        yrkesklassifisering.add(Map.of("62", "Skogbrukere, fiskere mv."));
        yrkesklassifisering.add(Map.of("71", "Byggearbeidere"));
        yrkesklassifisering.add(Map.of("72", "Metall- og maskinarbeidere"));
        yrkesklassifisering.add(Map.of("73", "Presisjonsarbeidere, kunsthåndverkere, grafiske arbeidere mv."));
        yrkesklassifisering.add(Map.of("74", "Elektrikere, elektronikere mv."));
        yrkesklassifisering.add(Map.of("75", "Andre håndverkspregede yrker"));
        yrkesklassifisering.add(Map.of("81", "Prosess- og maskinoperatører"));
        yrkesklassifisering.add(Map.of("82", "Montører"));
        yrkesklassifisering.add(Map.of("83", "Transportarbeidere og operatører av mobile maskiner mv."));
        yrkesklassifisering.add(Map.of("91", "Renholdere mv."));
        yrkesklassifisering.add(Map.of("92", "Hjelpearbeidere i jordbruk, skogbruk og fiske"));
        yrkesklassifisering.add(Map.of("93", "Hjelpearbeidere i bergverk, industri, bygg og anlegg og transport"));
        yrkesklassifisering.add(Map.of("94", "Kjøkkenassistenter"));
        yrkesklassifisering.add(Map.of("95", "Reklamedistributører mv."));
        yrkesklassifisering.add(Map.of("96", "Renovasjons- og gjenvinningsarbeidere mv."));
        yrkesklassifisering.add(Map.of("000", "Uoppgitt / yrker som ikke kan identifiseres"));
        yrkesklassifisering.add(Map.of("011", "Offiserer fra fenrik og høyere grad"));
        yrkesklassifisering.add(Map.of("021", "Befal med sersjant grad"));
        yrkesklassifisering.add(Map.of("031", "Menige"));
        yrkesklassifisering.add(Map.of("111", "Politikere og toppledere i offentlig administrasjon"));
        yrkesklassifisering.add(Map.of("112", "Administrerende direktører"));
        yrkesklassifisering.add(Map.of("121", "Ledere av administrative enheter"));
        yrkesklassifisering.add(Map.of("122", "Ledere av salgs-, PR- og forskningsenheter"));
        yrkesklassifisering.add(Map.of("131", "Ledere i gartnerier, akvakultur mv."));
        yrkesklassifisering.add(Map.of("132", "Ledere av produksjon, utvinning, bygg og anlegg, transport"));
        yrkesklassifisering.add(Map.of("133", "Ledere av IKT-enheter"));
        yrkesklassifisering.add(Map.of("134", "Ledere av utdanning, helse- og sosialtjenester"));
        yrkesklassifisering.add(Map.of("141", "Ledere i hotell og restaurant"));
        yrkesklassifisering.add(Map.of("142", "Varehandelssjefer"));
        yrkesklassifisering.add(Map.of("143", "Daglige ledere, andre tjenesteytende virksomheter"));
        yrkesklassifisering.add(Map.of("211", "Fysikere, kjemikere mv."));
        yrkesklassifisering.add(Map.of("212", "Matematikere, statistikere mv."));
        yrkesklassifisering.add(Map.of("213", "Biologiske yrker mv."));
        yrkesklassifisering.add(Map.of("214", "Sivilingeniører (unntatt elektroteknologi)"));
        yrkesklassifisering.add(Map.of("215", "Sivilingeniører elektroteknologi"));
        yrkesklassifisering.add(Map.of("216", "Arkitekter, designere mv."));
        yrkesklassifisering.add(Map.of("221", "Leger"));
        yrkesklassifisering.add(Map.of("222", "Sykepleiere og spesialsykepleiere"));
        yrkesklassifisering.add(Map.of("225", "Veterinærer"));
        yrkesklassifisering.add(Map.of("226", "Andre medisinske yrker"));
        yrkesklassifisering.add(Map.of("231", "Universitets- og høyskolelektorer/-lærere"));
        yrkesklassifisering.add(Map.of("232", "Yrkesfaglærere"));
        yrkesklassifisering.add(Map.of("233", "Lektorer mv (videregående skole)"));
        yrkesklassifisering.add(Map.of("234", "Grunnskole- og førskole-/barnehagelærere"));
        yrkesklassifisering.add(Map.of("235", "Andre lærere"));
        yrkesklassifisering.add(Map.of("241", "Finansrådgivere"));
        yrkesklassifisering.add(Map.of("242", "Administrasjonsrådgivere"));
        yrkesklassifisering.add(Map.of("243", "Rådgivere innen salg, markedsføring mv."));
        yrkesklassifisering.add(Map.of("251", "Programvare- og applikasjonsutviklere/analytikere"));
        yrkesklassifisering.add(Map.of("252", "Databasedesignere, systemadministratorer mv."));
        yrkesklassifisering.add(Map.of("261", "Juridiske yrker"));
        yrkesklassifisering.add(Map.of("262", "Bibliotekarer, arkivarer mv."));
        yrkesklassifisering.add(Map.of("263", "Samfunnsvitenskapelige, humanistiske og religiøse yrker"));
        yrkesklassifisering.add(Map.of("264", "Forfattere, journalister mv."));
        yrkesklassifisering.add(Map.of("265", "Profesjonelle kunstnere"));
        yrkesklassifisering.add(Map.of("311", "Ingeniører"));
        yrkesklassifisering.add(Map.of("312", "Arbeidsledere innen bergfag, industri, bygg og anlegg"));
        yrkesklassifisering.add(Map.of("313", "Prosesskontrollører"));
        yrkesklassifisering.add(Map.of("314", "Bioteknikere mv."));
        yrkesklassifisering.add(Map.of("315", "Skipoffiserer, flygere, flygeledere mv."));
        yrkesklassifisering.add(Map.of("321", "Radiografer, proteseteknikere, reseptarer mv."));
        yrkesklassifisering.add(Map.of("323", "Yrker innen alternativ medisin"));
        yrkesklassifisering.add(Map.of("324", "Dyrepleiere"));
        yrkesklassifisering.add(Map.of("325", "Andre helseyrker"));
        yrkesklassifisering.add(Map.of("331", "Yrker innen finanstjenester"));
        yrkesklassifisering.add(Map.of("332", "Agenter og meglere"));
        yrkesklassifisering.add(Map.of("333", "Forretningstjenesteyrker"));
        yrkesklassifisering.add(Map.of("334", "Sekretærer og arbeidsledere for kontorpersonell"));
        yrkesklassifisering.add(Map.of("335", "Yrker innen offentlig forvaltning"));
        yrkesklassifisering.add(Map.of("341", "Yrker innen sosialarbeid og kultur"));
        yrkesklassifisering.add(Map.of("342", "Yrker innen sport og idrett"));
        yrkesklassifisering.add(Map.of("343", "Yrker innen estetiske fag"));
        yrkesklassifisering.add(Map.of("351", "Operatører og brukerstøtte, IKT"));
        yrkesklassifisering.add(Map.of("352", "Teknikere innen kringkasting og telekom"));
        yrkesklassifisering.add(Map.of("411", "Kontormedarbeidere"));
        yrkesklassifisering.add(Map.of("413", "Dataregistrere og stenografer"));
        yrkesklassifisering.add(Map.of("421", "Kundebehandlere, penger og pengespill"));
        yrkesklassifisering.add(Map.of("422", "Reisebyrå-, resepsjons- og andre opplysningsmedarbeidere"));
        yrkesklassifisering.add(Map.of("431", "Regnskaps- og lønnsmedarbeidere mv."));
        yrkesklassifisering.add(Map.of("432", "Lager- og transportmedarbeidere"));
        yrkesklassifisering.add(Map.of("441", "Postbud, arkiv- og personalkontor-medarbeidere"));
        yrkesklassifisering.add(Map.of("511", "Persontransportpersonell"));
        yrkesklassifisering.add(Map.of("512", "Kokker"));
        yrkesklassifisering.add(Map.of("513", "Servitører og bartendere"));
        yrkesklassifisering.add(Map.of("514", "Frisører, kosmetologer mv."));
        yrkesklassifisering.add(Map.of("515", "Renholdsledere og vaktmestre"));
        yrkesklassifisering.add(Map.of("516", "Andre yrker innen personlig tjenesteyting"));
        yrkesklassifisering.add(Map.of("521", "Torg og markedsselgere"));
        yrkesklassifisering.add(Map.of("522", "Butikkselgere"));
        yrkesklassifisering.add(Map.of("523", "Billettselgere"));
        yrkesklassifisering.add(Map.of("524", "Andre salgsyrker"));
        yrkesklassifisering.add(Map.of("531", "Barnehage- og skoleassistenter mv."));
        yrkesklassifisering.add(Map.of("532", "Pleiemedarbeidere"));
        yrkesklassifisering.add(Map.of("541", "Sikkerhetsarbeidere"));
        yrkesklassifisering.add(Map.of("611", "Korn-, grønnsaks-, frukt- og bærprodusenter, gartnere"));
        yrkesklassifisering.add(Map.of("612", "Husdyr-, egg- og melkeprodusenter"));
        yrkesklassifisering.add(Map.of("613", "Plante- og husdyrprodusenter (kombinasjonsbruk)"));
        yrkesklassifisering.add(Map.of("621", "Skogbrukere"));
        yrkesklassifisering.add(Map.of("622", "Havbruksarbeidere og fiskere"));
        yrkesklassifisering.add(Map.of("711", "Bygningsarbeidere"));
        yrkesklassifisering.add(Map.of("712", "Bygningstekniske arbeidere"));
        yrkesklassifisering.add(Map.of("713", "Malere, overflatebehandlere, feiere mv."));
        yrkesklassifisering.add(Map.of("721", "Støpere, sveisere, platearbeidere mv."));
        yrkesklassifisering.add(Map.of("722", "Smeder, verktøymakere mv."));
        yrkesklassifisering.add(Map.of("723", "Mekanikere og reparatører"));
        yrkesklassifisering.add(Map.of("731", "Presisjonsarbeidere og kunsthåndverkere"));
        yrkesklassifisering.add(Map.of("732", "Grafiske arbeidere"));
        yrkesklassifisering.add(Map.of("741", "Elektrikere mv."));
        yrkesklassifisering.add(Map.of("742", "Serviceelektronikere og tele- og IKT-installatører mv."));
        yrkesklassifisering.add(Map.of("751", "Slaktere, fiskehandlere, konditorer mv."));
        yrkesklassifisering.add(Map.of("752", "Møbelsnekkere"));
        yrkesklassifisering.add(Map.of("753", "Skreddere, møbeltapetserere mv."));
        yrkesklassifisering.add(Map.of("754", "Yrkesdykkere, skytebaser mv."));
        yrkesklassifisering.add(Map.of("811", "Operatører innen borefag mv."));
        yrkesklassifisering.add(Map.of("812", "Operatører metallproduksjon"));
        yrkesklassifisering.add(Map.of("813", "Operatører innen produksjon av kjemiske produkter"));
        yrkesklassifisering.add(Map.of("814", "Operatører innen gummi, plast og papirproduksjon"));
        yrkesklassifisering.add(Map.of("815", "Operatører innen bearbeiding og produksjon av tekstiler, pels, skinn og lær"));
        yrkesklassifisering.add(Map.of("816", "Operatører innen næringsmiddelproduksjon"));
        yrkesklassifisering.add(Map.of("817", "Operatører innen treforedling og trelast"));
        yrkesklassifisering.add(Map.of("818", "Operatører av andre stasjonære maskiner"));
        yrkesklassifisering.add(Map.of("821", "Montører"));
        yrkesklassifisering.add(Map.of("831", "Lokomotiv og T-baneførere mv."));
        yrkesklassifisering.add(Map.of("832", "Bil-, drosje- og varebilførere"));
        yrkesklassifisering.add(Map.of("833", "Lastebil-, buss- og trikkeførere"));
        yrkesklassifisering.add(Map.of("834", "Operatører av mobile maskiner mv."));
        yrkesklassifisering.add(Map.of("835", "Dekks- og maskinmannskap (skip)"));
        yrkesklassifisering.add(Map.of("911", "Renholdere"));
        yrkesklassifisering.add(Map.of("912", "Bilvaskere, vinduspussere mv."));
        yrkesklassifisering.add(Map.of("921", "Hjelpearbeidere i jordbruk, skogbruk og fiske"));
        yrkesklassifisering.add(Map.of("931", "Hjelpearbeidere i bergverk, bygg og anlegg"));
        yrkesklassifisering.add(Map.of("932", "Hjelpearbeidere i industri"));
        yrkesklassifisering.add(Map.of("933", "Hjelpearbeidere innen transport og lager"));
        yrkesklassifisering.add(Map.of("941", "Kjøkkenassistenter"));
        yrkesklassifisering.add(Map.of("951", "Reklamedistributører mv."));
        yrkesklassifisering.add(Map.of("961", "Renovasjons- og gjenvinningsarbeidere"));
        yrkesklassifisering.add(Map.of("962", "Andre hjelpearbeidere"));
        yrkesklassifisering.add(Map.of("0000", "Uoppgitt / yrker som ikke kan identifiseres"));
        yrkesklassifisering.add(Map.of("0110", "Offiserer fra fenrik og høyere grad"));
        yrkesklassifisering.add(Map.of("0210", "Befal med sersjant grad"));
        yrkesklassifisering.add(Map.of("0310", "Menige"));
        yrkesklassifisering.add(Map.of("1111", "Politikere"));
        yrkesklassifisering.add(Map.of("1112", "Toppledere i offentlig administrasjon"));
        yrkesklassifisering.add(Map.of("1114", "Toppledere i interesseorganisasjoner"));
        yrkesklassifisering.add(Map.of("1120", "Administrerende direktører"));
        yrkesklassifisering.add(Map.of("1211", "Finans- og økonomisjefer"));
        yrkesklassifisering.add(Map.of("1212", "Personalsjefer"));
        yrkesklassifisering.add(Map.of("1213", "Strategi- og planleggingssjefer"));
        yrkesklassifisering.add(Map.of("1219", "Andre administrative ledere"));
        yrkesklassifisering.add(Map.of("1221", "Salgs- og markedssjefer"));
        yrkesklassifisering.add(Map.of("1222", "PR- og informasjonssjefer"));
        yrkesklassifisering.add(Map.of("1223", "Forsknings- og utviklingsledere"));
        yrkesklassifisering.add(Map.of("1311", "Ledere i skogbruk, gartnerier mv."));
        yrkesklassifisering.add(Map.of("1312", "Ledere innen akvakultur mv."));
        yrkesklassifisering.add(Map.of("1321", "Ledere av industriproduksjon mv."));
        yrkesklassifisering.add(Map.of("1322", "Ledere av olje- og gassutvinning mv."));
        yrkesklassifisering.add(Map.of("1323", "Ledere av bygge- og anleggsvirksomhet"));
        yrkesklassifisering.add(Map.of("1324", "Ledere av logistikk og transport mv."));
        yrkesklassifisering.add(Map.of("1330", "Ledere av IKT-enheter"));
        yrkesklassifisering.add(Map.of("1341", "Ledere av omsorgstjenester for barn"));
        yrkesklassifisering.add(Map.of("1342", "Ledere av helsetjenester"));
        yrkesklassifisering.add(Map.of("1343", "Ledere av eldreomsorg"));
        yrkesklassifisering.add(Map.of("1344", "Ledere av sosialomsorg"));
        yrkesklassifisering.add(Map.of("1345", "Ledere av utdanning og undervisning"));
        yrkesklassifisering.add(Map.of("1346", "Ledere av forsikring og finansvirksomhet"));
        yrkesklassifisering.add(Map.of("1349", "Andre ledere av produksjon og tjenesteyting"));
        yrkesklassifisering.add(Map.of("1411", "Hotellsjefer"));
        yrkesklassifisering.add(Map.of("1412", "Restaurantsjefer"));
        yrkesklassifisering.add(Map.of("1420", "Varehandelssjefer"));
        yrkesklassifisering.add(Map.of("1431", "Sports-, rekreasjons- og kultursenterledere"));
        yrkesklassifisering.add(Map.of("1439", "Andre daglige ledere i tjenesteytende virksomheter"));
        yrkesklassifisering.add(Map.of("2111", "Fysikere og astronomer"));
        yrkesklassifisering.add(Map.of("2112", "Meteorologer"));
        yrkesklassifisering.add(Map.of("2113", "Kjemikere"));
        yrkesklassifisering.add(Map.of("2114", "Geologer og geofysikere"));
        yrkesklassifisering.add(Map.of("2120", "Matematikere, statistikere mv."));
        yrkesklassifisering.add(Map.of("2131", "Biologer, botanikere, zoologer mv."));
        yrkesklassifisering.add(Map.of("2132", "Sivilagronomer mv."));
        yrkesklassifisering.add(Map.of("2133", "Miljøvernrådgivere"));
        yrkesklassifisering.add(Map.of("2141", "Sivilingeniører (industri og produksjon)"));
        yrkesklassifisering.add(Map.of("2142", "Sivilingeniører (bygg og anlegg)"));
        yrkesklassifisering.add(Map.of("2143", "Sivilingeniører (miljøteknikk)"));
        yrkesklassifisering.add(Map.of("2144", "Sivilingeniører (maskin- og marin-teknikk)"));
        yrkesklassifisering.add(Map.of("2145", "Sivilingeniører (kjemi)"));
        yrkesklassifisering.add(Map.of("2146", "Sivilingeniører (geofag, petro-leumsteknologi, metallurgi mv.)"));
        yrkesklassifisering.add(Map.of("2149", "Andre sivilingeniører (unntatt elektroteknologi)"));
        yrkesklassifisering.add(Map.of("2151", "Sivilingeniører (elkraftteknikk)"));
        yrkesklassifisering.add(Map.of("2152", "Sivilingeniører (elektronikk)"));
        yrkesklassifisering.add(Map.of("2153", "Sivilingeniører (telekommunikasjon)"));
        yrkesklassifisering.add(Map.of("2161", "Sivilarkitekter"));
        yrkesklassifisering.add(Map.of("2162", "Landskapsarkitekter"));
        yrkesklassifisering.add(Map.of("2163", "Produkt- og klesdesignere"));
        yrkesklassifisering.add(Map.of("2164", "Arealplanleggere"));
        yrkesklassifisering.add(Map.of("2165", "Landmålere, kartografer mv."));
        yrkesklassifisering.add(Map.of("2166", "Grafiske- og multimediadesignere"));
        yrkesklassifisering.add(Map.of("2211", "Allmennpraktiserende leger"));
        yrkesklassifisering.add(Map.of("2212", "Legespesialister"));
        yrkesklassifisering.add(Map.of("2221", "Spesialsykepleiere"));
        yrkesklassifisering.add(Map.of("2222", "Jordmødre"));
        yrkesklassifisering.add(Map.of("2223", "Sykepleiere"));
        yrkesklassifisering.add(Map.of("2224", "Vernepleiere"));
        yrkesklassifisering.add(Map.of("2250", "Veterinærer"));
        yrkesklassifisering.add(Map.of("2261", "Tannleger"));
        yrkesklassifisering.add(Map.of("2262", "Farmasøyter"));
        yrkesklassifisering.add(Map.of("2263", "Helse- og miljørådgivere"));
        yrkesklassifisering.add(Map.of("2264", "Fysioterapeuter"));
        yrkesklassifisering.add(Map.of("2265", "Ernæringsfysiologer"));
        yrkesklassifisering.add(Map.of("2266", "Audiografer og logopeder"));
        yrkesklassifisering.add(Map.of("2267", "Ergoterapeuter"));
        yrkesklassifisering.add(Map.of("2269", "Kiropraktorer mv."));
        yrkesklassifisering.add(Map.of("2310", "Universitets- og høyskolelektorer/-lærere"));
        yrkesklassifisering.add(Map.of("2320", "Yrkesfaglærere"));
        yrkesklassifisering.add(Map.of("2330", "Lektorer mv. (videregående skole)"));
        yrkesklassifisering.add(Map.of("2341", "Grunnskolelærere"));
        yrkesklassifisering.add(Map.of("2342", "Førskole-/barnehagelærere"));
        yrkesklassifisering.add(Map.of("2351", "Spesialister i pedagogikk"));
        yrkesklassifisering.add(Map.of("2352", "Spesiallærere / spesialpedagoger"));
        yrkesklassifisering.add(Map.of("2353", "Andre språklærere"));
        yrkesklassifisering.add(Map.of("2354", "Andre musikklærere"));
        yrkesklassifisering.add(Map.of("2355", "Andre lærere i estetiske fag"));
        yrkesklassifisering.add(Map.of("2356", "Andre IKT-lærere"));
        yrkesklassifisering.add(Map.of("2359", "Andre lærere"));
        yrkesklassifisering.add(Map.of("2411", "Revisorer, regnskapsrådgivere"));
        yrkesklassifisering.add(Map.of("2412", "Finans- og investeringsrådgivere"));
        yrkesklassifisering.add(Map.of("2413", "Finansanalytikere"));
        yrkesklassifisering.add(Map.of("2421", "Organisasjonsrådgivere mv."));
        yrkesklassifisering.add(Map.of("2422", "Høyere saksbehandlere i offentlig og privat virksomhet"));
        yrkesklassifisering.add(Map.of("2423", "Personal- og karriererådgivere"));
        yrkesklassifisering.add(Map.of("2424", "Rådgivere innen kompetanseutvikling"));
        yrkesklassifisering.add(Map.of("2431", "Reklame- og markedsføringsrådgivere"));
        yrkesklassifisering.add(Map.of("2432", "Informasjonsrådgivere"));
        yrkesklassifisering.add(Map.of("2433", "Salgskonsulenter innen tekniske og medisinske produkter"));
        yrkesklassifisering.add(Map.of("2434", "Salgskonsulenter innen IKT-produkter"));
        yrkesklassifisering.add(Map.of("2511", "Systemanalytikere/-arkitekter"));
        yrkesklassifisering.add(Map.of("2512", "Programvareutviklere"));
        yrkesklassifisering.add(Map.of("2513", "Nett- og multimediautviklere"));
        yrkesklassifisering.add(Map.of("2514", "Applikasjonsprogrammerere"));
        yrkesklassifisering.add(Map.of("2519", "Andre programvare- og applikasjonsutviklere"));
        yrkesklassifisering.add(Map.of("2521", "Databasedesignere og -administratorer"));
        yrkesklassifisering.add(Map.of("2522", "Systemadministratorer"));
        yrkesklassifisering.add(Map.of("2523", "Nettverksansvarlige"));
        yrkesklassifisering.add(Map.of("2529", "Sikkerhetsanalytikere mv."));
        yrkesklassifisering.add(Map.of("2611", "Jurister og advokater"));
        yrkesklassifisering.add(Map.of("2612", "Dommere"));
        yrkesklassifisering.add(Map.of("2619", "Andre juridiske yrker"));
        yrkesklassifisering.add(Map.of("2621", "Arkivarer og kuratorer"));
        yrkesklassifisering.add(Map.of("2622", "Bibliotekarer og andre informasjonsarbeidere"));
        yrkesklassifisering.add(Map.of("2631", "Rådgivere/forskere, samfunnsøkonomi"));
        yrkesklassifisering.add(Map.of("2632", "Rådgivere/forskere, samfunnsvitenskap"));
        yrkesklassifisering.add(Map.of("2633", "Rådgivere/forskere, humanistiske fag"));
        yrkesklassifisering.add(Map.of("2634", "Psykologer"));
        yrkesklassifisering.add(Map.of("2635", "Rådgivere innen sosiale fagfelt"));
        yrkesklassifisering.add(Map.of("2636", "Geistlige yrker"));
        yrkesklassifisering.add(Map.of("2641", "Forfattere mv."));
        yrkesklassifisering.add(Map.of("2642", "Journalister"));
        yrkesklassifisering.add(Map.of("2643", "Oversettere, tolker mv."));
        yrkesklassifisering.add(Map.of("2651", "Skulptører, kunstmalere og andre billedkunstnere"));
        yrkesklassifisering.add(Map.of("2652", "Dirigenter, komponister, musikere og sangere"));
        yrkesklassifisering.add(Map.of("2653", "Koreografer og dansere"));
        yrkesklassifisering.add(Map.of("2654", "Regissører"));
        yrkesklassifisering.add(Map.of("2655", "Skuespillere"));
        yrkesklassifisering.add(Map.of("2656", "Programledere i TV og radio"));
        yrkesklassifisering.add(Map.of("2659", "Andre utøvende kunstneriske yrker"));
        yrkesklassifisering.add(Map.of("3112", "Bygningsingeniører"));
        yrkesklassifisering.add(Map.of("3113", "Elkraftingeniører"));
        yrkesklassifisering.add(Map.of("3114", "Elektronikkingeniører"));
        yrkesklassifisering.add(Map.of("3115", "Maskiningeniører"));
        yrkesklassifisering.add(Map.of("3116", "Kjemiingeniører"));
        yrkesklassifisering.add(Map.of("3117", "Ingeniører innen petroleum, bergverk og metallurgi"));
        yrkesklassifisering.add(Map.of("3118", "Tekniske tegnere"));
        yrkesklassifisering.add(Map.of("3119", "Andre ingeniører"));
        yrkesklassifisering.add(Map.of("3121", "Arbeidsleder, bergfag"));
        yrkesklassifisering.add(Map.of("3122", "Arbeidsleder, industri"));
        yrkesklassifisering.add(Map.of("3123", "Arbeidsleder, bygg og anlegg"));
        yrkesklassifisering.add(Map.of("3131", "Energikontrolloperatører"));
        yrkesklassifisering.add(Map.of("3132", "Kontrolloperatører ved forbrennings- kjøle- og vannrenseanlegg mv."));
        yrkesklassifisering.add(Map.of("3133", "Kontrolloperatører innen kjemisk prosessindustri"));
        yrkesklassifisering.add(Map.of("3134", "Kontrolloperatører ved olje- og naturgassraffineringsanlegg"));
        yrkesklassifisering.add(Map.of("3135", "Kontrolloperatører innen metallproduksjon"));
        yrkesklassifisering.add(Map.of("3139", "Andre prosesskontrolloperatører"));
        yrkesklassifisering.add(Map.of("3141", "Bioteknikere (ikke-medisinske laboratorier)"));
        yrkesklassifisering.add(Map.of("3142", "Agroteknikere"));
        yrkesklassifisering.add(Map.of("3143", "Skogteknikere"));
        yrkesklassifisering.add(Map.of("3151", "Skipsmaskinister"));
        yrkesklassifisering.add(Map.of("3152", "Dekksoffiserer og loser"));
        yrkesklassifisering.add(Map.of("3153", "Flygere"));
        yrkesklassifisering.add(Map.of("3154", "Flygeledere"));
        yrkesklassifisering.add(Map.of("3155", "Teknikere innen luftfartssikkerhet"));
        yrkesklassifisering.add(Map.of("3211", "Radiografer mv."));
        yrkesklassifisering.add(Map.of("3212", "Bioingeniører"));
        yrkesklassifisering.add(Map.of("3213", "Reseptarer"));
        yrkesklassifisering.add(Map.of("3214", "Protese- og tannteknikere"));
        yrkesklassifisering.add(Map.of("3230", "Yrker innen alternativ medisin"));
        yrkesklassifisering.add(Map.of("3240", "Dyrepleiere"));
        yrkesklassifisering.add(Map.of("3251", "Tannpleiere"));
        yrkesklassifisering.add(Map.of("3254", "Optikere"));
        yrkesklassifisering.add(Map.of("3256", "Helsesekretærer"));
        yrkesklassifisering.add(Map.of("3257", "Helse- og miljøkontrollører"));
        yrkesklassifisering.add(Map.of("3258", "Ambulansepersonell"));
        yrkesklassifisering.add(Map.of("3259", "Andre helseyrker"));
        yrkesklassifisering.add(Map.of("3311", "Finansmeglere"));
        yrkesklassifisering.add(Map.of("3312", "Kundebehandlere lån og kreditt"));
        yrkesklassifisering.add(Map.of("3313", "Regnskapsførere"));
        yrkesklassifisering.add(Map.of("3315", "Takstmenn"));
        yrkesklassifisering.add(Map.of("3321", "Forsikringsagenter"));
        yrkesklassifisering.add(Map.of("3322", "Selgere (engros)"));
        yrkesklassifisering.add(Map.of("3323", "Innkjøpere"));
        yrkesklassifisering.add(Map.of("3324", "Handels- og skipsmeglere"));
        yrkesklassifisering.add(Map.of("3331", "Speditører og befraktere"));
        yrkesklassifisering.add(Map.of("3332", "Konferanse- og arrangementsplanleggere mv."));
        yrkesklassifisering.add(Map.of("3333", "Arbeidsformidlere"));
        yrkesklassifisering.add(Map.of("3334", "Eiendomsmeglere og - forvaltere"));
        yrkesklassifisering.add(Map.of("3339", "Andre yrker innen forretningstjenester"));
        yrkesklassifisering.add(Map.of("3341", "Arbeidsledere for kontorpersonell"));
        yrkesklassifisering.add(Map.of("3342", "Advokatsekretær"));
        yrkesklassifisering.add(Map.of("3343", "Sjefssekretærer"));
        yrkesklassifisering.add(Map.of("3351", "Tollere"));
        yrkesklassifisering.add(Map.of("3352", "Skattefunksjonærer"));
        yrkesklassifisering.add(Map.of("3353", "Saksbehandlere innen sosiale ytelser"));
        yrkesklassifisering.add(Map.of("3354", "Saksbehandlere for førerkort, importlisenser mv."));
        yrkesklassifisering.add(Map.of("3355", "Politibetjenter mv."));
        yrkesklassifisering.add(Map.of("3359", "Andre yrker innen offentlig forvaltning"));
        yrkesklassifisering.add(Map.of("3411", "Privatetterforskere mv."));
        yrkesklassifisering.add(Map.of("3412", "Miljøarbeidere innen sosiale fagfelt"));
        yrkesklassifisering.add(Map.of("3413", "Religiøse yrker"));
        yrkesklassifisering.add(Map.of("3421", "Idrettsutøvere"));
        yrkesklassifisering.add(Map.of("3422", "Trenere og idrettsdommere"));
        yrkesklassifisering.add(Map.of("3423", "Sports- og aktivitetsinstruktører"));
        yrkesklassifisering.add(Map.of("3431", "Fotografer og filmfotografer"));
        yrkesklassifisering.add(Map.of("3432", "Interiørdesignere og dekoratører"));
        yrkesklassifisering.add(Map.of("3433", "Tekniske konservatorer"));
        yrkesklassifisering.add(Map.of("3434", "Sjefskokker"));
        yrkesklassifisering.add(Map.of("3439", "Andre yrker innen estetiske fag"));
        yrkesklassifisering.add(Map.of("3511", "Driftsteknikere, IKT"));
        yrkesklassifisering.add(Map.of("3512", "Brukerstøtte, IKT"));
        yrkesklassifisering.add(Map.of("3513", "Nettverks- og systemteknikere, IKT"));
        yrkesklassifisering.add(Map.of("3514", "Internett-teknikere"));
        yrkesklassifisering.add(Map.of("3521", "Teknikere innen radio og tv"));
        yrkesklassifisering.add(Map.of("3522", "Teknikere innen telekom"));
        yrkesklassifisering.add(Map.of("4110", "Kontormedarbeidere"));
        yrkesklassifisering.add(Map.of("4131", "Stenografer mv."));
        yrkesklassifisering.add(Map.of("4132", "Dataregistrere"));
        yrkesklassifisering.add(Map.of("4211", "Kundebehandlere, bank og postkontor"));
        yrkesklassifisering.add(Map.of("4212", "Bingoverter, bookmakere mv."));
        yrkesklassifisering.add(Map.of("4213", "Pantelånere mv."));
        yrkesklassifisering.add(Map.of("4214", "Inkassomedarbeidere mv."));
        yrkesklassifisering.add(Map.of("4221", "Reisebyråmedarbeidere mv."));
        yrkesklassifisering.add(Map.of("4222", "Kundesentermedarbeidere"));
        yrkesklassifisering.add(Map.of("4223", "Sentralbordoperatører"));
        yrkesklassifisering.add(Map.of("4224", "Hotellresepsjonister"));
        yrkesklassifisering.add(Map.of("4225", "Informasjonsskrankemedarbeidere"));
        yrkesklassifisering.add(Map.of("4226", "Resepsjonister (ekskl. hotell)"));
        yrkesklassifisering.add(Map.of("4227", "Intervjuere"));
        yrkesklassifisering.add(Map.of("4229", "Andre opplysningsmedarbeidere"));
        yrkesklassifisering.add(Map.of("4311", "Regnskapsmedarbeidere"));
        yrkesklassifisering.add(Map.of("4312", "Forsikrings- og finansmedarbeidere"));
        yrkesklassifisering.add(Map.of("4313", "Lønningsmedarbeidere"));
        yrkesklassifisering.add(Map.of("4321", "Lagermedarbeidere og material-forvaltere"));
        yrkesklassifisering.add(Map.of("4322", "Logistikkmedarbeidere"));
        yrkesklassifisering.add(Map.of("4323", "Transportfunksjonærer"));
        yrkesklassifisering.add(Map.of("4411", "Bibliotekassistenter"));
        yrkesklassifisering.add(Map.of("4412", "Postbud og postsorterere"));
        yrkesklassifisering.add(Map.of("4413", "Kodere mv."));
        yrkesklassifisering.add(Map.of("4415", "Arkivassistenter"));
        yrkesklassifisering.add(Map.of("4416", "Personalkontormedarbeidere"));
        yrkesklassifisering.add(Map.of("5111", "Flyverter, båtverter mv."));
        yrkesklassifisering.add(Map.of("5112", "Konduktører"));
        yrkesklassifisering.add(Map.of("5113", "Reiseledere og guider"));
        yrkesklassifisering.add(Map.of("5120", "Kokker"));
        yrkesklassifisering.add(Map.of("5131", "Servitører"));
        yrkesklassifisering.add(Map.of("5132", "Bartendere"));
        yrkesklassifisering.add(Map.of("5141", "Frisører"));
        yrkesklassifisering.add(Map.of("5142", "Kosmetologer mv."));
        yrkesklassifisering.add(Map.of("5151", "Renholdsledere i virksomheter"));
        yrkesklassifisering.add(Map.of("5152", "Husholdere"));
        yrkesklassifisering.add(Map.of("5153", "Vaktmestre"));
        yrkesklassifisering.add(Map.of("5161", "Astrologer mv."));
        yrkesklassifisering.add(Map.of("5163", "Begravelsesbyrå- og krematoriearbeidere"));
        yrkesklassifisering.add(Map.of("5164", "Dyrepassere og - trenere mv."));
        yrkesklassifisering.add(Map.of("5165", "Kjøreskolelærere"));
        yrkesklassifisering.add(Map.of("5169", "Andre personlige tjenesteytere"));
        yrkesklassifisering.add(Map.of("5211", "Torghandlere"));
        yrkesklassifisering.add(Map.of("5212", "Gateselgere, mat"));
        yrkesklassifisering.add(Map.of("5221", "Innehavere av kiosk/liten butikk"));
        yrkesklassifisering.add(Map.of("5222", "Butikkavdelingssjefer"));
        yrkesklassifisering.add(Map.of("5223", "Butikkmedarbeidere"));
        yrkesklassifisering.add(Map.of("5230", "Billettselgere"));
        yrkesklassifisering.add(Map.of("5241", "Mannekenger og modeller"));
        yrkesklassifisering.add(Map.of("5242", "Demonstrasjonsselgere"));
        yrkesklassifisering.add(Map.of("5243", "Dørselgere"));
        yrkesklassifisering.add(Map.of("5244", "Telefon- og nettselgere"));
        yrkesklassifisering.add(Map.of("5245", "Servicemedarbeidere (bensinstasjon)"));
        yrkesklassifisering.add(Map.of("5246", "Gatekjøkken- og kafÈmedarbeidere mv."));
        yrkesklassifisering.add(Map.of("5249", "Andre salgsmedarbeidere"));
        yrkesklassifisering.add(Map.of("5311", "Barnehage- og skolefritidsassistenter mv."));
        yrkesklassifisering.add(Map.of("5312", "Skoleassistenter"));
        yrkesklassifisering.add(Map.of("5321", "Helsefagarbeidere"));
        yrkesklassifisering.add(Map.of("5322", "Hjemmehjelper"));
        yrkesklassifisering.add(Map.of("5329", "Andre pleiemedarbeidere"));
        yrkesklassifisering.add(Map.of("5411", "Brannkonstabler"));
        yrkesklassifisering.add(Map.of("5413", "Fengselsbetjenter"));
        yrkesklassifisering.add(Map.of("5414", "Vektere"));
        yrkesklassifisering.add(Map.of("5419", "Andre sikkerhetsarbeidere"));
        yrkesklassifisering.add(Map.of("6111", "Korn- og grønnsaksprodusenter"));
        yrkesklassifisering.add(Map.of("6112", "Frukt- og bærprodusenter"));
        yrkesklassifisering.add(Map.of("6113", "Gartnere"));
        yrkesklassifisering.add(Map.of("6114", "Kombinasjonsbrukere, nyttevekster"));
        yrkesklassifisering.add(Map.of("6121", "Melke- og husdyrprodusenter"));
        yrkesklassifisering.add(Map.of("6122", "Egg- og fjærfeprodusenter"));
        yrkesklassifisering.add(Map.of("6123", "Birøktere mv."));
        yrkesklassifisering.add(Map.of("6129", "Andre dyreoppdrettere og røktere"));
        yrkesklassifisering.add(Map.of("6130", "Plante- og husdyrprodusenter (kombinasjonsbruk)"));
        yrkesklassifisering.add(Map.of("6210", "Skogbrukere"));
        yrkesklassifisering.add(Map.of("6221", "Havbruksarbeidere"));
        yrkesklassifisering.add(Map.of("6222", "Fiskere"));
        yrkesklassifisering.add(Map.of("6224", "Fangstfolk"));
        yrkesklassifisering.add(Map.of("7112", "Murere"));
        yrkesklassifisering.add(Map.of("7113", "Steinhoggere mv."));
        yrkesklassifisering.add(Map.of("7114", "Betongarbeidere"));
        yrkesklassifisering.add(Map.of("7115", "Tømrere og snekkere"));
        yrkesklassifisering.add(Map.of("7119", "Andre bygningsarbeidere"));
        yrkesklassifisering.add(Map.of("7121", "Taktekkere"));
        yrkesklassifisering.add(Map.of("7122", "Gulv- og flisleggere"));
        yrkesklassifisering.add(Map.of("7123", "Gips- og sparklingsarbeidere"));
        yrkesklassifisering.add(Map.of("7124", "Isolatører mv."));
        yrkesklassifisering.add(Map.of("7125", "Glassarbeidere"));
        yrkesklassifisering.add(Map.of("7126", "Rørleggere og VVS-montører"));
        yrkesklassifisering.add(Map.of("7127", "Kuldemontører mv."));
        yrkesklassifisering.add(Map.of("7131", "Malere og byggtapetserere"));
        yrkesklassifisering.add(Map.of("7132", "Overflatebehandlere og lakkerere"));
        yrkesklassifisering.add(Map.of("7133", "Feiere, fasaderenholdere mv."));
        yrkesklassifisering.add(Map.of("7211", "Støpere"));
        yrkesklassifisering.add(Map.of("7212", "Sveisere"));
        yrkesklassifisering.add(Map.of("7213", "Kopper- og blikkenslagere"));
        yrkesklassifisering.add(Map.of("7214", "Platearbeidere"));
        yrkesklassifisering.add(Map.of("7215", "Riggere og spleisere"));
        yrkesklassifisering.add(Map.of("7221", "Smeder"));
        yrkesklassifisering.add(Map.of("7222", "Verktøymaker, låsesmeder mv."));
        yrkesklassifisering.add(Map.of("7223", "Metalldreiere mv."));
        yrkesklassifisering.add(Map.of("7224", "Metallslipere"));
        yrkesklassifisering.add(Map.of("7231", "Bilmekanikere"));
        yrkesklassifisering.add(Map.of("7232", "Mekanikere innen flytekniske fag"));
        yrkesklassifisering.add(Map.of("7233", "Anleggsmaskin- og industrimekanikere"));
        yrkesklassifisering.add(Map.of("7234", "Sykkelreparatører mv."));
        yrkesklassifisering.add(Map.of("7311", "Presisjonsinstrumentmakere og -reparatører"));
        yrkesklassifisering.add(Map.of("7312", "Musikkinstrumentmakere og -stemmere"));
        yrkesklassifisering.add(Map.of("7313", "Gull- og sølvsmeder, gravører mv."));
        yrkesklassifisering.add(Map.of("7314", "Keramikere mv."));
        yrkesklassifisering.add(Map.of("7315", "Glasshåndverkere"));
        yrkesklassifisering.add(Map.of("7316", "Dekormalere mv."));
        yrkesklassifisering.add(Map.of("7317", "Kunsthåndverkere i tre mv."));
        yrkesklassifisering.add(Map.of("7318", "Vevere, strikkere mv. (innen husflidsproduksjon)"));
        yrkesklassifisering.add(Map.of("7319", "Andre kunsthåndverkere"));
        yrkesklassifisering.add(Map.of("7321", "Førtrykkere"));
        yrkesklassifisering.add(Map.of("7322", "Trykkere"));
        yrkesklassifisering.add(Map.of("7323", "Innbindere mv."));
        yrkesklassifisering.add(Map.of("7411", "Elektrikere"));
        yrkesklassifisering.add(Map.of("7412", "Automatikere"));
        yrkesklassifisering.add(Map.of("7413", "Energimontører"));
        yrkesklassifisering.add(Map.of("7421", "Serviceelektronikere"));
        yrkesklassifisering.add(Map.of("7422", "Tele- og IKT-installatører"));
        yrkesklassifisering.add(Map.of("7511", "Slaktere, fiskehandlere mv."));
        yrkesklassifisering.add(Map.of("7512", "Bakere, konditorer mv."));
        yrkesklassifisering.add(Map.of("7513", "Ystere mv. (gårdsproduksjon)"));
        yrkesklassifisering.add(Map.of("7514", "Saftere, syltere mv. (gårdsproduksjon)"));
        yrkesklassifisering.add(Map.of("7515", "Prøvesmakere og kvalitetsbedømmere av mat og drikke"));
        yrkesklassifisering.add(Map.of("7522", "Møbelsnekkere"));
        yrkesklassifisering.add(Map.of("7531", "Skreddere, buntmakere mv."));
        yrkesklassifisering.add(Map.of("7532", "Gradører"));
        yrkesklassifisering.add(Map.of("7534", "Møbeltapetserere mv."));
        yrkesklassifisering.add(Map.of("7535", "Skinnberedere og garvere"));
        yrkesklassifisering.add(Map.of("7536", "Skomakere"));
        yrkesklassifisering.add(Map.of("7541", "Yrkesdykkere"));
        yrkesklassifisering.add(Map.of("7542", "Skytebaser og sprengningsarbeidere"));
        yrkesklassifisering.add(Map.of("7543", "Produkttestere (ikke matprodukter)"));
        yrkesklassifisering.add(Map.of("7544", "Desinfeksjonsarbeidere og skadedyrbekjempere"));
        yrkesklassifisering.add(Map.of("7549", "Andre håndverkere"));
        yrkesklassifisering.add(Map.of("8111", "Bergfagarbeidere"));
        yrkesklassifisering.add(Map.of("8112", "Prosessoperatører (oppredning)"));
        yrkesklassifisering.add(Map.of("8113", "Operatører innen boring mv."));
        yrkesklassifisering.add(Map.of("8114", "Operatører innen produksjon av betong mv."));
        yrkesklassifisering.add(Map.of("8121", "Operatører innen metallurgiske prosessfag"));
        yrkesklassifisering.add(Map.of("8122", "Operatører innen metallflatebehandling"));
        yrkesklassifisering.add(Map.of("8131", "Operatører innen kjemisk industri"));
        yrkesklassifisering.add(Map.of("8132", "Operatører innen produksjon av fotofilm og -papir mv."));
        yrkesklassifisering.add(Map.of("8141", "Operatører innen produksjon av gummiprodukter"));
        yrkesklassifisering.add(Map.of("8142", "Operatører innen plastprodukter"));
        yrkesklassifisering.add(Map.of("8143", "Operatører innen papirprodukter"));
        yrkesklassifisering.add(Map.of("8151", "Spinne- og nøstemaskinoperatører"));
        yrkesklassifisering.add(Map.of("8152", "Operatører innen tekstilproduksjon mv."));
        yrkesklassifisering.add(Map.of("8153", "Industrisyere"));
        yrkesklassifisering.add(Map.of("8154", "Operatører innen tekstilbearbeiding"));
        yrkesklassifisering.add(Map.of("8155", "Operatører innen pels, skinn- og lærbearbeiding"));
        yrkesklassifisering.add(Map.of("8156", "Operatører innen skinn og lærprodukter"));
        yrkesklassifisering.add(Map.of("8157", "Renseri- og vaskerimaskinoperatører"));
        yrkesklassifisering.add(Map.of("8159", "Andre operatører innen produksjon av tekstiler, pels, skinn og lær"));
        yrkesklassifisering.add(Map.of("8160", "Operatører innen næringsmiddelproduksjon"));
        yrkesklassifisering.add(Map.of("8171", "Operatører innen treforedling"));
        yrkesklassifisering.add(Map.of("8172", "Operatører innen trelastproduksjon"));
        yrkesklassifisering.add(Map.of("8181", "Operatører innen glass- og keramisk produksjon"));
        yrkesklassifisering.add(Map.of("8182", "Fyrkjele- og turbinoperatører"));
        yrkesklassifisering.add(Map.of("8183", "Pakke-, tappe- og etikettmaskinoperatører"));
        yrkesklassifisering.add(Map.of("8189", "Andre stasjonære maskinoperatører"));
        yrkesklassifisering.add(Map.of("8211", "Montører av mekaniske produkter"));
        yrkesklassifisering.add(Map.of("8212", "Montører av elektriske og elektroniske produkter"));
        yrkesklassifisering.add(Map.of("8219", "Andre montører"));
        yrkesklassifisering.add(Map.of("8311", "Lokomotiv og T-baneførere"));
        yrkesklassifisering.add(Map.of("8312", "Skiftekonduktører mv"));
        yrkesklassifisering.add(Map.of("8322", "Bil-, drosje- og varebilførere"));
        yrkesklassifisering.add(Map.of("8331", "Bussjåfører og trikkeførere"));
        yrkesklassifisering.add(Map.of("8332", "Lastebil- og trailersjåfører"));
        yrkesklassifisering.add(Map.of("8341", "Jordbruks- og skogbruksmaskinførere"));
        yrkesklassifisering.add(Map.of("8342", "Anleggsmaskinførere"));
        yrkesklassifisering.add(Map.of("8343", "Kran- og heisførere mv."));
        yrkesklassifisering.add(Map.of("8344", "Truckførere"));
        yrkesklassifisering.add(Map.of("8350", "Dekks- og maskinmannskap (skip)"));
        yrkesklassifisering.add(Map.of("9111", "Renholdere i private hjem"));
        yrkesklassifisering.add(Map.of("9112", "Renholdere i virksomheter"));
        yrkesklassifisering.add(Map.of("9122", "Bilvaskere"));
        yrkesklassifisering.add(Map.of("9123", "Vinduspussere"));
        yrkesklassifisering.add(Map.of("9129", "Andre rengjørere"));
        yrkesklassifisering.add(Map.of("9211", "Hjelpearbeidere i nyttevekstproduksjon"));
        yrkesklassifisering.add(Map.of("9212", "Hjelpearbeidere i husdyrproduksjon"));
        yrkesklassifisering.add(Map.of("9213", "Hjelpearbeidere i kombinasjonsbruk"));
        yrkesklassifisering.add(Map.of("9214", "Hjelpearbeidere i gartneri mv."));
        yrkesklassifisering.add(Map.of("9215", "Hjelpearbeidere i skogbruk"));
        yrkesklassifisering.add(Map.of("9216", "Hjelpearbeidere innen havbruk"));
        yrkesklassifisering.add(Map.of("9311", "Hjelpearbeidere i bergverk"));
        yrkesklassifisering.add(Map.of("9312", "Hjelpearbeidere i anlegg"));
        yrkesklassifisering.add(Map.of("9313", "Hjelpearbeidere i bygg"));
        yrkesklassifisering.add(Map.of("9321", "Håndpakkere mv."));
        yrkesklassifisering.add(Map.of("9329", "Andre hjelpearbeidere i industri"));
        yrkesklassifisering.add(Map.of("9331", "Førere av ikke-motorisert kjøretøy"));
        yrkesklassifisering.add(Map.of("9333", "Laste- og lossearbeidere"));
        yrkesklassifisering.add(Map.of("9334", "Varepåfyllere"));
        yrkesklassifisering.add(Map.of("9412", "Kjøkkenassistenter"));
        yrkesklassifisering.add(Map.of("9510", "Reklamedistributører mv."));
        yrkesklassifisering.add(Map.of("9611", "Renovasjonsarbeidere"));
        yrkesklassifisering.add(Map.of("9612", "Gjenvinningsarbeidere"));
        yrkesklassifisering.add(Map.of("9613", "Gatefeiere mv."));
        yrkesklassifisering.add(Map.of("9621", "Bud mv."));
        yrkesklassifisering.add(Map.of("9622", "Altmuligmann"));
        yrkesklassifisering.add(Map.of("9623", "Måleravlesere mv."));
        yrkesklassifisering.add(Map.of("9629", "Andre hjelpearbeidere"));
    }

    public static KodeverkDTO getKodeverk() {

        return KodeverkDTO.builder()
                .kodeverknavn(YRKESKLASSIFISERING)
                .kodeverk(yrkesklassifisering.stream()
                        .map(Map::entrySet)
                        .flatMap(Collection::stream)
                        .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)))
                .build();
    }

    public static KodeverkAdjustedDTO getKodeverkAdjusted() {

        return KodeverkAdjustedDTO.builder()
                .name(YRKESKLASSIFISERING)
                .koder(yrkesklassifisering.stream()
                        .map(Map::entrySet)
                        .flatMap(Collection::stream)
                        .map(e -> KodeAdjusted.builder()
                                .value(e.getKey())
                                .label(e.getValue())
                                .gyldigFra(GYLDIG_FRA)
                                .gyldigTil(GYLDIG_TIL)
                                .build())
                        .toList())
                .build();
    }
}