package no.nav.testnav.kodeverkservice.utility;

import lombok.Getter;
import lombok.experimental.UtilityClass;
import no.nav.testnav.kodeverkservice.dto.KodeverkBetydningerResponse;

import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

@UtilityClass
public class YrkesklassifiseringUtility {

    @Getter
    private static final Map<String, String> yrkesklassifisering = new HashMap<>();

    static {

        yrkesklassifisering.put("0", "MilitÊre yrker og uoppgitt");
        yrkesklassifisering.put("1", "Ledere");
        yrkesklassifisering.put("2", "Akademiske yrker");
        yrkesklassifisering.put("3", "H¯yskoleyrker");
        yrkesklassifisering.put("4", "Kontoryrker");
        yrkesklassifisering.put("5", "Salgs- og serviceyrker");
        yrkesklassifisering.put("6", "B¯nder, fiskere mv.");
        yrkesklassifisering.put("7", "HÂndverkere");
        yrkesklassifisering.put("8", "Prosess- og maskinoperat¯rer, transportarbeidere mv.");
        yrkesklassifisering.put("9", "Renholdere, hjelpearbeidere mv.");
        yrkesklassifisering.put("00", "Uoppgitt / yrker som ikke kan identifiseres");
        yrkesklassifisering.put("01", "Offiserer fra fenrik og h¯yere grad");
        yrkesklassifisering.put("02", "Befal med sersjant grad");
        yrkesklassifisering.put("03", "Menige");
        yrkesklassifisering.put("11", "Politikere og toppledere");
        yrkesklassifisering.put("12", "Administrative og merkantile ledere");
        yrkesklassifisering.put("13", "Ledere av enheter for vareproduksjon og tjenesteyting");
        yrkesklassifisering.put("14", "Ledere i hotell, restaurant, varehandel mv.");
        yrkesklassifisering.put("21", "Realister, sivilingeni¯rer mv.");
        yrkesklassifisering.put("22", "Medisinske yrker");
        yrkesklassifisering.put("23", "Undervisningsyrker");
        yrkesklassifisering.put("24", "RÂdgivere innen ¯konomi, administrasjon og salg");
        yrkesklassifisering.put("25", "IKT-rÂdgivere");
        yrkesklassifisering.put("26", "Juridiske, samfunnsvitenskapelige og humanistiske yrker");
        yrkesklassifisering.put("31", "Ingeni¯rer mv.");
        yrkesklassifisering.put("32", "Helserelaterte yrker");
        yrkesklassifisering.put("33", "Medarbeidere innen ¯konomi, administrasjon og salg");
        yrkesklassifisering.put("34", "Yrker innen kultur, idrett mv.");
        yrkesklassifisering.put("35", "IKT-teknikere");
        yrkesklassifisering.put("41", "Kontormedarbeidere");
        yrkesklassifisering.put("42", "Kundeserviceyrker");
        yrkesklassifisering.put("43", "ÿkonomi- og logistikkmedarbeidere");
        yrkesklassifisering.put("44", "Postbud, arkiv- og personalkontormedarbeidere");
        yrkesklassifisering.put("51", "Yrker innen personlig tjenesteyting");
        yrkesklassifisering.put("52", "Salgsyrker");
        yrkesklassifisering.put("53", "Pleie- og omsorgsarbeidere");
        yrkesklassifisering.put("54", "Sikkerhetsarbeidere");
        yrkesklassifisering.put("61", "Jordbrukere");
        yrkesklassifisering.put("62", "Skogbrukere, fiskere mv.");
        yrkesklassifisering.put("71", "Byggearbeidere");
        yrkesklassifisering.put("72", "Metall- og maskinarbeidere");
        yrkesklassifisering.put("73", "Presisjonsarbeidere, kunsthÂndverkere, grafiske arbeidere mv.");
        yrkesklassifisering.put("74", "Elektrikere, elektronikere mv.");
        yrkesklassifisering.put("75", "Andre hÂndverkspregede yrker");
        yrkesklassifisering.put("81", "Prosess- og maskinoperat¯rer");
        yrkesklassifisering.put("82", "Mont¯rer");
        yrkesklassifisering.put("83", "Transportarbeidere og operat¯rer av mobile maskiner mv.");
        yrkesklassifisering.put("91", "Renholdere mv.");
        yrkesklassifisering.put("92", "Hjelpearbeidere i jordbruk, skogbruk og fiske");
        yrkesklassifisering.put("93", "Hjelpearbeidere i bergverk, industri, bygg og anlegg og transport");
        yrkesklassifisering.put("94", "Kj¯kkenassistenter");
        yrkesklassifisering.put("95", "Reklamedistribut¯rer mv.");
        yrkesklassifisering.put("96", "Renovasjons- og gjenvinningsarbeidere mv.");
        yrkesklassifisering.put("000", "Uoppgitt / yrker som ikke kan identifiseres");
        yrkesklassifisering.put("011", "Offiserer fra fenrik og h¯yere grad");
        yrkesklassifisering.put("021", "Befal med sersjant grad");
        yrkesklassifisering.put("031", "Menige");
        yrkesklassifisering.put("111", "Politikere og toppledere i offentlig administrasjon");
        yrkesklassifisering.put("112", "Administrerende direkt¯rer");
        yrkesklassifisering.put("121", "Ledere av administrative enheter");
        yrkesklassifisering.put("122", "Ledere av salgs-, PR- og forskningsenheter");
        yrkesklassifisering.put("131", "Ledere i gartnerier, akvakultur mv.");
        yrkesklassifisering.put("132", "Ledere av produksjon, utvinning, bygg og anlegg, transport");
        yrkesklassifisering.put("133", "Ledere av IKT-enheter");
        yrkesklassifisering.put("134", "Ledere av utdanning, helse- og sosialtjenester");
        yrkesklassifisering.put("141", "Ledere i hotell og restaurant");
        yrkesklassifisering.put("142", "Varehandelssjefer");
        yrkesklassifisering.put("143", "Daglige ledere, andre tjenesteytende virksomheter");
        yrkesklassifisering.put("211", "Fysikere, kjemikere mv.");
        yrkesklassifisering.put("212", "Matematikere, statistikere mv.");
        yrkesklassifisering.put("213", "Biologiske yrker mv.");
        yrkesklassifisering.put("214", "Sivilingeni¯rer (unntatt elektroteknologi)");
        yrkesklassifisering.put("215", "Sivilingeni¯rer elektroteknologi");
        yrkesklassifisering.put("216", "Arkitekter, designere mv.");
        yrkesklassifisering.put("221", "Leger");
        yrkesklassifisering.put("222", "Sykepleiere og spesialsykepleiere");
        yrkesklassifisering.put("225", "VeterinÊrer");
        yrkesklassifisering.put("226", "Andre medisinske yrker");
        yrkesklassifisering.put("231", "Universitets- og h¯yskolelektorer/-lÊrere");
        yrkesklassifisering.put("232", "YrkesfaglÊrere");
        yrkesklassifisering.put("233", "Lektorer mv (videregÂende skole)");
        yrkesklassifisering.put("234", "Grunnskole- og f¯rskole-/barnehagelÊrere");
        yrkesklassifisering.put("235", "Andre lÊrere");
        yrkesklassifisering.put("241", "FinansrÂdgivere");
        yrkesklassifisering.put("242", "AdministrasjonsrÂdgivere");
        yrkesklassifisering.put("243", "RÂdgivere innen salg, markedsf¯ring mv.");
        yrkesklassifisering.put("251", "Programvare- og applikasjonsutviklere/analytikere");
        yrkesklassifisering.put("252", "Databasedesignere, systemadministratorer mv.");
        yrkesklassifisering.put("261", "Juridiske yrker");
        yrkesklassifisering.put("262", "Bibliotekarer, arkivarer mv.");
        yrkesklassifisering.put("263", "Samfunnsvitenskapelige, humanistiske og religi¯se yrker");
        yrkesklassifisering.put("264", "Forfattere, journalister mv.");
        yrkesklassifisering.put("265", "Profesjonelle kunstnere");
        yrkesklassifisering.put("311", "Ingeni¯rer");
        yrkesklassifisering.put("312", "Arbeidsledere innen bergfag, industri, bygg og anlegg");
        yrkesklassifisering.put("313", "Prosesskontroll¯rer");
        yrkesklassifisering.put("314", "Bioteknikere mv.");
        yrkesklassifisering.put("315", "Skipoffiserer, flygere, flygeledere mv.");
        yrkesklassifisering.put("321", "Radiografer, proteseteknikere, reseptarer mv.");
        yrkesklassifisering.put("323", "Yrker innen alternativ medisin");
        yrkesklassifisering.put("324", "Dyrepleiere");
        yrkesklassifisering.put("325", "Andre helseyrker");
        yrkesklassifisering.put("331", "Yrker innen finanstjenester");
        yrkesklassifisering.put("332", "Agenter og meglere");
        yrkesklassifisering.put("333", "Forretningstjenesteyrker");
        yrkesklassifisering.put("334", "SekretÊrer og arbeidsledere for kontorpersonell");
        yrkesklassifisering.put("335", "Yrker innen offentlig forvaltning");
        yrkesklassifisering.put("341", "Yrker innen sosialarbeid og kultur");
        yrkesklassifisering.put("342", "Yrker innen sport og idrett");
        yrkesklassifisering.put("343", "Yrker innen estetiske fag");
        yrkesklassifisering.put("351", "Operat¯rer og brukerst¯tte, IKT");
        yrkesklassifisering.put("352", "Teknikere innen kringkasting og telekom");
        yrkesklassifisering.put("411", "Kontormedarbeidere");
        yrkesklassifisering.put("413", "Dataregistrere og stenografer");
        yrkesklassifisering.put("421", "Kundebehandlere, penger og pengespill");
        yrkesklassifisering.put("422", "ReisebyrÂ-, resepsjons- og andre opplysningsmedarbeidere");
        yrkesklassifisering.put("431", "Regnskaps- og l¯nnsmedarbeidere mv.");
        yrkesklassifisering.put("432", "Lager- og transportmedarbeidere");
        yrkesklassifisering.put("441", "Postbud, arkiv- og personalkontor-medarbeidere");
        yrkesklassifisering.put("511", "Persontransportpersonell");
        yrkesklassifisering.put("512", "Kokker");
        yrkesklassifisering.put("513", "Servit¯rer og bartendere");
        yrkesklassifisering.put("514", "Fris¯rer, kosmetologer mv.");
        yrkesklassifisering.put("515", "Renholdsledere og vaktmestre");
        yrkesklassifisering.put("516", "Andre yrker innen personlig tjenesteyting");
        yrkesklassifisering.put("521", "Torg og markedsselgere");
        yrkesklassifisering.put("522", "Butikkselgere");
        yrkesklassifisering.put("523", "Billettselgere");
        yrkesklassifisering.put("524", "Andre salgsyrker");
        yrkesklassifisering.put("531", "Barnehage- og skoleassistenter mv.");
        yrkesklassifisering.put("532", "Pleiemedarbeidere");
        yrkesklassifisering.put("541", "Sikkerhetsarbeidere");
        yrkesklassifisering.put("611", "Korn-, gr¯nnsaks-, frukt- og bÊrprodusenter, gartnere");
        yrkesklassifisering.put("612", "Husdyr-, egg- og melkeprodusenter");
        yrkesklassifisering.put("613", "Plante- og husdyrprodusenter (kombinasjonsbruk)");
        yrkesklassifisering.put("621", "Skogbrukere");
        yrkesklassifisering.put("622", "Havbruksarbeidere og fiskere");
        yrkesklassifisering.put("711", "Bygningsarbeidere");
        yrkesklassifisering.put("712", "Bygningstekniske arbeidere");
        yrkesklassifisering.put("713", "Malere, overflatebehandlere, feiere mv.");
        yrkesklassifisering.put("721", "St¯pere, sveisere, platearbeidere mv.");
        yrkesklassifisering.put("722", "Smeder, verkt¯ymakere mv.");
        yrkesklassifisering.put("723", "Mekanikere og reparat¯rer");
        yrkesklassifisering.put("731", "Presisjonsarbeidere og kunsthÂndverkere");
        yrkesklassifisering.put("732", "Grafiske arbeidere");
        yrkesklassifisering.put("741", "Elektrikere mv.");
        yrkesklassifisering.put("742", "Serviceelektronikere og tele- og IKT-installat¯rer mv.");
        yrkesklassifisering.put("751", "Slaktere, fiskehandlere, konditorer mv.");
        yrkesklassifisering.put("752", "M¯belsnekkere");
        yrkesklassifisering.put("753", "Skreddere, m¯beltapetserere mv.");
        yrkesklassifisering.put("754", "Yrkesdykkere, skytebaser mv.");
        yrkesklassifisering.put("811", "Operat¯rer innen borefag mv.");
        yrkesklassifisering.put("812", "Operat¯rer metallproduksjon");
        yrkesklassifisering.put("813", "Operat¯rer innen produksjon av kjemiske produkter");
        yrkesklassifisering.put("814", "Operat¯rer innen gummi, plast og papirproduksjon");
        yrkesklassifisering.put("815", "Operat¯rer innen bearbeiding og produksjon av tekstiler, pels, skinn og lÊr");
        yrkesklassifisering.put("816", "Operat¯rer innen nÊringsmiddelproduksjon");
        yrkesklassifisering.put("817", "Operat¯rer innen treforedling og trelast");
        yrkesklassifisering.put("818", "Operat¯rer av andre stasjonÊre maskiner");
        yrkesklassifisering.put("821", "Mont¯rer");
        yrkesklassifisering.put("831", "Lokomotiv og T-banef¯rere mv.");
        yrkesklassifisering.put("832", "Bil-, drosje- og varebilf¯rere");
        yrkesklassifisering.put("833", "Lastebil-, buss- og trikkef¯rere");
        yrkesklassifisering.put("834", "Operat¯rer av mobile maskiner mv.");
        yrkesklassifisering.put("835", "Dekks- og maskinmannskap (skip)");
        yrkesklassifisering.put("911", "Renholdere");
        yrkesklassifisering.put("912", "Bilvaskere, vinduspussere mv.");
        yrkesklassifisering.put("921", "Hjelpearbeidere i jordbruk, skogbruk og fiske");
        yrkesklassifisering.put("931", "Hjelpearbeidere i bergverk, bygg og anlegg");
        yrkesklassifisering.put("932", "Hjelpearbeidere i industri");
        yrkesklassifisering.put("933", "Hjelpearbeidere innen transport og lager");
        yrkesklassifisering.put("941", "Kj¯kkenassistenter");
        yrkesklassifisering.put("951", "Reklamedistribut¯rer mv.");
        yrkesklassifisering.put("961", "Renovasjons- og gjenvinningsarbeidere");
        yrkesklassifisering.put("962", "Andre hjelpearbeidere");
        yrkesklassifisering.put("0000", "Uoppgitt / yrker som ikke kan identifiseres");
        yrkesklassifisering.put("0110", "Offiserer fra fenrik og h¯yere grad");
        yrkesklassifisering.put("0210", "Befal med sersjant grad");
        yrkesklassifisering.put("0310", "Menige");
        yrkesklassifisering.put("1111", "Politikere");
        yrkesklassifisering.put("1112", "Toppledere i offentlig administrasjon");
        yrkesklassifisering.put("1114", "Toppledere i interesseorganisasjoner");
        yrkesklassifisering.put("1120", "Administrerende direkt¯rer");
        yrkesklassifisering.put("1211", "Finans- og ¯konomisjefer");
        yrkesklassifisering.put("1212", "Personalsjefer");
        yrkesklassifisering.put("1213", "Strategi- og planleggingssjefer");
        yrkesklassifisering.put("1219", "Andre administrative ledere");
        yrkesklassifisering.put("1221", "Salgs- og markedssjefer");
        yrkesklassifisering.put("1222", "PR- og informasjonssjefer");
        yrkesklassifisering.put("1223", "Forsknings- og utviklingsledere");
        yrkesklassifisering.put("1311", "Ledere i skogbruk, gartnerier mv.");
        yrkesklassifisering.put("1312", "Ledere innen akvakultur mv.");
        yrkesklassifisering.put("1321", "Ledere av industriproduksjon mv.");
        yrkesklassifisering.put("1322", "Ledere av olje- og gassutvinning mv.");
        yrkesklassifisering.put("1323", "Ledere av bygge- og anleggsvirksomhet");
        yrkesklassifisering.put("1324", "Ledere av logistikk og transport mv.");
        yrkesklassifisering.put("1330", "Ledere av IKT-enheter");
        yrkesklassifisering.put("1341", "Ledere av omsorgstjenester for barn");
        yrkesklassifisering.put("1342", "Ledere av helsetjenester");
        yrkesklassifisering.put("1343", "Ledere av eldreomsorg");
        yrkesklassifisering.put("1344", "Ledere av sosialomsorg");
        yrkesklassifisering.put("1345", "Ledere av utdanning og undervisning");
        yrkesklassifisering.put("1346", "Ledere av forsikring og finansvirksomhet");
        yrkesklassifisering.put("1349", "Andre ledere av produksjon og tjenesteyting");
        yrkesklassifisering.put("1411", "Hotellsjefer");
        yrkesklassifisering.put("1412", "Restaurantsjefer");
        yrkesklassifisering.put("1420", "Varehandelssjefer");
        yrkesklassifisering.put("1431", "Sports-, rekreasjons- og kultursenterledere");
        yrkesklassifisering.put("1439", "Andre daglige ledere i tjenesteytende virksomheter");
        yrkesklassifisering.put("2111", "Fysikere og astronomer");
        yrkesklassifisering.put("2112", "Meteorologer");
        yrkesklassifisering.put("2113", "Kjemikere");
        yrkesklassifisering.put("2114", "Geologer og geofysikere");
        yrkesklassifisering.put("2120", "Matematikere, statistikere mv.");
        yrkesklassifisering.put("2131", "Biologer, botanikere, zoologer mv.");
        yrkesklassifisering.put("2132", "Sivilagronomer mv.");
        yrkesklassifisering.put("2133", "Milj¯vernrÂdgivere");
        yrkesklassifisering.put("2141", "Sivilingeni¯rer (industri og produksjon)");
        yrkesklassifisering.put("2142", "Sivilingeni¯rer (bygg og anlegg)");
        yrkesklassifisering.put("2143", "Sivilingeni¯rer (milj¯teknikk)");
        yrkesklassifisering.put("2144", "Sivilingeni¯rer (maskin- og marin-teknikk)");
        yrkesklassifisering.put("2145", "Sivilingeni¯rer (kjemi)");
        yrkesklassifisering.put("2146", "Sivilingeni¯rer (geofag, petro-leumsteknologi, metallurgi mv.)");
        yrkesklassifisering.put("2149", "Andre sivilingeni¯rer (unntatt elektroteknologi)");
        yrkesklassifisering.put("2151", "Sivilingeni¯rer (elkraftteknikk)");
        yrkesklassifisering.put("2152", "Sivilingeni¯rer (elektronikk)");
        yrkesklassifisering.put("2153", "Sivilingeni¯rer (telekommunikasjon)");
        yrkesklassifisering.put("2161", "Sivilarkitekter");
        yrkesklassifisering.put("2162", "Landskapsarkitekter");
        yrkesklassifisering.put("2163", "Produkt- og klesdesignere");
        yrkesklassifisering.put("2164", "Arealplanleggere");
        yrkesklassifisering.put("2165", "LandmÂlere, kartografer mv.");
        yrkesklassifisering.put("2166", "Grafiske- og multimediadesignere");
        yrkesklassifisering.put("2211", "Allmennpraktiserende leger");
        yrkesklassifisering.put("2212", "Legespesialister");
        yrkesklassifisering.put("2221", "Spesialsykepleiere");
        yrkesklassifisering.put("2222", "Jordm¯dre");
        yrkesklassifisering.put("2223", "Sykepleiere");
        yrkesklassifisering.put("2224", "Vernepleiere");
        yrkesklassifisering.put("2250", "VeterinÊrer");
        yrkesklassifisering.put("2261", "Tannleger");
        yrkesklassifisering.put("2262", "Farmas¯yter");
        yrkesklassifisering.put("2263", "Helse- og milj¯rÂdgivere");
        yrkesklassifisering.put("2264", "Fysioterapeuter");
        yrkesklassifisering.put("2265", "ErnÊringsfysiologer");
        yrkesklassifisering.put("2266", "Audiografer og logopeder");
        yrkesklassifisering.put("2267", "Ergoterapeuter");
        yrkesklassifisering.put("2269", "Kiropraktorer mv.");
        yrkesklassifisering.put("2310", "Universitets- og h¯yskolelektorer/-lÊrere");
        yrkesklassifisering.put("2320", "YrkesfaglÊrere");
        yrkesklassifisering.put("2330", "Lektorer mv. (videregÂende skole)");
        yrkesklassifisering.put("2341", "GrunnskolelÊrere");
        yrkesklassifisering.put("2342", "F¯rskole-/barnehagelÊrere");
        yrkesklassifisering.put("2351", "Spesialister i pedagogikk");
        yrkesklassifisering.put("2352", "SpesiallÊrere / spesialpedagoger");
        yrkesklassifisering.put("2353", "Andre sprÂklÊrere");
        yrkesklassifisering.put("2354", "Andre musikklÊrere");
        yrkesklassifisering.put("2355", "Andre lÊrere i estetiske fag");
        yrkesklassifisering.put("2356", "Andre IKT-lÊrere");
        yrkesklassifisering.put("2359", "Andre lÊrere");
        yrkesklassifisering.put("2411", "Revisorer, regnskapsrÂdgivere");
        yrkesklassifisering.put("2412", "Finans- og investeringsrÂdgivere");
        yrkesklassifisering.put("2413", "Finansanalytikere");
        yrkesklassifisering.put("2421", "OrganisasjonsrÂdgivere mv.");
        yrkesklassifisering.put("2422", "H¯yere saksbehandlere i offentlig og privat virksomhet");
        yrkesklassifisering.put("2423", "Personal- og karriererÂdgivere");
        yrkesklassifisering.put("2424", "RÂdgivere innen kompetanseutvikling");
        yrkesklassifisering.put("2431", "Reklame- og markedsf¯ringsrÂdgivere");
        yrkesklassifisering.put("2432", "InformasjonsrÂdgivere");
        yrkesklassifisering.put("2433", "Salgskonsulenter innen tekniske og medisinske produkter");
        yrkesklassifisering.put("2434", "Salgskonsulenter innen IKT-produkter");
        yrkesklassifisering.put("2511", "Systemanalytikere/-arkitekter");
        yrkesklassifisering.put("2512", "Programvareutviklere");
        yrkesklassifisering.put("2513", "Nett- og multimediautviklere");
        yrkesklassifisering.put("2514", "Applikasjonsprogrammerere");
        yrkesklassifisering.put("2519", "Andre programvare- og applikasjonsutviklere");
        yrkesklassifisering.put("2521", "Databasedesignere og -administratorer");
        yrkesklassifisering.put("2522", "Systemadministratorer");
        yrkesklassifisering.put("2523", "Nettverksansvarlige");
        yrkesklassifisering.put("2529", "Sikkerhetsanalytikere mv.");
        yrkesklassifisering.put("2611", "Jurister og advokater");
        yrkesklassifisering.put("2612", "Dommere");
        yrkesklassifisering.put("2619", "Andre juridiske yrker");
        yrkesklassifisering.put("2621", "Arkivarer og kuratorer");
        yrkesklassifisering.put("2622", "Bibliotekarer og andre informasjonsarbeidere");
        yrkesklassifisering.put("2631", "RÂdgivere/forskere, samfunns¯konomi");
        yrkesklassifisering.put("2632", "RÂdgivere/forskere, samfunnsvitenskap");
        yrkesklassifisering.put("2633", "RÂdgivere/forskere, humanistiske fag");
        yrkesklassifisering.put("2634", "Psykologer");
        yrkesklassifisering.put("2635", "RÂdgivere innen sosiale fagfelt");
        yrkesklassifisering.put("2636", "Geistlige yrker");
        yrkesklassifisering.put("2641", "Forfattere mv.");
        yrkesklassifisering.put("2642", "Journalister");
        yrkesklassifisering.put("2643", "Oversettere, tolker mv.");
        yrkesklassifisering.put("2651", "Skulpt¯rer, kunstmalere og andre billedkunstnere");
        yrkesklassifisering.put("2652", "Dirigenter, komponister, musikere og sangere");
        yrkesklassifisering.put("2653", "Koreografer og dansere");
        yrkesklassifisering.put("2654", "Regiss¯rer");
        yrkesklassifisering.put("2655", "Skuespillere");
        yrkesklassifisering.put("2656", "Programledere i TV og radio");
        yrkesklassifisering.put("2659", "Andre ut¯vende kunstneriske yrker");
        yrkesklassifisering.put("3112", "Bygningsingeni¯rer");
        yrkesklassifisering.put("3113", "Elkraftingeni¯rer");
        yrkesklassifisering.put("3114", "Elektronikkingeni¯rer");
        yrkesklassifisering.put("3115", "Maskiningeni¯rer");
        yrkesklassifisering.put("3116", "Kjemiingeni¯rer");
        yrkesklassifisering.put("3117", "Ingeni¯rer innen petroleum, bergverk og metallurgi");
        yrkesklassifisering.put("3118", "Tekniske tegnere");
        yrkesklassifisering.put("3119", "Andre ingeni¯rer");
        yrkesklassifisering.put("3121", "Arbeidsleder, bergfag");
        yrkesklassifisering.put("3122", "Arbeidsleder, industri");
        yrkesklassifisering.put("3123", "Arbeidsleder, bygg og anlegg");
        yrkesklassifisering.put("3131", "Energikontrolloperat¯rer");
        yrkesklassifisering.put("3132", "Kontrolloperat¯rer ved forbrennings- kj¯le- og vannrenseanlegg mv.");
        yrkesklassifisering.put("3133", "Kontrolloperat¯rer innen kjemisk prosessindustri");
        yrkesklassifisering.put("3134", "Kontrolloperat¯rer ved olje- og naturgassraffineringsanlegg");
        yrkesklassifisering.put("3135", "Kontrolloperat¯rer innen metallproduksjon");
        yrkesklassifisering.put("3139", "Andre prosesskontrolloperat¯rer");
        yrkesklassifisering.put("3141", "Bioteknikere (ikke-medisinske laboratorier)");
        yrkesklassifisering.put("3142", "Agroteknikere");
        yrkesklassifisering.put("3143", "Skogteknikere");
        yrkesklassifisering.put("3151", "Skipsmaskinister");
        yrkesklassifisering.put("3152", "Dekksoffiserer og loser");
        yrkesklassifisering.put("3153", "Flygere");
        yrkesklassifisering.put("3154", "Flygeledere");
        yrkesklassifisering.put("3155", "Teknikere innen luftfartssikkerhet");
        yrkesklassifisering.put("3211", "Radiografer mv.");
        yrkesklassifisering.put("3212", "Bioingeni¯rer");
        yrkesklassifisering.put("3213", "Reseptarer");
        yrkesklassifisering.put("3214", "Protese- og tannteknikere");
        yrkesklassifisering.put("3230", "Yrker innen alternativ medisin");
        yrkesklassifisering.put("3240", "Dyrepleiere");
        yrkesklassifisering.put("3251", "Tannpleiere");
        yrkesklassifisering.put("3254", "Optikere");
        yrkesklassifisering.put("3256", "HelsesekretÊrer");
        yrkesklassifisering.put("3257", "Helse- og milj¯kontroll¯rer");
        yrkesklassifisering.put("3258", "Ambulansepersonell");
        yrkesklassifisering.put("3259", "Andre helseyrker");
        yrkesklassifisering.put("3311", "Finansmeglere");
        yrkesklassifisering.put("3312", "Kundebehandlere lÂn og kreditt");
        yrkesklassifisering.put("3313", "Regnskapsf¯rere");
        yrkesklassifisering.put("3315", "Takstmenn");
        yrkesklassifisering.put("3321", "Forsikringsagenter");
        yrkesklassifisering.put("3322", "Selgere (engros)");
        yrkesklassifisering.put("3323", "Innkj¯pere");
        yrkesklassifisering.put("3324", "Handels- og skipsmeglere");
        yrkesklassifisering.put("3331", "Spedit¯rer og befraktere");
        yrkesklassifisering.put("3332", "Konferanse- og arrangementsplanleggere mv.");
        yrkesklassifisering.put("3333", "Arbeidsformidlere");
        yrkesklassifisering.put("3334", "Eiendomsmeglere og - forvaltere");
        yrkesklassifisering.put("3339", "Andre yrker innen forretningstjenester");
        yrkesklassifisering.put("3341", "Arbeidsledere for kontorpersonell");
        yrkesklassifisering.put("3342", "AdvokatsekretÊr");
        yrkesklassifisering.put("3343", "SjefssekretÊrer");
        yrkesklassifisering.put("3351", "Tollere");
        yrkesklassifisering.put("3352", "SkattefunksjonÊrer");
        yrkesklassifisering.put("3353", "Saksbehandlere innen sosiale ytelser");
        yrkesklassifisering.put("3354", "Saksbehandlere for f¯rerkort, importlisenser mv.");
        yrkesklassifisering.put("3355", "Politibetjenter mv.");
        yrkesklassifisering.put("3359", "Andre yrker innen offentlig forvaltning");
        yrkesklassifisering.put("3411", "Privatetterforskere mv.");
        yrkesklassifisering.put("3412", "Milj¯arbeidere innen sosiale fagfelt");
        yrkesklassifisering.put("3413", "Religi¯se yrker");
        yrkesklassifisering.put("3421", "Idrettsut¯vere");
        yrkesklassifisering.put("3422", "Trenere og idrettsdommere");
        yrkesklassifisering.put("3423", "Sports- og aktivitetsinstrukt¯rer");
        yrkesklassifisering.put("3431", "Fotografer og filmfotografer");
        yrkesklassifisering.put("3432", "Interi¯rdesignere og dekorat¯rer");
        yrkesklassifisering.put("3433", "Tekniske konservatorer");
        yrkesklassifisering.put("3434", "Sjefskokker");
        yrkesklassifisering.put("3439", "Andre yrker innen estetiske fag");
        yrkesklassifisering.put("3511", "Driftsteknikere, IKT");
        yrkesklassifisering.put("3512", "Brukerst¯tte, IKT");
        yrkesklassifisering.put("3513", "Nettverks- og systemteknikere, IKT");
        yrkesklassifisering.put("3514", "Internett-teknikere");
        yrkesklassifisering.put("3521", "Teknikere innen radio og tv");
        yrkesklassifisering.put("3522", "Teknikere innen telekom");
        yrkesklassifisering.put("4110", "Kontormedarbeidere");
        yrkesklassifisering.put("4131", "Stenografer mv.");
        yrkesklassifisering.put("4132", "Dataregistrere");
        yrkesklassifisering.put("4211", "Kundebehandlere, bank og postkontor");
        yrkesklassifisering.put("4212", "Bingoverter, bookmakere mv.");
        yrkesklassifisering.put("4213", "PantelÂnere mv.");
        yrkesklassifisering.put("4214", "Inkassomedarbeidere mv.");
        yrkesklassifisering.put("4221", "ReisebyrÂmedarbeidere mv.");
        yrkesklassifisering.put("4222", "Kundesentermedarbeidere");
        yrkesklassifisering.put("4223", "Sentralbordoperat¯rer");
        yrkesklassifisering.put("4224", "Hotellresepsjonister");
        yrkesklassifisering.put("4225", "Informasjonsskrankemedarbeidere");
        yrkesklassifisering.put("4226", "Resepsjonister (ekskl. hotell)");
        yrkesklassifisering.put("4227", "Intervjuere");
        yrkesklassifisering.put("4229", "Andre opplysningsmedarbeidere");
        yrkesklassifisering.put("4311", "Regnskapsmedarbeidere");
        yrkesklassifisering.put("4312", "Forsikrings- og finansmedarbeidere");
        yrkesklassifisering.put("4313", "L¯nningsmedarbeidere");
        yrkesklassifisering.put("4321", "Lagermedarbeidere og material-forvaltere");
        yrkesklassifisering.put("4322", "Logistikkmedarbeidere");
        yrkesklassifisering.put("4323", "TransportfunksjonÊrer");
        yrkesklassifisering.put("4411", "Bibliotekassistenter");
        yrkesklassifisering.put("4412", "Postbud og postsorterere");
        yrkesklassifisering.put("4413", "Kodere mv.");
        yrkesklassifisering.put("4415", "Arkivassistenter");
        yrkesklassifisering.put("4416", "Personalkontormedarbeidere");
        yrkesklassifisering.put("5111", "Flyverter, bÂtverter mv.");
        yrkesklassifisering.put("5112", "Kondukt¯rer");
        yrkesklassifisering.put("5113", "Reiseledere og guider");
        yrkesklassifisering.put("5120", "Kokker");
        yrkesklassifisering.put("5131", "Servit¯rer");
        yrkesklassifisering.put("5132", "Bartendere");
        yrkesklassifisering.put("5141", "Fris¯rer");
        yrkesklassifisering.put("5142", "Kosmetologer mv.");
        yrkesklassifisering.put("5151", "Renholdsledere i virksomheter");
        yrkesklassifisering.put("5152", "Husholdere");
        yrkesklassifisering.put("5153", "Vaktmestre");
        yrkesklassifisering.put("5161", "Astrologer mv.");
        yrkesklassifisering.put("5163", "BegravelsesbyrÂ- og krematoriearbeidere");
        yrkesklassifisering.put("5164", "Dyrepassere og - trenere mv.");
        yrkesklassifisering.put("5165", "Kj¯reskolelÊrere");
        yrkesklassifisering.put("5169", "Andre personlige tjenesteytere");
        yrkesklassifisering.put("5211", "Torghandlere");
        yrkesklassifisering.put("5212", "Gateselgere, mat");
        yrkesklassifisering.put("5221", "Innehavere av kiosk/liten butikk");
        yrkesklassifisering.put("5222", "Butikkavdelingssjefer");
        yrkesklassifisering.put("5223", "Butikkmedarbeidere");
        yrkesklassifisering.put("5230", "Billettselgere");
        yrkesklassifisering.put("5241", "Mannekenger og modeller");
        yrkesklassifisering.put("5242", "Demonstrasjonsselgere");
        yrkesklassifisering.put("5243", "D¯rselgere");
        yrkesklassifisering.put("5244", "Telefon- og nettselgere");
        yrkesklassifisering.put("5245", "Servicemedarbeidere (bensinstasjon)");
        yrkesklassifisering.put("5246", "Gatekj¯kken- og kafÈmedarbeidere mv.");
        yrkesklassifisering.put("5249", "Andre salgsmedarbeidere");
        yrkesklassifisering.put("5311", "Barnehage- og skolefritidsassistenter mv.");
        yrkesklassifisering.put("5312", "Skoleassistenter");
        yrkesklassifisering.put("5321", "Helsefagarbeidere");
        yrkesklassifisering.put("5322", "Hjemmehjelper");
        yrkesklassifisering.put("5329", "Andre pleiemedarbeidere");
        yrkesklassifisering.put("5411", "Brannkonstabler");
        yrkesklassifisering.put("5413", "Fengselsbetjenter");
        yrkesklassifisering.put("5414", "Vektere");
        yrkesklassifisering.put("5419", "Andre sikkerhetsarbeidere");
        yrkesklassifisering.put("6111", "Korn- og gr¯nnsaksprodusenter");
        yrkesklassifisering.put("6112", "Frukt- og bÊrprodusenter");
        yrkesklassifisering.put("6113", "Gartnere");
        yrkesklassifisering.put("6114", "Kombinasjonsbrukere, nyttevekster");
        yrkesklassifisering.put("6121", "Melke- og husdyrprodusenter");
        yrkesklassifisering.put("6122", "Egg- og fjÊrfeprodusenter");
        yrkesklassifisering.put("6123", "Bir¯ktere mv.");
        yrkesklassifisering.put("6129", "Andre dyreoppdrettere og r¯ktere");
        yrkesklassifisering.put("6130", "Plante- og husdyrprodusenter (kombinasjonsbruk)");
        yrkesklassifisering.put("6210", "Skogbrukere");
        yrkesklassifisering.put("6221", "Havbruksarbeidere");
        yrkesklassifisering.put("6222", "Fiskere");
        yrkesklassifisering.put("6224", "Fangstfolk");
        yrkesklassifisering.put("7112", "Murere");
        yrkesklassifisering.put("7113", "Steinhoggere mv.");
        yrkesklassifisering.put("7114", "Betongarbeidere");
        yrkesklassifisering.put("7115", "T¯mrere og snekkere");
        yrkesklassifisering.put("7119", "Andre bygningsarbeidere");
        yrkesklassifisering.put("7121", "Taktekkere");
        yrkesklassifisering.put("7122", "Gulv- og flisleggere");
        yrkesklassifisering.put("7123", "Gips- og sparklingsarbeidere");
        yrkesklassifisering.put("7124", "Isolat¯rer mv.");
        yrkesklassifisering.put("7125", "Glassarbeidere");
        yrkesklassifisering.put("7126", "R¯rleggere og VVS-mont¯rer");
        yrkesklassifisering.put("7127", "Kuldemont¯rer mv.");
        yrkesklassifisering.put("7131", "Malere og byggtapetserere");
        yrkesklassifisering.put("7132", "Overflatebehandlere og lakkerere");
        yrkesklassifisering.put("7133", "Feiere, fasaderenholdere mv.");
        yrkesklassifisering.put("7211", "St¯pere");
        yrkesklassifisering.put("7212", "Sveisere");
        yrkesklassifisering.put("7213", "Kopper- og blikkenslagere");
        yrkesklassifisering.put("7214", "Platearbeidere");
        yrkesklassifisering.put("7215", "Riggere og spleisere");
        yrkesklassifisering.put("7221", "Smeder");
        yrkesklassifisering.put("7222", "Verkt¯ymaker, lÂsesmeder mv.");
        yrkesklassifisering.put("7223", "Metalldreiere mv.");
        yrkesklassifisering.put("7224", "Metallslipere");
        yrkesklassifisering.put("7231", "Bilmekanikere");
        yrkesklassifisering.put("7232", "Mekanikere innen flytekniske fag");
        yrkesklassifisering.put("7233", "Anleggsmaskin- og industrimekanikere");
        yrkesklassifisering.put("7234", "Sykkelreparat¯rer mv.");
        yrkesklassifisering.put("7311", "Presisjonsinstrumentmakere og -reparat¯rer");
        yrkesklassifisering.put("7312", "Musikkinstrumentmakere og -stemmere");
        yrkesklassifisering.put("7313", "Gull- og s¯lvsmeder, grav¯rer mv.");
        yrkesklassifisering.put("7314", "Keramikere mv.");
        yrkesklassifisering.put("7315", "GlasshÂndverkere");
        yrkesklassifisering.put("7316", "Dekormalere mv.");
        yrkesklassifisering.put("7317", "KunsthÂndverkere i tre mv.");
        yrkesklassifisering.put("7318", "Vevere, strikkere mv. (innen husflidsproduksjon)");
        yrkesklassifisering.put("7319", "Andre kunsthÂndverkere");
        yrkesklassifisering.put("7321", "F¯rtrykkere");
        yrkesklassifisering.put("7322", "Trykkere");
        yrkesklassifisering.put("7323", "Innbindere mv.");
        yrkesklassifisering.put("7411", "Elektrikere");
        yrkesklassifisering.put("7412", "Automatikere");
        yrkesklassifisering.put("7413", "Energimont¯rer");
        yrkesklassifisering.put("7421", "Serviceelektronikere");
        yrkesklassifisering.put("7422", "Tele- og IKT-installat¯rer");
        yrkesklassifisering.put("7511", "Slaktere, fiskehandlere mv.");
        yrkesklassifisering.put("7512", "Bakere, konditorer mv.");
        yrkesklassifisering.put("7513", "Ystere mv. (gÂrdsproduksjon)");
        yrkesklassifisering.put("7514", "Saftere, syltere mv. (gÂrdsproduksjon)");
        yrkesklassifisering.put("7515", "Pr¯vesmakere og kvalitetsbed¯mmere av mat og drikke");
        yrkesklassifisering.put("7522", "M¯belsnekkere");
        yrkesklassifisering.put("7531", "Skreddere, buntmakere mv.");
        yrkesklassifisering.put("7532", "Grad¯rer");
        yrkesklassifisering.put("7534", "M¯beltapetserere mv.");
        yrkesklassifisering.put("7535", "Skinnberedere og garvere");
        yrkesklassifisering.put("7536", "Skomakere");
        yrkesklassifisering.put("7541", "Yrkesdykkere");
        yrkesklassifisering.put("7542", "Skytebaser og sprengningsarbeidere");
        yrkesklassifisering.put("7543", "Produkttestere (ikke matprodukter)");
        yrkesklassifisering.put("7544", "Desinfeksjonsarbeidere og skadedyrbekjempere");
        yrkesklassifisering.put("7549", "Andre hÂndverkere");
        yrkesklassifisering.put("8111", "Bergfagarbeidere");
        yrkesklassifisering.put("8112", "Prosessoperat¯rer (oppredning)");
        yrkesklassifisering.put("8113", "Operat¯rer innen boring mv.");
        yrkesklassifisering.put("8114", "Operat¯rer innen produksjon av betong mv.");
        yrkesklassifisering.put("8121", "Operat¯rer innen metallurgiske prosessfag");
        yrkesklassifisering.put("8122", "Operat¯rer innen metallflatebehandling");
        yrkesklassifisering.put("8131", "Operat¯rer innen kjemisk industri");
        yrkesklassifisering.put("8132", "Operat¯rer innen produksjon av fotofilm og -papir mv.");
        yrkesklassifisering.put("8141", "Operat¯rer innen produksjon av gummiprodukter");
        yrkesklassifisering.put("8142", "Operat¯rer innen plastprodukter");
        yrkesklassifisering.put("8143", "Operat¯rer innen papirprodukter");
        yrkesklassifisering.put("8151", "Spinne- og n¯stemaskinoperat¯rer");
        yrkesklassifisering.put("8152", "Operat¯rer innen tekstilproduksjon mv.");
        yrkesklassifisering.put("8153", "Industrisyere");
        yrkesklassifisering.put("8154", "Operat¯rer innen tekstilbearbeiding");
        yrkesklassifisering.put("8155", "Operat¯rer innen pels, skinn- og lÊrbearbeiding");
        yrkesklassifisering.put("8156", "Operat¯rer innen skinn og lÊrprodukter");
        yrkesklassifisering.put("8157", "Renseri- og vaskerimaskinoperat¯rer");
        yrkesklassifisering.put("8159", "Andre operat¯rer innen produksjon av tekstiler, pels, skinn og lÊr");
        yrkesklassifisering.put("8160", "Operat¯rer innen nÊringsmiddelproduksjon");
        yrkesklassifisering.put("8171", "Operat¯rer innen treforedling");
        yrkesklassifisering.put("8172", "Operat¯rer innen trelastproduksjon");
        yrkesklassifisering.put("8181", "Operat¯rer innen glass- og keramisk produksjon");
        yrkesklassifisering.put("8182", "Fyrkjele- og turbinoperat¯rer");
        yrkesklassifisering.put("8183", "Pakke-, tappe- og etikettmaskinoperat¯rer");
        yrkesklassifisering.put("8189", "Andre stasjonÊre maskinoperat¯rer");
        yrkesklassifisering.put("8211", "Mont¯rer av mekaniske produkter");
        yrkesklassifisering.put("8212", "Mont¯rer av elektriske og elektroniske produkter");
        yrkesklassifisering.put("8219", "Andre mont¯rer");
        yrkesklassifisering.put("8311", "Lokomotiv og T-banef¯rere");
        yrkesklassifisering.put("8312", "Skiftekondukt¯rer mv");
        yrkesklassifisering.put("8322", "Bil-, drosje- og varebilf¯rere");
        yrkesklassifisering.put("8331", "BussjÂf¯rer og trikkef¯rere");
        yrkesklassifisering.put("8332", "Lastebil- og trailersjÂf¯rer");
        yrkesklassifisering.put("8341", "Jordbruks- og skogbruksmaskinf¯rere");
        yrkesklassifisering.put("8342", "Anleggsmaskinf¯rere");
        yrkesklassifisering.put("8343", "Kran- og heisf¯rere mv.");
        yrkesklassifisering.put("8344", "Truckf¯rere");
        yrkesklassifisering.put("8350", "Dekks- og maskinmannskap (skip)");
        yrkesklassifisering.put("9111", "Renholdere i private hjem");
        yrkesklassifisering.put("9112", "Renholdere i virksomheter");
        yrkesklassifisering.put("9122", "Bilvaskere");
        yrkesklassifisering.put("9123", "Vinduspussere");
        yrkesklassifisering.put("9129", "Andre rengj¯rere");
        yrkesklassifisering.put("9211", "Hjelpearbeidere i nyttevekstproduksjon");
        yrkesklassifisering.put("9212", "Hjelpearbeidere i husdyrproduksjon");
        yrkesklassifisering.put("9213", "Hjelpearbeidere i kombinasjonsbruk");
        yrkesklassifisering.put("9214", "Hjelpearbeidere i gartneri mv.");
        yrkesklassifisering.put("9215", "Hjelpearbeidere i skogbruk");
        yrkesklassifisering.put("9216", "Hjelpearbeidere innen havbruk");
        yrkesklassifisering.put("9311", "Hjelpearbeidere i bergverk");
        yrkesklassifisering.put("9312", "Hjelpearbeidere i anlegg");
        yrkesklassifisering.put("9313", "Hjelpearbeidere i bygg");
        yrkesklassifisering.put("9321", "HÂndpakkere mv.");
        yrkesklassifisering.put("9329", "Andre hjelpearbeidere i industri");
        yrkesklassifisering.put("9331", "F¯rere av ikke-motorisert kj¯ret¯y");
        yrkesklassifisering.put("9333", "Laste- og lossearbeidere");
        yrkesklassifisering.put("9334", "VarepÂfyllere");
        yrkesklassifisering.put("9412", "Kj¯kkenassistenter");
        yrkesklassifisering.put("9510", "Reklamedistribut¯rer mv.");
        yrkesklassifisering.put("9611", "Renovasjonsarbeidere");
        yrkesklassifisering.put("9612", "Gjenvinningsarbeidere");
        yrkesklassifisering.put("9613", "Gatefeiere mv.");
        yrkesklassifisering.put("9621", "Bud mv.");
        yrkesklassifisering.put("9622", "Altmuligmann");
        yrkesklassifisering.put("9623", "MÂleravlesere mv.");
        yrkesklassifisering.put("9629", "Andre hjelpearbeidere");
    }

}