#!/bin/bash

./gradlew build \
 :person-service:build \
 :profil-api:build \
 :faste-data-frontend:build \
 :oversikt-frontend:build \
 :testnorge-inst:build \
 :testnorge-aareg:build \
 :endringsmelding-frontend:build \
 :endringsmelding-service:build \
 :applikasjonsanalyse-frontend:build \
 :adresse-service:build \
 :pdl-forvalter:build \
 :syntrest:build \
 :amelding-service:build \
 :applikasjonsanalyse-service:build \
 :arbeidsforhold-export-api:build \
 :arbeidsforhold-service:build \
 :varslinger-service:build \
 :dolly-frontend-redirect:build \
 :dolly-frontend:build \
 :synt-sykemelding-api:build \
 :import-person-service:build \
 :jenkins-batch-status-service:build \
 :organisasjon-bestilling-service:build \
 :aareg-proxy:build \
 :batch-adeo-proxy:build \
 :ident-pool-proxy:build \
 :saf-proxy:build \
 :dokarkiv-proxy:build \
 :kodeverk-proxy:build \
 :statisk-data-forvalter-proxy:build \
 :skjermingsregister-proxy:build \
 :udistub-proxy:build \
 :syntrest-proxy:build \
 :tps-forvalteren-proxy:build \
 :aareg-synt-services-proxy:build \
 :pdl-proxy:build \
 :samhandlerregisteret-proxy:build \
 :hodejegeren-proxy:build \
 :ereg-proxy:build \
 :inntektstub-proxy:build \
 :brregstub-proxy:build \
 :arena-forvalteren-proxy:build \
 :testnorge-aareg-proxy:build \
 :krrstub-proxy:build \
 :testnorge-inst-proxy:build \
 :sigrunstub-proxy:build \
 :pensjon-testdata-facade-proxy:build \
 :geografiske-kodeverk-service:build \
 :testnorge-inntekt:build