CREATE TABLE ORGANISAJON
(
    ORGNUMMER  VARCHAR(256) PRIMARY KEY,
    ACTIVE     BOOLEAN NOT NULL         DEFAULT TRUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);