ALTER TABLE ORGANISAJON
    RENAME TO ORGANISAJON_TEMP;

CREATE TABLE ORGANISAJON
(
    ID          SERIAL PRIMARY KEY,
    ORGNUMMER   VARCHAR(64) NOT NULL,
    ACTIVE      BOOLEAN     NOT NULL     DEFAULT TRUE,
    ENVIRONMENT VARCHAR(32) NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ORGANISAJON_ENVIRONMENT_UNIQUE UNIQUE (ORGNUMMER, ENVIRONMENT)
);

INSERT INTO ORGANISAJON(ORGNUMMER, ACTIVE, ENVIRONMENT, CREATED_AT, UPDATED_AT)
SELECT ORGNUMMER, ACTIVE, 'q2', CREATED_AT, CURRENT_TIMESTAMP
FROM ORGANISAJON_TEMP;

DROP TABLE ORGANISAJON_TEMP;