apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "localauth"
  namespace: "dolly"
spec:
  image: "europe-north1-docker.pkg.dev/nais-management-233d/nais/localauth:latest"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/internal/healthz"
  readiness:
    path: "/internal/healthz"
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "10m"
      memory: "32Mi"
  ingresses:
    - https://localauth-dolly.intern.dev.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
  env:
    - name: LOCALAUTH_PUBLIC_URL
      value: "https://localauth-dolly.intern.dev.nav.no"