import { test } from '@playwright/test'

import { CypressSelector } from '../../cypress/mocks/Selectors'

test.describe('Åpne bestilt ident med knytning mot alle fagsystem', () => {
	test('passes', async ({ page }) => {
		await page.goto('gruppe')
		await page
			.locator('div')
			.getByText(/Testytest/)
			.first()
			.click()
		page.getByTestId(CypressSelector.TOGGLE_VISNING_BESTILLINGER)
		await page.click()
		await page.waitForTimeout(200)
		page.getByTestId(CypressSelector.BUTTON_OPEN_BESTILLING)
		page.FIXME_each(async (element) => {
			page.FIXME_wrap(element)
			await page.click()
		})
		page.getByTestId(CypressSelector.TOGGLE_VISNING_PERSONER)
		await page.click()
		page.getByTestId(CypressSelector.TOGGLE_PERSON_IBRUK)
		await page.click()
		page.getByTestId(CypressSelector.TOGGLE_PERSON_IBRUK)
		await page.FIXME_should('be.enabled')
		page.getByTestId(CypressSelector.TOGGLE_PERSON_IBRUK)
		await page.click()
		page.getByTestId(CypressSelector.BUTTON_OPEN_IDENT)
		await page.click()
		page.getByTestId(CypressSelector.BUTTON_OPEN_BESTILLINGSDETALJER)
		await page.waitForTimeout(200)
		page.getByTestId(CypressSelector.TITLE_VISNING)
		await page.FIXME_invoke('show')
		await page.click()
		await page.waitForTimeout(1000)
		await page.waitForTimeout(1000)
		page.getByTestId(CypressSelector.BUTTON_OPEN_EXPANDABLE)
		page.FIXME_each(async (element) => {
			page.FIXME_wrap(element)
			await page.FIXME_invoke('show')
			await page.click()
			await page.waitForTimeout(300)
		})
		await page.waitForTimeout(1000)
		await page.waitForTimeout(1000)
		page.getByTestId(CypressSelector.HOVER_MILJOE)
		page.FIXME_each(async (element) => {
			page.FIXME_wrap(element)
			await page.FIXME_invoke('show')
			await page.click()
			await page.waitForTimeout(400)
			page.getByTestId(CypressSelector.TITLE_VISNING)
			await page.FIXME_invoke('show')
			await page.click()
		})
		await toggle_brukt.FIXME_should('be.calledTwice')
	})
})
