package no.nav.dolly.domain.resultset.udistub.model.arbeidsadgang;

public enum UdiArbeidsadgangType {

    BESTEMT_ARBEIDSGIVER_ELLER_OPPDRAGSGIVER, BESTEMT_ARBEID_ELLER_OPPDRAG, BESTEMT_ARBEIDSGIVER_OG_ARBEID_ELLER_BESTEMT_OPPDRAGSGIVER_OG_OPPDRAG, GENERELL, UAVKLART
}
