CREATE TABLE APPLICATION_DEPENDENCY
(
    ID         SERIAL PRIMARY KEY,
    NAMESPACE  VARCHAR(256) NOT NULL,
    NAME       VARCHAR(256) NOT NULL,
    CLUSTER    VARCHAR(64)  NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APPLICATION_INFO
(
    ID         SERIAL PRIMARY KEY,
    NAMESPACE  VARCHAR(256) NOT NULL,
    NAME       VARCHAR(256) NOT NULL,
    CLUSTER    VARCHAR(64)  NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APPLICATION_INFO_DEPENDENCY
(
    ID                        SERIAL PRIMARY KEY,
    APPLICATION_INFO_ID       INTEGER REFERENCES APPLICATION_INFO (ID),
    APPLICATION_DEPENDENCY_ID INTEGER REFERENCES APPLICATION_DEPENDENCY (ID),
    CREATED_AT                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);