CREATE TABLE APPLICATION
(
    SHA          VARCHAR(256) PRIMARY KEY,
    CONTENT      TEXT         NOT NULL,
    NAME         VARCHAR(256) NOT NULL,
    ORGANISATION VARCHAR(256) NOT NULL,
    REPOSITORY   VARCHAR(256) NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);