export const CREATE_GRUPPE_SUCCESS = 'CREATE_GRUPPE_SUCCESS';

export const UPDATE_GRUPPE_SUCCES = 'UPDATE_GRUPPE_SUCCESS';
export const LOAD_GRUPPER_SUCCESS = 'LOAD_GRUPPER_SUCCESS';

export const LOAD_BRUKER_SUCCESS = 'LOAD_BRUKER_SUCCESS';

export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAM_SUCCESS';
