-----------------------------
-- A L T E R   T A B L E S --
-----------------------------
ALTER TABLE T_BESTILLING_PROGRESS MODIFY TPSF_SUCCESS_ENVIRONMENTS VARCHAR2(4000);
ALTER TABLE T_BESTILLING_PROGRESS MODIFY SIGRUN_SUCCESS_ENVIRONMENTS VARCHAR2(4000);
ALTER TABLE T_BESTILLING_PROGRESS MODIFY AAREG_SUCCESS_ENVIRONMENTS VARCHAR2(4000);

