-----------------------------
-- A L T E R   T A B L E S --
-----------------------------
ALTER TABLE T_BESTILLING_PROGRESS ADD KRRSTUB_STATUS VARCHAR2(50);
ALTER TABLE T_BESTILLING_PROGRESS RENAME COLUMN SIGRUN_SUCCESS_ENVIRONMENTS TO SIGRUNSTUB_STATUS;
ALTER TABLE T_BESTILLING_PROGRESS MODIFY SIGRUNSTUB_STATUS VARCHAR2(50);
ALTER TABLE T_BESTILLING_PROGRESS DROP COLUMN AAREG_SUCCESS_ENVIRONMENTS;