-----------------------------
-- A L T E R   T A B L E S --
-----------------------------
ALTER TABLE T_BESTILLING_PROGRESS
    RENAME COLUMN ARENASTUB_STATUS TO ARENAFORVALTER_STATUS;

ALTER TABLE T_BESTILLING_PROGRESS
    MODIFY ARENAFORVALTER_STATUS VARCHAR2(4000);