CREATE TABLE TEAM
(
    ID          SERIAL PRIMARY KEY,
    NAVN        VARCHAR(100) NOT NULL UNIQUE,
    BESKRIVELSE VARCHAR(1000)
);

ALTER TABLE GRUPPE
    ADD COLUMN TEAM_ID BIGINT;
ALTER TABLE GRUPPE
    ADD CONSTRAINT FK_GRUPPE_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID);

CREATE TABLE TEAM_BRUKER
(
    TEAM_ID   BIGINT       NOT NULL,
    BRUKER_ID VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TEAM_BRUKER PRIMARY KEY (TEAM_ID, BRUKER_ID),
    CONSTRAINT FK_TEAM_BRUKER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID),
    CONSTRAINT FK_TEAM_BRUKER_BRUKER FOREIGN KEY (BRUKER_ID) REFERENCES BRUKER (ID)
);