-------------------------------
-- M O D I F Y   T A B L E S --
-------------------------------

CREATE TABLE SOEK
(
    ID           SERIAL PRIMARY KEY,
    SOEK_VERDI   TEXT NOT NULL,
    OPPRETTET    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    BRUKER_ID    INT NOT NULL,
    SOEK_TYPE    VARCHAR(10) NOT NULL,
    CONSTRAINT FK_SOEK_BRUKER_ID FOREIGN KEY (BRUKER_ID) REFERENCES BRUKER (ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SOEK_BRUKER_TYPE ON SOEK (BRUKER_ID, SOEK_TYPE);