-- Check if constraint exists before dropping
DO
$$
    BEGIN
        IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bruker_gjeldende_team') THEN
            ALTER TABLE BRUKER
                DROP CONSTRAINT FK_BRUKER_GJELDENDE_TEAM;
        END IF;
    END
$$;

-- Check if column exists before dropping
DO
$$
    BEGIN
        IF EXISTS (SELECT 1
                   FROM information_schema.columns
                   WHERE table_name = 'bruker'
                     AND column_name = 'gjeldende_team_id') THEN
            ALTER TABLE BRUKER
                DROP COLUMN GJELDENDE_TEAM_ID;
        END IF;
    END
$$;

DROP TABLE IF EXISTS TEAM_BRUKER cascade;
DROP TABLE IF EXISTS TEAM cascade;

CREATE TABLE TEAM
(
    ID           SERIAL PRIMARY KEY,
    NAVN         VARCHAR(100) NOT NULL UNIQUE,
    BESKRIVELSE  VARCHAR(1000),
    OPPRETTET    TIMESTAMP,
    OPPRETTET_AV INT,
    BRUKER_ID    INT,
    CONSTRAINT FK_TEAM_OPPRETTET_AV FOREIGN KEY (OPPRETTET_AV) REFERENCES BRUKER (ID) ON DELETE SET NULL,
    CONSTRAINT FK_TEAM_BRUKER_ID FOREIGN KEY (BRUKER_ID) REFERENCES BRUKER (ID) ON DELETE CASCADE
);

CREATE TABLE TEAM_BRUKER
(
    ID        SERIAL PRIMARY KEY,
    BRUKER_ID INT NOT NULL,
    TEAM_ID   INT NOT NULL,
    OPPRETTET TIMESTAMP,
    CONSTRAINT FK_TEAM_BRUKER_BRUKER FOREIGN KEY (BRUKER_ID) REFERENCES BRUKER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_TEAM_BRUKER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID) ON DELETE CASCADE,
    CONSTRAINT UNIK_BRUKER_TEAM UNIQUE (BRUKER_ID, TEAM_ID)
);

ALTER TABLE BRUKER
    ADD COLUMN REPRESENTERER_TEAM INT,
    ADD CONSTRAINT FK_BRUKER_GJELDENDE_TEAM
        FOREIGN KEY (REPRESENTERER_TEAM)
            REFERENCES TEAM (ID) ON DELETE SET NULL;