-- First, remove the foreign key constraint and column added to BRUKER table
ALTER TABLE BRUKER
    DROP CONSTRAINT FK_BRUKER_GJELDENDE_TEAM;
ALTER TABLE BRUKER
    DROP COLUMN GJELDENDE_TEAM_ID;

-- Next, drop the TEAM_BRUKER table that has foreign keys to both BRUKER and TEAM
DROP TABLE TEAM_BRUKER;

-- Finally, drop the TEAM table
DROP TABLE TEAM;

-- CREATE TABLE TEAM
-- (
--     ID           SERIAL PRIMARY KEY,
--     NAVN         VARCHAR(100) NOT NULL UNIQUE,
--     BESKRIVELSE  VARCHAR(1000),
--     OPPRETTET    TIMESTAMP,
--     OPPRETTET_AV INT,
--     BRUKER_ID INT,
--     CONSTRAINT FK_TEAM_OPPRETTET_AV FOREIGN KEY (OPPRETTET_AV) REFERENCES BRUKER (ID),
--     CONSTRAINT FK_TEAM_BRUKER_ID FOREIGN KEY (BRUKER_ID) REFERENCES BRUKER (ID)
-- );
-- 
-- CREATE TABLE TEAM_BRUKER
-- (
--     ID SERIAL PRIMARY KEY,
--     BRUKER_ID INT NOT NULL,
--     TEAM_ID   INT NOT NULL,
--     OPPRETTET TIMESTAMP,
--     CONSTRAINT FK_TEAM_BRUKER_BRUKER FOREIGN KEY (BRUKER_ID) REFERENCES BRUKER (ID),
--     CONSTRAINT FK_TEAM_BRUKER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID),
--     CONSTRAINT UNIK_BRUKER_TEAM UNIQUE (BRUKER_ID, TEAM_ID)
-- );
-- 
-- ALTER TABLE BRUKER
--     ADD COLUMN GJELDENDE_TEAM_ID INT,
--     ADD CONSTRAINT FK_BRUKER_GJELDENDE_TEAM
--         FOREIGN KEY (GJELDENDE_TEAM_ID)
--             REFERENCES TEAM (ID);