package no.nav.registre.hodejegeren.service;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum Funksjoner {
    FOEDSELSMELDING("01"),
    INNVANDRING("02"),
    NAVNEENDRING_FOERSTE("06"),
    NAVNEENDRING_MELDING("07"),
    NAVNEENDRING_KORREKSJON("10"),
    VIGSEL("11"),
    SEPERASJON("14"),
    SKILSMISSE("18"),
    FLYTTING_INNEN_KOMMUNEN("24"),
    ANNULERING_FLYTTING_ADRESSEENDRING("25"),
    INNFLYTTING_ANNEN_KOMMUNE("26"),
    ADRESSEENDRING_UTEN_FLYTTING("28"),
    ADRESSEKORREKSJON("29"),
    UTVANDRING("32"),
    FARSKAP_MEDMORSKAP("34"),
    ENDRING_STATSBORGERSKAP_BIBEHOLD("35"),
    ENDRING_FAMILIENUMMER("38"),
    FOEDSELSNUMMERKORREKSJON("39"),
    ENDRING_FORELDREANSVAR("40"),
    ENDRING_OPPHOLDSTILLATELSE("41"),
    DOEDSMELDING("43"),
    ENDRING_POSTADRESSE_TILLEGGSADRESSE("44"),
    ENDRING_POSTNUMMER_SKOLE_VALG_GRUNNKRETS("47"),
    KOMMUNEREGULERING("48"),
    ADRESSEENDRING_GAB("49"),
    ENDRING_KORREKSJON_FOEDESTED("51"),
    UREGISTRERT_PERSON("56"),
    ENDRING_DUF_NUMMER("81"),
    SIVILSTANDSENDRING("85"),
    TILDELING_DNUMMER("91"),
    KORREKSJON_FAMILIEOPPLYSNINGER("98"),
    KORREKSJON_FAMILIEOPPLYSNINGER_BARN("98");

    private String aarsakskode;

}
