TOKEN_X_CLIENT_ID: dev-gcp:dolly:dolly-backend-dev

spring:
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_TESTNAV_DOLLY_BACKEND_DEV_TESTNAV_DOLLY_BACKEND_DEV_HOST}:${NAIS_DATABASE_TESTNAV_DOLLY_BACKEND_DEV_TESTNAV_DOLLY_BACKEND_DEV_PORT}/${NAIS_DATABASE_TESTNAV_DOLLY_BACKEND_DEV_TESTNAV_DOLLY_BACKEND_DEV_DATABASE}?user=${NAIS_DATABASE_TESTNAV_DOLLY_BACKEND_DEV_TESTNAV_DOLLY_BACKEND_DEV_USERNAME}&password=${NAIS_DATABASE_TESTNAV_DOLLY_BACKEND_DEV_TESTNAV_DOLLY_BACKEND_DEV_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1

consumers:
  testnav-profil-api:
    name: testnorge-profil-api-dev
    url: http://testnorge-profil-api-dev
  testnav-pdl-forvalter:
    name: testnav-pdl-forvalter-dev
    url: http://testnav-pdl-forvalter-dev
  testnav-helsepersonell-service:
    url: http://testnav-helsepersonell-service
  testnav-organisasjon-forvalter:
    url: http://testnav-organisasjon-forvalter
  testnav-inntektsmelding-service:
    url: http://testnav-inntektsmelding-service
  testnav-tps-messaging-service:
    url: http://testnav-tps-messaging-service
  testnav-generer-navn-service:
    url: http://generer-navn-service
  testnav-person-service:
    url: http://testnav-person-service
  testnav-arbeidsforhold-service:
    url: http://testnav-arbeidsforhold-service
  testnav-amelding-service:
    url: http://testnav-amelding-service
  testnav-organisasjon-service:
    url: http://testnav-organisasjon-service