spring:
  r2dbc:
    url: r2dbc:postgresql://${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_HOST}:${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_PORT}/${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_DATABASE}
    username: ${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_USERNAME}
    password: ${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_PASSWORD}
    properties:
      sslCert: ${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_SSLCERT}
      sslKey: /tmp/pk8.pem
      sslMode: ${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_SSLMODE}
      sslRootCert: ${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_SSLROOTCERT}
  flyway:
    url: ${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_JDBC_URL}
    user: ${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_USERNAME}
    password: ${NAIS_DATABASE_TESTNAV_TENOR_SEARCH_SERVICE_TESTNAV_TENOR_SEARCH_SERVICE_DB_PASSWORD}
