spring:
  config:
    import: "dolly-application.yml"

springdoc:
  api-docs:
    path: /api/api-docs
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: false

logging:
  level:
    root: INFO
    no.nav.dolly: DEBUG

server:
  servlet:
    context-path: /
  shutdown: graceful
