-----------------
-- T A B L E S --
-----------------
CREATE TABLE T_TEST_IDENT (
  IDENT            NUMBER(11) PRIMARY KEY,
  TILHOERER_GRUPPE NUMBER(9) NOT NULL
);

CREATE TABLE T_TESTGRUPPE (
  ID             NUMBER(9) PRIMARY KEY,
  NAVN           VARCHAR2(50) NOT NULL,
  OPPRETTET_AV   VARCHAR2(10) NOT NULL,
  DATO_ENDRET    TIMESTAMP    NOT NULL,
  SIST_ENDRET_AV VARCHAR2(10) NOT NULL,
  TILHOERER_TEAM NUMBER(9)    NOT NULL
);

CREATE TABLE T_TEAM (
  ID             NUMBER(9) PRIMARY KEY,
  NAVN           VARCHAR2(50) NOT NULL UNIQUE,
  BESKRIVELSE    VARCHAR2(200),
  DATO_OPPRETTET TIMESTAMP    NOT NULL,
  EIER           VARCHAR2(10) NOT NULL
);

CREATE TABLE T_BRUKER (
  NAV_IDENT       VARCHAR2(10) PRIMARY KEY
);

CREATE TABLE TEAM_MEDLEMMER (

  TEAM_ID   NUMBER(9) NOT NULL,
  BRUKER_ID VARCHAR2(10) NOT NULL
);

---------------------------------------------------
-- F O R E I G N   K E Y   C O N S T R A I N T S --
---------------------------------------------------

ALTER TABLE T_TEST_IDENT
  ADD CONSTRAINT TESTPERSON_GRUPPE_PK FOREIGN KEY (TILHOERER_GRUPPE) REFERENCES T_TESTGRUPPE (ID);

ALTER TABLE T_TESTGRUPPE
  ADD CONSTRAINT GRUPPENS_TEAM_FK FOREIGN KEY (TILHOERER_TEAM) REFERENCES T_TEAM (ID);
ALTER TABLE T_TESTGRUPPE
  ADD CONSTRAINT GRUPPEN_ENDRET_AV_FK FOREIGN KEY (SIST_ENDRET_AV) REFERENCES T_BRUKER (NAV_IDENT);
ALTER TABLE T_TESTGRUPPE
  ADD CONSTRAINT GRUPPEN_OPPRETTET_AV_FK FOREIGN KEY (OPPRETTET_AV) REFERENCES T_BRUKER (NAV_IDENT);

ALTER TABLE T_TEAM
  ADD CONSTRAINT TEAMETS_EIER_FK FOREIGN KEY (EIER) REFERENCES T_BRUKER (NAV_IDENT);

ALTER TABLE TEAM_MEDLEMMER
  ADD CONSTRAINT TEAM_MANYTOMANY_FK FOREIGN KEY (TEAM_ID) REFERENCES T_TEAM (ID);
ALTER TABLE TEAM_MEDLEMMER
  ADD CONSTRAINT MEDLEMMER_MANYTOMANY_FK FOREIGN KEY (BRUKER_ID) REFERENCES T_BRUKER (NAV_IDENT);

-----------------------
-- S E Q U E N C E S --
-----------------------
CREATE SEQUENCE T_GRUPPE_SEQ
  START WITH 100000000;
CREATE SEQUENCE T_TEAM_SEQ
  START WITH 100000000;
