-----------------------------
-- A L T E R   T A B L E S --
-----------------------------
ALTER TABLE T_BESTILLING_PROGRESS MODIFY KRRSTUB_STATUS VARCHAR2(4000);
ALTER TABLE T_BESTILLING_PROGRESS MODIFY SIGRUNSTUB_STATUS VARCHAR2(4000);