-----------------------------
-- A L T E R   T A B L E S --
-----------------------------
DELETE FROM T_BESTILLING_PROGRESS
WHERE BESTILLING_ID IN (SELECT ID FROM T_BESTILLING WHERE GRUPPE_ID NOT IN (SELECT ID FROM T_GRUPPE));

DELETE FROM T_BESTILLING_KONTROLL
WHERE BESTILLING_ID IN (SELECT ID FROM T_BESTILLING WHERE GRUPPE_ID NOT IN (SELECT ID FROM T_GRUPPE));

DELETE FROM T_BESTILLING WHERE GRUPPE_ID NOT IN (SELECT ID FROM T_GRUPPE);

COMMIT;

ALTER TABLE T_BESTILLING
    ADD CONSTRAINT BESTILLING_GRUPPE_FK FOREIGN KEY (GRUPPE_ID) REFERENCES T_GRUPPE (ID);