create table WHITELIST
(
  ID    NUMBER PRIMARY KEY,
  FNR   varchar(255),
  WHITE boolean not null
);

ALTER TABLE WHITELIST
  ADD CONSTRAINT Unique_FNR UNIQUE (FNR);

CREATE SEQUENCE WHITELIST_SEQ START WITH 1;