CREATE TABLE ARBEIDSFORHOLD_HISTORIKK
(
    ARBEIDSFORHOLD_ID VARCHAR(256) PRIMARY KEY,
    HISTORIKK         TEXT NOT NULL,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);