DROP TABLE ARBEIDSFORHOLD_HISTORIKK;

CREATE TABLE ARBEIDSFORHOLD_HISTORIKK
(
    ID                SERIAL PRIMARY KEY,
    ARBEIDSFORHOLD_ID VARCHAR(256) NOT NULL,
    HISTORIKK         TEXT,
    ENVIRONMENT       VARCHAR(16)  NOT NULL,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);