CREATE TABLE AJOURHOLD (
  ID                    NUMBER          PRIMARY KEY,
  STATUS                VARCHAR2(255)   NOT NULL,
  SISTOPPDATERT         TIMESTAMP       ,
  FEILMELDING           VARCHAR2(1023)
);

CREATE SEQUENCE AJOURHOLD_SEQ START WITH 1;