package no.nav.registre.tss.domain;

public enum TssType {
    AA("Ambulansearbeider"),
    ADVO("Advokat / Jurist"),
    AFPO("AFP-ordning"),
    AK("NAV-kontor"),
    AMI("Arbeidsmarkedsinstitutt"),
    AN("Ankenemnda for sykepenger"),
    AP("Audiopedagog"),
    APOP("Apotek - privat"),
    APOS("Apotek - sykehus"),
    ART("Arbeidstilsynet"),
    ASEN("NAV Arbeidslivssenter"),
    AT("Apotektekniker"),
    ATU("Attføringsutvalg"),
    AU("Audiograf"),
    BAND("Bandasjist"),
    BB("Begravelsesbyrå"),
    BBE("Bobestyrer"),
    BEH("Behandler"),
    BEUT("Behandlingsreiser i utlandet"),
    BF("Bidragsfogden"),
    BH("Barnehage"),
    BHT("Bedriftshelsetjeneste"),
    BI("Bioingeniør"),
    BIRE("Bidragsreiser"),
    BU("Bilutvalget"),
    EOS("EØS-Land"),
    ET("Ergoterapeut"),
    FA("Farmasøyt"),
    FB("Fiskehelsebiolog"),
    FFU("NAV Internasjonalt"),
    FKL("Felleskontoret LO/NHO"),
    FL("Fylkeslegen"),
    FO("Fotterapeut"),
    FS("Forsikringsselskap"),
    FT("Fysioterapeut"),
    FTK("NAV Fylkesledd"),
    GVS("Grunn- og videregående(skole"),
    HE("Helsesekretær"),
    HF("Helsefagarbeider"),
    HFO("Helseforetak"),
    HJS("Hjemmesykepleien"),
    HMS("NAV Hjelpemiddelsentral"),
    HP("Hjelpepleier"),
    HSTA("Helsestasjon"),
    HTF("Helsetjeneste forvaltning"),
    HU("Høyskole/universitet"),
    INST("Institusjon"),
    IS("Statens Innkrevingssentral"),
    JO("Jordmor"),
    KA("NAV Klageinstans"),
    KE("Klinisk ernæringsfysiolog"),
    KEMN("Kemner"),
    KI("Kiropraktor"),
    KOMM("Kommune"),
    KON("Konvensjonsland"),
    KRED("Kreditor"),
    KRU("Klageinstans reiseutgift"),
    KS("Kurssentra"),
    KYND("Sakkyndig"),
    LARO("Lab/røntgen - privat"),
    LBS("NAV Landsdekkende bilsenter"),
    LE("Lege"),
    LERA("Rådgivende lege"),
    LFK("Legemiddel fagkontor"),
    LK("Ligningskontor"),
    LM("Leverandør motorkjøretøy"),
    LOGO("Logoped"),
    LRB("Løsøreregisteret i Brønnøysund"),
    LS("Legesenter"),
    MT("Manuellterapeut"),
    NB("Namsmannen"),
    NK("NAV Kontroll"),
    OA("Omsorgsarbeider"),
    OI("Ortopediingeniør"),
    OM("Ombygger bil"),
    OP("Optiker"),
    OPT("Opptreningsinstitusjon"),
    OR("Ortoptist"),
    PE("Perfusjonist"),
    PF("Provisorfarmasøyt"),
    PPT("Psykologisk pedagogisk tjeneste"),
    PR("Pasientreiser"),
    PS("Psykolog"),
    RA("Radiograf"),
    REGO("Regional oppgjørsenhet"),
    R("Reseptarfarmasøyt"),
    RHFO("Regionalt helseforetak"),
    RKK("NAV Regionklagekontor"),
    ROL("Rådgivende overlege"),
    RT("Rådgivende tannlege"),
    RTK("Regionstrygdekontor"),
    SAD("Samleadressat"),
    SK("Sosialkontor"),
    SP("Sykepleier"),
    SR("Skifteretten"),
    SUD("Statens utlendingsdirektorat"),
    SYKH("Sykehus"),
    TEPE("Tjenestepensjons leverandør"),
    TH("Tannhelsesekretær"),
    TI("Takseringsinstanser"),
    TK("NAV-kontor"),
    TL("Tannlege"),
    TLO("Tannlege offentlig"),
    TOLK("Tolk"),
    TP("Tannpleier"),
    TR("Trygderetten"),
    TT("Tanntekniker"),
    UTL("Utenlandsk samhandler"),
    VE("Veterinær"),
    VP("Vernepleier"),
    X("Diverse"),
    YM("Yrkesmedisiner");

    public String beskrivelse;

    TssType(String s) {
        beskrivelse = s;
    }
}
