export const initialValues = {
	// identifikator: null,
	// identifikatorType: null,
	// foedselsdato: {
	// 	fraOgMed: null,
	// 	tilOgMed: null,
	// },
	// doedsdato: {
	// 	fraOgMed: null,
	// 	tilOgMed: null,
	// },
	// kjoenn: null,
	// personstatus: null,
	// sivilstatus: null,
	// utenlandskPersonIdentifikasjon: [null],
	// identitetsgrunnlagStatus: null,
	// adressebeskyttelse: null,
	// harLegitimasjonsdokument: false,
	// harFalskIdentitet: false,
	// harNorskStatsborgerskap: false,
	// harFlereStatsborgerskap: false,
	// navn: {
	// 	navnLengde: {
	// 		fraOgMed: null,
	// 		tilOgMed: null,
	// 	},
	// 	harFlereFornavn: false,
	// 	harMellomnavn: false,
	// 	harNavnSpesialtegn: false,
	// },
	// adresser: {
	// 	adresseGradering: null,
	// 	kommunenummer: null,
	// 	harBostedsadresse: false,
	// 	harOppholdAnnetSted: false,
	// 	harPostadresseNorge: false,
	// 	harPostadresseUtland: false,
	// 	harKontaktadresseDoedsbo: false,
	// 	harAdresseSpesialtegn: false,
	// },
	// relasjoner: {
	// 	relasjon: null,
	// 	antallBarn: {
	// 		fraOgMed: null,
	// 		tilOgMed: null,
	// 	},
	// 	harForeldreAnsvar: false,
	// 	relasjonMedFoedselsaar: {
	// 		fraOgMed: null,
	// 		tilOgMed: null,
	// 	},
	// 	harDeltBosted: false,
	// 	harVergemaalEllerFremtidsfullmakt: false,
	// 	borMedMor: false,
	// 	borMedFar: false,
	// 	borMedMedmor: false,
	// 	foreldreHarSammeAdresse: false,
	// },
	// hendelser: {
	// 	hendelse: null,
	// 	sisteHendelse: null,
	// },
	// roller: [null],
	// tjenestepensjonsavtale: {
	// 	pensjonsinnretningOrgnr: null,
	// 	periode: null,
	// },
	// skattemelding: {
	// 	inntektsaar: null,
	// 	skattemeldingstype: null,
	// },
	inntektAordningen: {
		// periode: {
		// 	fraOgMed: null,
		// 	tilOgMed: null,
		// },
		// opplysningspliktig: null,
		// inntektstyper: [null],
		beskrivelse: null,
		// forskuddstrekk: [null],
		// harHistorikk: false,
	},
	// skatteplikt: {
	// 	inntektsaar: null,
	// 	skattepliktstyper: [null],
	// 	saerskiltSkatteplikt: null,
	// },
	// tilleggsskatt: {
	// 	inntektsaar: null,
	// 	tilleggsskattTyper: [null],
	// },
	// arbeidsforhold: {
	// 	startDatoPeriode: {
	// 		fraOgMed: null,
	// 		tilOgMed: null,
	// 	},
	// 	sluttDatoPeriode: {
	// 		fraOgMed: null,
	// 		tilOgMed: null,
	// 	},
	// 	harPermisjoner: false,
	// 	harPermitteringer: false,
	// 	harArbeidsgiver: false,
	// 	harTimerMedTimeloenn: false,
	// 	harUtenlandsopphold: false,
	// 	harHistorikk: false,
	// 	arbeidsforholdstype: null,
	// },
	// beregnetSkatt: {
	// 	inntektsaar: null,
	// 	oppgjoerstype: null,
	// 	pensjonsgivendeInntekt: false,
	// },
	// opplysningerFraSkatteetatensInnsendingsmiljoe: {
	// 	inntektsaar: null,
	// 	harSkattemeldingUtkast: false,
	// 	harSkattemeldingFastsatt: false,
	// },
	// samletReskontroInnsyn: {
	// 	harKrav: false,
	// 	harInnbetaling: false,
	// },
	// summertSkattegrunnlag: {
	// 	inntektsaar: null,
	// 	stadietype: null,
	// 	oppgjoerstype: null,
	// 	tekniskNavn: null,
	// 	alminneligInntektFoerSaerfradragBeloep: {
	// 		fraOgMed: null,
	// 		tilOgMed: null,
	// 	},
	// },
	// spesisfisertSummertSkattegrunnlag: {
	// 	inntektsaar: null,
	// 	stadietype: null,
	// 	oppgjoerstype: null,
	// 	tekniskNavn: null,
	// 	spesifiseringstype: null,
	// 	alminneligInntektFoerSaerfradragBeloep: {
	// 		fraOgMed: null,
	// 		tilOgMed: null,
	// 	},
	// },
}
