spring:
  application:
    name: testnav-bruker-service
    description: Tjeneste for brukere
  config:
    import: "classpath:dolly-application.yml"
  security:
    oauth2:
      resourceserver:
        aad:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}
        tokenx:
          accepted-audience: ${TOKEN_X_CLIENT_ID}

consumers:
  testnav-altinn3-tilgang-service:
    name: testnav-altinn3-tilgang-service-prod
    namespace: dolly
    url: https://testnav-altinn3-tilgang-service.nav.no
    cluster: prod-gcp