spring:
  cloud:
    vault:
      enabled: false

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /internal
      exposure.include: info,health,heapdump,prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    prometheus.enabled: true
    heapdump.enabled: true
    health.probes.enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
server:
  servlet:
    encoding:
      charset: UTF-8
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            security:
              reactive:
                ReactiveUserDetailsServiceAutoConfiguration: OFF

app:
  slack:
    bot-token: ${DOLLY_ALERTS_SLACK_BOT_TOKEN}
    channel-id: "C02GJN0UR1P"