spring:
  application:
    name: testnav-pdl-forvalter-dev
  r2dbc:
    url: r2dbc:postgresql://${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_HOST}:${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_PORT}/${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_DATABASE}
    username: ${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_USERNAME}
    password: ${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_HOST}:${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_PORT}/${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_DATABASE}
    user: ${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_USERNAME}
    password: ${NAIS_DATABASE_TESTNAV_PDL_FORVALTER_DEV_TESTNAV_PDL_FORVALTER_DEV_DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        tokenx:
          issuer-uri: ${TOKEN_X_ISSUER}
          accepted-audience: ${ACCEPTED_AUDIENCE}