CREATE TABLE IDENT
(
    IDENT  VARCHAR(64) PRIMARY KEY,
    DOKUMENT   TEXT        NOT NULL,
    GRUPPE     VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);