CREATE TABLE VARSLING
(
    VARSLING_ID VARCHAR(256) PRIMARY KEY,
    FOM         DATE NULL,
    TOM         DATE NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BRUKER
(
    OBJECT_ID  VARCHAR(256) PRIMARY KEY,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE MOTTATT_VARSLING
(
    ID                   SERIAL PRIMARY KEY,
    BRUKER_OBJECT_ID     VARCHAR(256) REFERENCES BRUKER,
    VARSLING_VARSLING_ID VARCHAR(256) REFERENCES VARSLING,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);