package no.nav.dolly.domain.resultset.dokarkiv;

public enum Fagsaksystem {

        FS38, FS36, UFM, OEBS, OB36, AO01, AO11, IT01, PP01, K9, BISYS, BA, EF, KONT,
        SUPSTONAD, OMSORGSPENGER, HJELPEMIDLER, BARNEBRILLER, EY, KELVIN, DAGPENGER, KOMPYS, ARGUS, NEESSI,
        TILLEGGSSTONADER, ARBEIDSOPPFOLGING, TILTAKSPENGER, TILTAKSADMINISTRASJON, FIA, HELT, UNG_SAK, REMEDY
    }