ARG BASE_IMAGE=mcr.microsoft.com/devcontainers/java:1-21-bullseye
FROM ${BASE_IMAGE}

ENV TZ=Europe/Oslo
ENV JAVA_TOOL_OPTIONS="-Duser.timezone=Europe/Oslo -Dreactor.bufferSize.small=10000 --add-opens=java.base/java.lang=ALL-UNNAMED"



