-- Manuelt legge dette inn i tabell kodeverk

insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (1, '1814-05-17', '2001-03-01', 'ANDRESAKER', 'UTFALL', 'Andre sakstyper');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (2, '1814-05-17', null, 'ARB', 'TILLATELSE', 'Arbeidstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (3, '2010-01-01', null, 'ARBASYLSØK', 'TILLATELSE', 'Rett til å ta arbeid som asylsøker');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (4, '1814-05-17', null, 'ARBDEL', 'TILLATELSE', 'Arbeidstillatelse, for deltidsarbeid');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (5, '1814-05-17', null, 'ARBFLYKT', 'TILLATELSE', 'Arbeidstillatelse med flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (6, '1814-05-17', null, 'ARBFLYKTINNR', 'TILLATELSE', 'Arbeidstillatelse med flyktningstatus - med innreisetillatelse, for overføringsflyktning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (7, '1814-05-17', null, 'ARBFORL', 'TILLATELSE', 'Arbeidstillatelse, foreløpig');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (8, '2009-05-01', null, 'ARBFORLMUF', 'TILLATELSE', 'Arbeidstillatelse, foreløpig etter mfi § 2b');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (9, '1814-05-17', null, 'ARBFRI', 'TILLATELSE', 'Arbeidstillatelse, for fritidsarbeid');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (10, '1814-05-17', null, 'ARBGRUPP', 'TILLATELSE', 'Arbeidstillatelse, for gruppe');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (11, '2010-01-01', null, 'ARBGRUPPARBG', 'TILLATELSE', 'Arbeidstillatelse for gruppe, arbeidsgiver');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (12, '1814-05-17', null, 'ARBGRUPPFORL', 'TILLATELSE', 'Foreløpig arbeidstillatelse for gruppe');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (13, '1814-05-17', null, 'ARBGRUPPKONT', 'TILLATELSE', 'Gruppetillatelse kontinentalsokkelen (både arbeids-og oppdragsgiver)');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (14, '2010-01-01', null, 'ARBGRUPPOPPDR', 'TILLATELSE', 'Arbeidstillatelse for gruppe, oppdragsgiver');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (15, '1814-05-17', null, 'ARBIGRUPP', 'TILLATELSE', 'Arbeidstillatelse, individuell i gruppe');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (16, '1814-05-17', null, 'ARBIGRUPPFORL', 'TILLATELSE', 'Foreløpig arbeidstillatelse, individuell i gruppe');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (17, '1814-05-17', null, 'ARBINNR', 'TILLATELSE', 'Arbeidstillatelse med innreisetillatelse, for overføringsflyktning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (18, '1814-05-17', null, 'ARBMIDL', 'TILLATELSE', 'Arbeidstillatelse, midlertidig for asylsøkere');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (19, '1814-05-17', null, 'ARBORD', 'TILLATELSE', 'Arbeidstillatelse, ordinær');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (20, '1814-05-17', null, 'ARBORDBEGR', 'TILLATELSE', 'Arbeidstillatelse, ordinær - begrensninger, jf uf § 21 åttende ledd');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (21, '2010-01-01', null, 'ARBTIDL', 'TILLATELSE', 'Arbeidstillatelse, tidlig arbeidsstart');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (22, '1814-05-17', '2011-02-01', 'BORTFALLBOS', 'UTFALL', 'Bortfall av bosettingstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (23, '2010-01-01', null, 'BORTFALLPOT', 'UTFALL', 'Bortfall av permanent oppholdstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (24, '1814-05-17', null, 'BOS', 'TILLATELSE', 'Bosettingstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (25, '1814-05-17', null, 'BOSBARN', 'TILLATELSE', 'Bosettingstillatelse for barn');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (26, '2003-09-01', null, 'BOSBARNADOP', 'TILLATELSE', 'Bosettingstillatelse for adoptivbarn');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (27, '2003-09-01', null, 'BOSBARNIRIK', 'TILLATELSE', 'Bosettingstillatelse for barn født i riket');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (28, '1814-05-17', null, 'BOSBIH', 'TILLATELSE', 'Bosettingstillatelse, tidligere kollektiv beskyttelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (29, '1814-05-17', null, 'BOSLANGOPP', 'TILLATELSE', 'Bosettingstillatelse, tidligere langvarig opphold');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (30, '1814-05-17', null, 'BOSORD', 'TILLATELSE', 'Bosettingstillatelse, ordinær');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (31, '1814-05-17', null, 'BOSORDFLYKT', 'TILLATELSE', 'Bosettingstillatelse, ordinær, med flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (32, '1814-05-17', null, 'BOSRET', 'TILLATELSE', 'Tillatelse til opphold i utlandet uten bortfall av BOS');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (33, '1814-05-17', null, 'BOSRETIFØLG', 'TILLATELSE', 'BOS består, tross opphold i utlandet i følge med ektefelle m fl');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (34, '1814-05-17', null, 'BOSRETOPPUTL', 'TILLATELSE', 'BOS består, tross opphold i utlandet pga arbeid mm');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (35, '1814-05-17', null, 'BOSRETVERNPL', 'TILLATELSE', 'BOS består, tross opphold i utlandet pga verneplikt ol');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (36, '1814-05-17', null, 'BOSRIML', 'TILLATELSE', 'Bosettingstillatelse, særlig sterke rimlighetsgrunner');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (37, '1814-05-17', null, 'BOSTIDLKOLL', 'TILLATELSE', 'Bosettingtillatelse, tidligere kollektiv beskyttelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (38, '2008-08-04', null, 'BOSTILBSTB', 'TILLATELSE', 'Bosetningstillatelse ved tilbakekall av statsborgerskap');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (39, '2001-01-01', null, 'BOSUTEN', 'TILLATELSE', 'Bosettingstillatelse ved utenriksstasjon for maker til norsk borger');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (40, '2012-04-13', null, 'GBB', 'TILLATELSE', 'Grenseboerbevis');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (41, '2012-04-13', null, 'GBBORD', 'TILLATELSE', 'Grenseboerbevis ordinært');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (42, '1814-05-17', '2004-01-20', 'GRUPP', 'TILLATELSE', 'Arbeidstillatelse for gruppe');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (43, '1814-05-17', '2004-01-20', 'GRUPPFORL', 'TILLATELSE', 'Foreløpig arbeidstillatelse for gruppe');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (44, '1814-05-17', null, 'INNR', 'TILLATELSE', 'Innreisetillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (45, '1814-05-17', null, 'INNRLANDLOV', 'TILLATELSE', 'Tillatelse til å gå i land fra skip');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (46, '2010-01-01', null, 'INNRLANDLOVBLIND', 'TILLATELSE', 'Tillatelse for blindpassasjer til å gå i land fra skip');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (47, '2010-01-01', null, 'INNRLANDLOVFLYKT', 'TILLATELSE', 'Tillatelse til å gå i land, påberoper seg å være flyktning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (48, '2010-01-01', null, 'INNRLANDLOVSJØ', 'TILLATELSE', 'Tillatelse til å fratre stilling på skip');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (49, '2010-01-01', null, 'INNRSEILAS', 'TILLATELSE', 'Seilingstillatelse for lystseilas');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (50, '1814-05-17', '2001-03-01', 'KONV', 'TILLATELSE', 'Konvertert vedtakskode');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (51, '1814-05-17', '2001-03-01', 'KONVB', 'TILLATELSE', 'Konvertert vedtakskode B, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (52, '1814-05-17', '2001-03-01', 'KONVD', 'TILLATELSE', 'Konvertert vedtakskode D, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (53, '1814-05-17', '2001-03-01', 'KONVE', 'TILLATELSE', 'Konvertert vedtakskode E, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (54, '1814-05-17', '2001-03-01', 'KONVF', 'TILLATELSE', 'Konvertert vedtakskode F, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (55, '1814-05-17', '2001-03-01', 'KONVG', 'TILLATELSE', 'Konvertert vedtakskode G, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (56, '1814-05-17', '2001-03-01', 'KONVGE', 'TILLATELSE', 'Konvertert vedtakskode GE, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (57, '1814-05-17', '2001-03-01', 'KONVINN', 'TILLATELSE', 'Konvertert vedtakskode INN, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (58, '1814-05-17', '2001-03-01', 'KONVM', 'TILLATELSE', 'Konvertert vedtakskode M, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (59, '1814-05-17', '2001-03-01', 'KONVR', 'TILLATELSE', 'Konvertert vedtakskode R, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (60, '1814-05-17', '2001-03-01', 'KONVS', 'TILLATELSE', 'Konvertert vedtakskode S, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (61, '1814-05-17', '2001-03-01', 'KONVU', 'TILLATELSE', 'Konvertert vedtakskode U, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (62, '1814-05-17', '2001-03-01', 'KONVUE', 'TILLATELSE', 'Konvertert vedtakskode E, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (63, '1814-05-17', '2001-03-01', 'KONVUG', 'TILLATELSE', 'Konvertert vedtakskode UG, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (64, '1814-05-17', '2001-03-01', 'KONVUGE', 'TILLATELSE', 'Konvertert vedtakskode UGE, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (65, '1814-05-17', '2001-03-01', 'KONVXAV', 'TILLATELSE', 'Konvertert vedtakskode XAV, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (66, '1814-05-17', '2001-03-01', 'KONVXOP', 'TILLATELSE', 'Konvertert vedtakskode XOP, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (67, '1814-05-17', '2001-03-01', 'KONVY', 'TILLATELSE', 'Konvertert vedtakskode Y, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (68, '1814-05-17', '2001-03-01', 'KONVYB', 'TILLATELSE', 'Konvertert vedtakskode YB, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (69, '1814-05-17', '2001-03-01', 'KONVYF', 'TILLATELSE', 'Konvertert vedtakskode YF, inaktiv');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (70, '2013-10-07', null, 'KORT', 'TILLATELSE', 'Oppholdskort mv.');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (71, '2013-10-07', null, 'KORTDIPL', 'TILLATELSE', 'Oppholdskort for diplomater mv.');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (72, '2013-10-07', null, 'KORTDIPLORD', 'TILLATELSE', 'Oppholdskort for diplomater mv., ordinær');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (73, '2017-03-02', null, 'KORTNATO', 'TILLATELSE', 'KORTNATO');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (74, '2017-03-02', null, 'KORTNATOCP', 'TILLATELSE', 'KORTNATOCP');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (75, '2017-03-02', null, 'KORTNATODEP', 'TILLATELSE', 'KORTNATODEP');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (76, '2017-03-02', null, 'KORTNATOMOF', 'TILLATELSE', 'KORTNATOMOF');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (77, '2017-03-02', null, 'KORTNATONSUPPE', 'TILLATELSE', 'KORTNATONSUPPE');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (78, '2010-01-01', null, 'MOT', 'TILLATELSE', 'Midlertidig oppholdstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (79, '2010-01-01', null, 'MOTBEGR', 'TILLATELSE', 'Midlertidig oppholdstillatelse, begrenset');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (80, '2010-01-01', '2010-01-01', 'MOTBEGRARB', 'TILLATELSE', 'Midlertidig oppholdstillatelse, begrenset rett til å arbeide');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (81, '2010-01-01', null, 'MOTDELARB', 'TILLATELSE', 'Midlertidig oppholdstillatelse, deltidarbeid');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (82, '2010-03-30', null, 'MOTFAMDIPL', 'TILLATELSE', 'Tillatelse til arbeid, tilmeldt familiemedlem');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (83, '2010-01-01', null, 'MOTFLYKT', 'TILLATELSE', 'Midlertidig oppholdstillatelse, flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (84, '2010-01-01', null, 'MOTFLYKTINNR', 'TILLATELSE', 'Midlertidig oppholdstillatelse, flyktningstatus - med innreisetillatelse, overføringsflyktning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (85, '2010-01-01', null, 'MOTFORL', 'TILLATELSE', 'Foreløpig oppholdstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (86, '2010-01-01', null, 'MOTIGRUPP', 'TILLATELSE', 'Midlertidig oppholdstillatelse, individuell i gruppe');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (87, '2010-01-01', null, 'MOTINNR', 'TILLATELSE', 'Midlertidig oppholdstillatelse med innreisetillatelse, overføringsflyktning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (88, '2010-01-01', null, 'MOTORD', 'TILLATELSE', 'Midlertidig oppholdstillatelse, ordinær');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (89, '2010-01-01', null, 'MOTORDBEGR', 'TILLATELSE', 'Midlertidig oppholdstillatelse, ordinær, med begrensninger');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (90, '2010-01-01', null, 'MOTORDBEGRARB', 'TILLATELSE', 'Midlertidig oppholdstillatelse, ikke rett til å arbeide');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (91, '2010-01-01', null, 'MOTORDBEGRDELARB', 'TILLATELSE', 'Midlertidig oppholdstillatelse, kun rett til deltidsarbeid');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (92, '2010-01-01', null, 'MOTORDBEGREMA', 'TILLATELSE', 'Midlertidig oppholdstillatelse, ordinær, med begrensninger, EMA over 16 år uten forsvarlig omsorg ved retur');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (93, '2010-01-01', null, 'MOTORDBEGRID', 'TILLATELSE', 'Midlertidig oppholdstillatelse, ordinær, med begrensninger, pga id-tvil eller mangler id-dok');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (94, '2010-01-01', null, 'MOTORDINNR', 'TILLATELSE', 'Midlertidig oppholdstillatelse, ordinær, rimelighetsgrunner - med innreisetillatelse, overføringsflyktning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (95, '1814-05-17', null, 'OMGJ', 'UTFALL', 'Omgjøring');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (96, '2010-01-01', null, 'OMGJBORTFALLPOT', 'UTFALL', 'Omgjøring av vedtak om bortfall av permanent oppholdstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (97, '2007-06-15', null, 'OMGJTILBARBOPPH', 'UTFALL', 'Omgjøring i UNE av UDIs tilbakekall av arbeids- / oppholdstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (98, '2010-01-04', null, 'OMGJTILBEØS', 'UTFALL', 'Omgjøring av tilbakekall av oppholdsdokument etter EØS-registreringsordningen');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (99, '1814-05-17', null, 'OPP', 'TILLATELSE', 'Oppholdstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (100, '2009-05-01', null, 'OPPBEGREMA', 'TILLATELSE', 'Begrenset oppholdstillatelse for EMA');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (101, '1814-05-17', '2002-06-03', 'OPPEØS', 'TILLATELSE', 'Oppholdstillatelse, EØS');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (102, '2002-07-01', null, 'OPPEØSEFTA', 'TILLATELSE', 'Oppholdstillatelse, EØS/EFTA');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (103, '2002-07-01', null, 'OPPEØSEFTAOVERG', 'TILLATELSE', 'Oppholdstillatelse, EØS/EFTA - til utlending omfattet av overgangsregler');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (104, '1814-05-17', null, 'OPPFLYKT', 'TILLATELSE', 'Oppholdstillatelse med flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (105, '1814-05-17', null, 'OPPFLYKTINNR', 'TILLATELSE', 'Oppholdstillatelse med flyktningstatus - med innreisetillatelse, for overføringsflyktning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (106, '1814-05-17', null, 'OPPFORL', 'TILLATELSE', 'Oppholdstillatelse, foreløpig');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (107, '1814-05-17', null, 'OPPINNR', 'TILLATELSE', 'Oppholdstillatelse med innreisetillatelse, for overføringsflyktning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (108, '1814-05-17', null, 'OPPORD', 'TILLATELSE', 'Oppholdstillatelse, ordinær');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (109, '1814-05-17', null, 'OPPORDBEGR', 'TILLATELSE', 'Oppholdstillatelse, ordinær - begrensninger, jf uf § 21 åttende ledd');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (110, '1814-05-17', '2003-01-03', 'OPPORDKAR', 'TILLATELSE', 'Ordinær oppholdstillatelse med karantene');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (111, '1814-05-17', '2003-01-03', 'OPPORDUKAR', 'TILLATELSE', 'Oppholdstillatelse for student uten karantene');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (112, '2010-01-01', null, 'POT', 'TILLATELSE', 'Permanent oppholdstillatelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (113, '2010-01-01', null, 'POTBARN', 'TILLATELSE', 'Permanent oppholdstillatelse for barn');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (114, '2010-01-01', null, 'POTBARNADOP', 'TILLATELSE', 'Permanent oppholdstillatelse for adoptivbarn');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (115, '2010-01-01', null, 'POTBARNIRIK', 'TILLATELSE', 'Permanent oppholdstillatelse for barn født i Norge');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (116, '2011-01-11', null, 'POTBARNIRIKFLYKT', 'TILLATELSE', 'Permanent oppholdstillatelse for barn født i Norge, med flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (117, '2010-01-01', null, 'POTDIPHUSSTAND', 'TILLATELSE', 'Permanent oppholdstillatelse, husstandsmedlem til utsendt personell ved norsk utenriksstasjon');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (118, '2010-01-01', null, 'POTEØS', 'TILLATELSE', 'Permanent oppholdstillatelse, tillatelse etter EØS/EFTA-regelverket');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (119, '2010-01-01', null, 'POTLANGOPP', 'TILLATELSE', 'Permanent oppholdstillatelse, tidligere langvarig opphold i Norge');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (120, '2011-01-11', null, 'POTLANGOPPFLYKT', 'TILLATELSE', 'Permanent oppholdstillatelse, tidligere langvarig opphold i Norge, med flyktningsstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (121, '2010-01-01', null, 'POTORD', 'TILLATELSE', 'Permanent oppholdstillatelse, ordinær');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (122, '2010-01-01', null, 'POTORD15MND', 'TILLATELSE', 'Permanent oppholdstillatelse, ordinær, hatt tillatelse som faglært/spesialist');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (123, '2010-01-01', null, 'POTORDFLYKT', 'TILLATELSE', 'Permanent oppholdstillatelse, ordinær, med flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (124, '2010-01-01', null, 'POTRET', 'TILLATELSE', 'Tillatelse til opphold i utlandet uten bortfall av POT');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (125, '2010-01-01', null, 'POTRETARBUTD', 'TILLATELSE', 'Tillatelse til opphold i utlandet uten bortfall av POT grunnet arbeid/utdanning');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (126, '2010-01-01', null, 'POTRETIFØLG', 'TILLATELSE', 'Tillatelse til opphold i utlandet uten bortfall av POT i følge med ektefelle m.fl.');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (127, '2010-01-01', null, 'POTRETVERNPL', 'TILLATELSE', 'Tillatelse til opphold i utlandet uten bortfall av POT for å avtjene verneplikt eller lignende');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (128, '2010-01-01', null, 'POTRIM', 'TILLATELSE', 'Permanent oppholdstillatelse, særlig sterke rimelighetsgrunner');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (129, '2011-01-11', null, 'POTRIMFLYKT', 'TILLATELSE', 'Permanent oppholdstillatelse, særlig sterke rimelighetsgrunner, med flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (130, '2010-01-01', null, 'POTSVALBARD', 'TILLATELSE', 'Permanent oppholdstillatelse, tidligere langvarig opphold på Svalbard');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (131, '2011-01-11', null, 'POTSVALBARDFLYKT', 'TILLATELSE', 'Permanent oppholdstillatelse, tidligere langvarig opphold på Svalbard, med flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (132, '2010-01-01', null, 'POTTIDLKOLL', 'TILLATELSE', 'Permanent oppholdstillatelse, tidligere kollektiv beskyttelse');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (133, '2010-01-01', null, 'POTTILBSTB', 'TILLATELSE', 'Permanent oppholdstillatelse etter tilbakekall av norsk statsborgerskap');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (134, '2010-01-01', null, 'POTURIKS', 'TILLATELSE', 'Permanent oppholdstillatelse, ektefelle/samboer til norsk borger ved norsk utenriksstasjon');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (135, '1814-05-17', null, 'RDOKRB', 'TILLATELSE', 'Reisebevis');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (136, '2010-01-01', null, 'RDOKRBFREMSTAT', 'TILLATELSE', 'Reisebevis, har reisebevis utstedt av fremmed stat');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (137, '2010-01-01', null, 'RDOKRBORD', 'TILLATELSE', 'Reisebevis, ordinært');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (138, '2010-01-01', null, 'RDOKRBSJØMENN', 'TILLATELSE', 'Reisebevis, sjømenn');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (139, '1814-05-17', null, 'STB', 'TILLATELSE', 'Statsborgerskap');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (140, '1950-01-01', null, 'STBBEV', 'TILLATELSE', 'Statsborgerskap ved bevilling');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (141, '1950-01-01', null, 'STBBEVFLYKT', 'TILLATELSE', 'Statsborgerskap ved bevilling, med flyktningstatus');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (142, '1950-01-01', null, 'STBBIB', 'TILLATELSE', 'Statsborgerskap, ved bibehold');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (143, '1950-01-01', null, 'STBLØS', 'TILLATELSE', 'Statsborgerskap, løsning fra norsk statsborgerskap');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (144, '1950-01-01', null, 'STBMELD', 'TILLATELSE', 'Statsborgerskap, ved melding');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (145, '1950-01-01', null, 'STBMELDADOP', 'TILLATELSE', 'Statsborgerskap, ved melding av adoptivbarn');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (146, '1950-01-01', null, 'STBMELDFAR', 'TILLATELSE', 'Statsborgerskap, ved fedremelding');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (147, '1814-05-17', null, 'STBMELDMOR', 'TILLATELSE', 'Statsborgerskap, ved mødremelding');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (148, '2006-09-01', null, 'STBOPPR', 'TILLATELSE', 'Statsborgerskap opprettholdes pga særlige grunner');
insert into public.kodeverk (id, aktiv_fom, aktiv_tom, kode, type, visningsnavn) values (149, '2010-04-19', null, 'UTR', 'TILLATELSE', 'Utreisetillatelse');
commit;