CREATE TABLE CAR_ENTITY
(
    REGNUMBER  VARCHAR(42) PRIMARY KEY,
    COLOR      VARCHAR(256) NOT NULL,
    BRAND      VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);