INSERT INTO CAR_ENTITY (REGNUMBER, COLOR, BRAND)
values ('AB12345', 'Blue', 'Volvo');
INSERT INTO CAR_ENTITY (REGNUMBER, COLOR, BRAND)
values ('AK12345', 'Blue', 'Volvo');
INSERT INTO CAR_ENTITY (REGNUMBER, COLOR, BRAND)
values ('EL12345', 'Gray', 'Volvo');
INSERT INTO CAR_ENTITY (REGNUMBER, COLOR, BRAND)
values ('AB54321', 'Blue', 'Bentley');
INSERT INTO CAR_ENTITY (REGNUMBER, COLOR, BRAND)
values ('AC34443', 'Green', 'Bentley');