package no.nav.dolly.domain.resultset.udistub.model.opphold;

public enum UdiGrunnlagOverig {

    PERMANENT, BESKYTTELSE, STERKE_MENNESKELIGE_HENSYN_ELLER_SAERLIG_TILKNYTNING_TIL_NORGE, ARBEID, UTDANNING, FAMILIE, SELVSTENDIG_NAERINGSVIRKSOMHET, ANNET, UAVKLART
}
