package no.nav.testnav.libs.dto.pdlforvalter.v1;

public enum RelasjonType {

    FULLMEKTIG,
    FULLMAKTSGIVER,
    VERGE,
    VERGE_MOTTAKER,
    RIKTIG_IDENTITET,
    FALSK_IDENTITET,
    KONTAKT_FOR_DOEDSBO,
    AVDOEDD_FOR_KONTAKT,
    NY_IDENTITET,
    GAMMEL_IDENTITET,
    EKTEFELLE_PARTNER,
    FAMILIERELASJON_BARN,
    FAMILIERELASJON_FORELDER,
    FORELDREANSVAR_BARN,
    FORELDREANSVAR_FORELDER
}
