package no.nav.testnav.libs.dto.pdlforvalter.v1;

public enum RelasjonType {

    FULLMEKTIG,
    FULLMAKTSGIVER,
    VERGE,
    VERGE_MOTTAKER,
    RIKTIG_IDENTITET,
    FALSK_IDENTITET,
    ADRESSAT_FOR_DOEDSBO,
    AVDOEDD_SIN_ADRESSAT,
    NY_IDENTITET,
    GAMMEL_IDENTITET,
    SIVILSTAND_PERSON,
    SIVILSTAND_RELATERT_PERSON,
    FAMILIERELASJON_BARN,
    FAMILIERELASJON_FORELDER
}
