-----------------------------
-- A L T E R   T A B L E S --
-----------------------------
ALTER TABLE T_TRANSAKSJON_MAPPING
    ADD BESTILLING_ID NUMBER(9);
ALTER TABLE T_TRANSAKSJON_MAPPING
    ADD CONSTRAINT TRANSAKSJON_MAPPING_FK FOREIGN KEY (BESTILLING_ID) REFERENCES T_BESTILLING (ID);
