-----------------------------
-- A L T E R   T A B L E S --
-----------------------------
ALTER TABLE T_BESTILLING
    DISABLE CONSTRAINT BESTILLING_GRUPPE_FK;

ALTER TABLE T_BESTILLING
    DROP CONSTRAINT BESTILLING_GRUPPE_FK;

ALTER TABLE T_BESTILLING
    ADD CONSTRAINT BESTILLING_GRUPPE_FK FOREIGN KEY (GRUPPE_ID) REFERENCES T_GRUPPE(ID);

ALTER TABLE T_TEST_IDENT
    DISABLE CONSTRAINT TESTPERSON_GRUPPE_FK;

ALTER TABLE T_TEST_IDENT
    DROP CONSTRAINT TESTPERSON_GRUPPE_FK;

ALTER TABLE T_TEST_IDENT
    ADD CONSTRAINT TESTPERSON_GRUPPE_FK FOREIGN KEY (TILHOERER_GRUPPE) REFERENCES T_GRUPPE(ID);