package no.nav.dolly.domain.resultset.inntektsmeldingstub;

public enum NaturalytelseType {

    AKSJER_GRUNNFONDSBEVIS_TIL_UNDERKURS,
    LOSJI,
    KOST_DOEGN,
    BESOEKSREISER_HJEMMET_ANNET,
    KOSTBESPARELSE_I_HJEMMET,
    RENTEFORDEL_LAAN,
    BIL,
    KOST_DAGER,
    BOLIG,
    SKATTEPLIKTIG_DEL_FORSIKRINGER,
    FRI_TRANSPORT,
    OPSJONER,
    TILSKUDD_BARNEHAGEPLASS,
    ANNET,
    BEDRIFTSBARNEHAGEPLASS,
    YRKEBIL_TJENESTLIGBEHOV_KILOMETER,
    YRKEBIL_TJENESTLIGBEHOV_LISTEPRIS,
    INNBETALING_TIL_UTENLANDSK_PENSJONSORDNING,
    ELEKTRONISK_KOMMUNIKASJON
}
