insert into jobb_parameter (navn, tekst, verdi) values ("antallOrganisasjoner", "Antall Organisasjoner", "20");
insert into jobb_parameter (navn, tekst, verdi) values ("antallPersoner", "Antall Personer", "40");
insert into verdier (verdi_navn, verdi_verdi) values ("antallOrganisasjoner", 20);
insert into verdier (verdi_navn, verdi_verdi) values ("antallOrganisasjoner", 40);
insert into verdier (verdi_navn, verdi_verdi) values ("antallOrganisasjoner", 60);
insert into verdier (verdi_navn, verdi_verdi) values ("antallOrganisasjoner", 80);
insert into verdier (verdi_navn, verdi_verdi) values ("antallOrganisasjoner", 100);
insert into verdier (verdi_navn, verdi_verdi) values ("antallPersone", 40);
insert into verdier (verdi_navn, verdi_verdi) values ("antallPersone", 80);
insert into verdier (verdi_navn, verdi_verdi) values ("antallPersone", 120);
insert into verdier (verdi_navn, verdi_verdi) values ("antallPersone", 160);
insert into verdier (verdi_navn, verdi_verdi) values ("antallPersone", 180);