package no.nav.dolly.synt.tilleggsstonad.onnx;

public enum TilleggsstonadType {

    BOUTGIFT("BOUTGIFTER"),
    BOUTGIFTER_ARBEIDSSOKERE("BOUTGIFTER"),
    DAGLIG_REISE("DAGLIG_REISE"),
    DAGLIG_REISE_ARBEIDSSOKER("DAGLIG_REISE"),
    LAEREMIDLER("LAEREMIDLER"),
    LAEREMIDLER_ARBEIDSSOKERE("LAEREMIDLER"),
    FLYTTING("FLYTTING"),
    FLYTTING_ARBEIDSSOKERE("FLYTTING"),
    REISE_AKTIVITET_OG_HJEMREISER("REISE_VED_OPPSTART_OG_AVSLUTNING_AV_AKTIVITET_OG_HJEMREISE"),
    REISE_AKTIVITET_OG_HJEMREISER_ARBEIDSSOKERE("REISE_VED_OPPSTART_OG_AVSLUTNING_AV_AKTIVITET_OG_HJEMREISE"),
    REISESTONAD_TIL_ARBEIDSSOKERE("REISESTONAD_ARBEIDSSOKER"),
    REISE_TIL_OBLIGATORISK_SAMLING("REISESTONAD_OBLIGATORISK_SAMLING"),
    REISE_TIL_OBLIGATORISK_SAMLING_ARBEIDSSOKERE("REISESTONAD_OBLIGATORISK_SAMLING"),
    TILSYN_FAMILIEMEDLEMMER("TILSYN_FAMILIEMEDLEMMER"),
    TILSYN_FAMILIEMEDLEMMER_ARBEIDSSOKERE("TILSYN_FAMILIEMEDLEMMER"),
    TILSYN_BARN("TILSYN_BARN"),
    TILSYN_BARN_ARBEIDSSOKER("TILSYN_BARN");

    private final String resultField;

    TilleggsstonadType(String resultField) {
        this.resultField = resultField;
    }

    public String resultField() {
        return resultField;
    }

}
