--------------------------
-- D R O P   T A B L E  --
--------------------------

drop table whitelist;


---------------------------------
-- M O D I F Y   T A B L E S   --
---------------------------------

alter table personidentifikator
    drop column finnes_hos_skatt;

alter table ajourhold
    alter column id add generated by default as identity;

alter table personidentifikator
    alter column id add generated by default as identity;