plugins {
    id "dolly-apps"
}

sonarqube {
    properties {
        property "sonar.projectKey", "testnav-dollystatus"
        property "sonar.projectName", "testnav-dollystatus"
        property 'sonar.projectBaseDir', project.projectDir
        property 'sonar.sources', 'src/main/java,src/main/js/src'
        property "sonar.inclusions", "src/main/java/**,src/main/js/src/**"
        property "sonar.typescript.tsconfigPaths", "src/main/js/tsconfig.json"
        property "sonar.exclusions", "**/node_modules/**,src/main/js/node_modules/**,src/main/js/playwright/**,**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx"
    }
}

dependencies {
    developmentOnly "io.netty:netty-resolver-dns-native-macos::osx-aarch_64"
    developmentOnly "io.netty:netty-resolver-dns-native-macos::osx-x86_64"

    implementation "no.nav.testnav.libs:data-transfer-objects"
    implementation "no.nav.testnav.libs:reactive-core"
    implementation "no.nav.testnav.libs:reactive-security"
    implementation "no.nav.testnav.libs:security-core"
    implementation "no.nav.testnav.libs:slack"
    implementation "no.nav.testnav.libs:testing"

    implementation "org.springframework.boot:spring-boot-starter-oauth2-client"
    implementation "org.springframework.boot:spring-boot-starter-oauth2-resource-server"
    implementation "org.springframework.boot:spring-boot-starter-security"

    testImplementation "io.projectreactor:reactor-test"
    testImplementation "org.wiremock:wiremock-standalone:3.13.0"
    testImplementation "org.springframework.security:spring-security-test"
}
