CREATE TABLE TAGS
(
    TAG         VARCHAR(255) PRIMARY KEY,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE EREG_TAGS
(
    ID          SERIAL PRIMARY KEY,
    ORGNR       VARCHAR(255) REFERENCES EREG,
    TAG         VARCHAR(255) REFERENCES TAGS,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TPS_IDENTER_TAGS
(
    ID          SERIAL PRIMARY KEY,
    IDENT       VARCHAR(255) REFERENCES TPS_IDENTER(FNR),
    TAG         VARCHAR(255) REFERENCES TAGS,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);