export const initialValuesArbeidssoekerregisteret = {
	utfoertAv: 'SLUTTBRUKER',
	kilde: 'Dolly',
	aarsak: 'Registrering av arbeidssøker i Dolly',
	nuskode: '3',
	utdanningBestaatt: true,
	utdanningGodkjent: true,
	jobbsituasjonsbeskrivelse: 'HAR_BLITT_SAGT_OPP',
	jobbsituasjonsdetaljer: {
		gjelderFraDato: null,
		gjelderTilDato: null,
		stillingStyrk08: '00',
		stillingstittel: 'Annen stilling',
		stillingsprosent: '100',
		sisteDagMedLoenn: new Date(),
		sisteArbeidsdag: new Date(),
	},
	helsetilstandHindrerArbeid: false,
	andreForholdHindrerArbeid: false,
}
