CREATE TABLE OPPLYSNINGSPLIKTIG
(
    ID                  SERIAL PRIMARY KEY,
    ORGNUMMER           VARCHAR(64) NOT NULL,
    RAPPORTERINGSMAANED VARCHAR(64) NOT NULL,
    VERSION             INTEGER     NOT NULL,
    DOCUMENT            TEXT        NOT NULL,
    ENVIRONMENT         VARCHAR(64) NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);