CREATE TABLE DEPENDENCIES_VERSION
(
    HASH  BIGINT PRIMARY KEY,
    JSON      TEXT        NOT NULL
);

CREATE TABLE DEPENDENCIES_HISTORY
(
    ID            SERIAL PRIMARY KEY,
    HASH      BIGINT REFERENCES DEPENDENCIES_VERSION (HASH),
    REGISTERED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APPLICATION
(
    REGISTERED_NAME VARCHAR(256) PRIMARY KEY,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);