on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
      healthcheck:
        type: string
        required: true
    secrets:
      NAV_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Git"
        run: git fetch --unshallow
      - name: "Java"
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: 25
          distribution: 'temurin'
      - name: "Gradle"
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: false
      - name: "Auth"
        uses: nais/login@bb6c3e1e14e53d40d69d0d092bd2fce2e39ae3bf # v0
        with:
          team: dolly
      - name: "Build"
        env:
          NAV_TOKEN: ${{ secrets.NAV_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        run: ./gradlew assemble --scan
      - name: "Start docker containers"
        run: |
          JWK=$(cat ./mocks/jwk.json) docker compose up --build --detach
      - name: "Health check"
        timeout-minutes: 5
        run: |
          echo Wait on service...
          bash -c 'while [[ "$(curl --connect-timeout 2 -s -o /dev/null -w ''%{http_code}'' ${{ inputs.healthcheck }})" != "200" ]]; do echo ...; sleep 5; done; echo Service is up;'
      - name: "Run integration tests"
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: false
      - name: "Build"
        working-directory: ${{ inputs.working-directory }}
        run: ./gradlew iTest --scan
      - name: "Stop docker containers"
        run: |
          docker compose down --remove-orphans --volumes