name: Update Kafka Topics

on:
  push:
    branches:
      - master
    paths:
      - '.nais/topics.yml'
  workflow_dispatch:


jobs:
  deploy-kafka-topics-dev:
    name: Deploy to Aiven Dev
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
        env:
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: ".nais/topics.yml"