on:
  schedule:
    - cron: "0 9 * * MON"
  workflow_dispatch:
    inputs:
      working-directory:
        type: string
        description: "Directory to scan, e.g. apps/dolly-backend. Defaults to whole repo."
        default: "."
        required: true

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: "Markdown"
        uses: tcort/github-action-markdown-link-check@e7c7a18363c842693fadde5d41a3bd3573a7a225 # v1.1.2
        with:
          folder-path: ${{ inputs.working-directory }}
          config-file: .github/workflows/scheduled.scan.markdown.json
          use-quiet-mode: yes
      - name: "Slack"
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          webhook-type: webhook-trigger
          payload: |
            {
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEAD_URLS_WEBHOOK_URL }}
