on:
  schedule:
    - cron: "0 9 * * MON"
  workflow_dispatch:
    inputs:
      working-directory:
        type: string
        description: "Directory to scan, e.g. apps/dolly-backend. Defaults to whole repo."
        default: "."
        required: true

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Markdown"
        uses: tcort/github-action-markdown-link-check@e7c7a18363c842693fadde5d41a3bd3573a7a225 # v1.1.2
        with:
          folder-path: ${{ inputs.working-directory }}
          config-file: .github/workflows/scheduled.scan.markdown.json
          use-quiet-mode: yes
      - name: "Slack"
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook-type: webhook-trigger
          payload: |
            {
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEAD_URLS_WEBHOOK_URL }}
